vertica/vertica-kubernetes

- DEVELOPER.md
- Makefile
- README.md
- helm-charts/verticadb-operator/Chart.yaml
- helm-charts/verticadb-operator/values.yaml
- helm-charts/verticadb-webhook/Chart.yaml
- helm-charts/verticadb-webhook/values.yaml
- kuttl-soak-test-iteration-0.yaml
- scripts/wait-for-cert-manager-ready.sh
- Updates to the version and description of the helm charts
- Document installing the CRD from a YAML manifest
- Clarification in the DEVELOPER.md file
- Fixes to get the soak test running again
> Release preparation

- docker-vertica/packages/cleanup.sh
* This is a change to make minimal build work for `yes` or `YES`
> Added minimal variable to work with yes

- config/manifests/bases/verticadb-operator.clusterserviceversion.yaml
This has some copy edits to the CSV description.
> Copy edits for the CSV

- README.md
DEVELOPER link was broken, replaced with correct link.
> updated broken DEVELOPER link at the top of the repo

- docker-vlogger/README.md
previous link: https://github.com/vertica/vertica-kubernetes/blob/**main**/docker-vlogger/Dockerfile
updated link: https://github.com/vertica/vertica-kubernetes/blob/**v1.0.0**/docker-vlogger/Dockerfile
> Updated version link in vlogger README

- .github/actions/setup-e2e/action.yaml
- .github/actions/setup-go-kctx/action.yaml
- .github/workflows/scorecardtests.yml
- Makefile
This simply adds scorecard tests check to the CI. A new target has been added in the Makefile for that.
> Add scorecard tests to CI

- README.md
This update simplifies the README to provide a high-level overview of each section and point to the relevant areas of the Vertica.com docs. This simplifies the user experience and future doc upkeep.
> SP2 README revision

- Makefile
- helm-charts/verticadb-operator/Chart.yaml
- pkg/controllers/labels_annotations.go
Bumping the version now for the Feb 22 release of the operator.
> Bump operator version to 1.3.0

- DEVELOPER.md
This PR moves communal backend instruction, that was previously in a confluence page, in DEVELOPER.md.
> Move communal backend instruction in DEVELOPER.md

- README.md
- docker-operator/README.md
- docker-vertica/README.md
Added details and links about:
- OpenShift support
- Logging options with Helm
- Naming service objects with client connections
- Operator version update to 1.3.0
- Vertica server version updates to 11.1.0-0
> README doc updates

- .github/actions/setup-e2e/action.yaml
- .github/actions/setup-kubectl/action.yaml
- .github/workflows/verify-public-artifacts.yml
This adds a new workflow that we can use to verify the public artifacts
(helm charts + olm) after a release.
> Add a workflow to test the public artifacts

- Makefile
- docker-operator/README.md
- helm-charts/verticadb-operator/Chart.yaml
- helm-charts/verticadb-operator/README.md
- helm-charts/verticadb-operator/values.yaml
- pkg/builder/labels_annotations.go
This is prep for the next release, which has a TBD release date.
> Bump operator version to 1.9.0

- .github/workflows/release.yml
- scripts/create-release.sh
I had the first run of the release GitHub actions. There were some bugs with it. This PR has the fixes for that. Hopefully, next release things go a bit smoother.
> Fixes for the release workflow

- Makefile
This is try and minimize the number of times network issues cause the e2e runs to fail.
> Add retry to all curl commands

- pkg/controllers/vdb/podfacts.go
- pkg/controllers/vdb/podfacts_test.go
This ensures we try to use the same pod when calling various AT commands. When picking a pod, we always sort all pods that qualify and then use the one with the lowest statefulset index.
This is necessary for remove node. If we end up using a pod that is actually being removed, we run the risk the livenessProbe could actually delete the pod that is running the AT commands.  This bug isn't exposed in older release of the operator because the livenessProbe is new to this current release.
> Use a deterministic pod for AT commands

- README.md
New section with link to supported platforms docs.
> added supported platforms section

- .github/actions/setup-e2e/action.yaml
- .github/workflows/build-images.yml
- .github/workflows/e2e.yml
- Makefile
- docker-vertica/Dockerfile
- docker-vertica/Makefile
This part is about adding the new build image "nokeys".  After we change the jenkins process to  build "nokeys", we will remove the build image "nosshkeys".
> rename nosshkeys to nokeys, part 1

- .github/workflows/build-images.yml
- .github/workflows/e2e.yml
Phase 2 of renaming nosshkeys to nokeys
This is to remove the nosshkeys name.  The nokeys name has already been added.
> rename nosshkeys to nokeys, part 2

- Makefile
- scripts/wait-for-cert-manager-ready.sh
These came up while onboarding a new developer to this repo.
> Minor dev environment fixes

- tests/e2e-leg-2/restart-sanity/35-kill-three-pods.yaml
This fixes a timing hole introduced by a recent change.
> Fix timing in restart-sanity e2e test

- Makefile
- docker-vertica/Makefile
- scripts/create-k8s-user.sh
- scripts/dockerfile-lint
- scripts/gen-csv.sh
- scripts/gen-release-artifacts.sh
- scripts/setup-e2e-udx.sh
- scripts/setup-kustomize.sh
- scripts/template-helm-chart.sh
This is updates to the dev environment based on what we found while trying to develop the operator on macOS with an ARM based chip.
> Make the operator dev environment macOS ARM friendly

- scripts/guess-server-upgrade-base-image.sh
This is another attempt at picking the proper base image for the server upgrade tests. My previous attempt in #456 didn't handle the case where the CI is run against main. That run will use the public RPM, so upgrade base should be from 12.0.2.
> Pick base image for e2e server upgrade tests for main branch

- go.mod
- go.sum
- pkg/controllers/vdb/dbaddnode_reconciler.go
- pkg/controllers/vdb/install_reconciler.go
- pkg/controllers/vdb/podfacts.go
- pkg/vadmin/add_node_vc.go
- pkg/vadmin/add_node_vc_test.go
- pkg/vadmin/interface.go
- pkg/vadmin/opts/addnode/opts.go
- pkg/vadmin/vc_errors.go
- pkg/vadmin/vc_errors_test.go
- tests/e2e-vcluster/vcluster-ks-0/17-assert.yaml
Adds the logic for using VClusterOps library to add nodes to a subcluster.
> Implemented VClusterOps.AddNode() 

- go.mod
- go.sum
Applied the latest vcluster library in k8s operator.
> Update vclusterops library

- go.mod
- go.sum
- pkg/vadmin/interface.go
- pkg/vadmin/remove_node_vc.go
- pkg/vadmin/remove_sc_vc.go
- pkg/vadmin/remove_sc_vc_test.go
- tests/e2e-vcluster/vcluster-ks-0/30-assert.yaml
- tests/e2e-vcluster/vcluster-ks-0/30-remove-sc2.yaml
Adds the logic for using VClusterOps library to remove a subcluster.
> Implemented VClusterOps.RemoveSubcluster()

- pkg/builder/builder.go
This is prep for when the NMA will directly read the cert from the secret store. We store the namespace and name of the secret in these environment variables: NMA_SECRET_NAMESPACE, NMA_SECRET_NAME
This applies only to the vclusterops based deployments.
This is for jira VER-88251
> Store name of NMA cert in environment variable

- go.mod
- go.sum
Apply the latest version of vclusterops on the operator to check if some bugs are fixed.
> VCluster API Refresh

- docker-vertica-v2/Dockerfile
Add ENV instruction in v2 vertica image Dockerfile to make JAVA_HOME env var available in all server containers
> Set the JAVA_HOME environment variable in the Vertica v2 container

- scripts/undeploy.sh
Matt helped me update `undeploy.sh` to allow automatic helm cleanup after running an e2e test.
> Update the undeploy script to allow automatic helm cleanup

- pkg/kstepgen/options.go
- pkg/kstepgen/scaling.go
- tests/soak/soak-sample.cfg
The kuttl-step-gen tool, which is used for our soak tests, needs to be updated to reflect the recent changes to the v1 API.
> Update kuttl-step-gen for new field names

- api/v1/verticadb_webhook.go
- api/v1/verticadb_webhook_test.go
Add webhook check for sc type so that only allowed values are "primary", "secondary", and "transient".
Add relevant webhook tests as well.
> Add webhook check for sc type

- pkg/controllers/vdb/dbaddnode_reconciler.go
- Add logic in `dbaddnode_reconciler.go` so that between each successive invocations of `reconcileSubcluster()` the `PFacts` will be invalidated and recollected from the cluster, which ensures the correct options are passed in each invocation of `AddNode()`
> fix dbaddnode_reconciler error

- api/v1/verticadb_types.go
- docker-vertica/s6-rc.d/cron/run
We have to run cron under sudo. Without this fix we get this error repeated: "setuid: Operation not permitted"
> Fix issue preventing cron from starting in v1 container

- pkg/builder/builder.go
- pkg/controllers/vdb/podfacts.go
- pkg/controllers/vdb/restart_reconciler.go
This change addresses a timing issue with the new NMA sidecar and drop node. If the drop node process is interrupted, it is possible that the next reconcile iteration will attempt to restart the pod. However, this restart will fail because the pod may no longer be in the database, which will cause the restart to fail. This change addresses this issue by skipping pods in this state during restart.
> Fix timing with NMA sidecar and drop node

- scripts/capture-scrutinize.sh
This is to allow scrutinize to run successfully on the main branch.
> Fix e2e test for scrutinize

- tests/e2e-udx/udx-cpp/70-verify-cpp-source.yaml
This fixes `udx-cpp` that's been failing since May the 30th.
> Fix udx-cpp

- pkg/controllers/vdb/onlineupgrade_reconciler.go
This PR added some checks to make sure sandboxing and sandbox-upgrade will be executed.
> Improved reliability of online upgrade

- go.mod
- go.sum
- pkg/controllers/vdb/sandboxsubcluster_reconciler.go
- pkg/mockvops/mockvops.go
- pkg/vadmin/interface.go
- pkg/vadmin/opts/pollscstate/pollscstate.go
- pkg/vadmin/poll_sc_state_at.go
- pkg/vadmin/poll_sc_state_vc.go
- pkg/vadmin/suite_test.go
- tests/e2e-leg-9/verify-vrep/08-wait-for-steady-state.yaml
fixes an issue where if pods are removed during sandboxing they will never be brought back up
> poll for subcluster up in un/sandbox

- .github/workflows/e2e.yml
1. Fix Notification to be triggered only by k8s-sync job
2. Fix the contains logic to trigger job
> Fix teams notification

- .github/actions/run-e2e-leg/action.yaml
- .github/actions/setup-e2e/action.yaml
- .github/workflows/build-images.yml
- .github/workflows/e2e.yml
- scripts/setup-kustomize.sh
- tests/e2e-leg-6/verify-server-logrotate/08-upload-files.yaml
- tests/e2e-leg-6/verify-server-logrotate/setup-env-runtime.sh
- tests/e2e-udx/udx-cpp/30-upload-files.yaml
- tests/e2e-udx/udx-cpp/setup-env-runtime.sh
- tests/e2e-udx/udx-java/30-upload-files.yaml
- tests/e2e-udx/udx-java/setup-env-runtime.sh
- tests/e2e-udx/udx-python/30-upload-files.yaml
- tests/e2e-udx/udx-python/setup-env-runtime.sh
This PR is a follow-up task of #902. We don't want to download packages from RHEL operating system inside Vertica image because we don't have VPN access in Github. This time we will assume all packages are installed beforehand.
> Fixed e2e tests

- api/v1/helpers.go
- pkg/controllers/vdb/onlineupgrade_reconciler.go
- pkg/controllers/vdb/onlineupgrade_reconciler_test.go
- pkg/controllers/vdb/upgrade.go
- pkg/events/event.go
- pkg/mockvops/mockvops.go
- pkg/vadmin/interface.go
- pkg/vadmin/manage_connection_draining_at.go
- pkg/vadmin/manage_connection_draining_vc.go
- pkg/vadmin/manage_connection_draining_vc_test.go
- pkg/vadmin/opts/getconfigparameter/opts.go
- pkg/vadmin/opts/manageconnectiondraining/opts.go
add support to the operator for pausing and redirecting client connections during upgrade
> pause & redirect during online upgrade

- .github/workflows/build-images.yml
This PR add an action to check if docker image exists on remote internal repo(github private repo), if not we will push to it during the image build step.
> add check to push image

- .github/workflows/build-images.yml
That last PR added cmd docker manifest inspect IMAGE into non pr cases. However the pipeline will detect the exit code and stop the following tasks. Wrapped the cmd into a variable result, so the pipeline will ignore the exit code.
Also fixed a typo $.
> fix run condition

- changes/unreleased/Added-20240930-175706.yaml
- pkg/controllers/vdb/saverestorepoint_reconciler.go
- pkg/vadmin/create_archive_vc.go
Some small changes like adding a changie entry for restore point and letting the user know through an event that the archive already exists.
> Restore point update

- .github/CODEOWNERS
- api/v1/helpers.go
- api/v1/verticadb_webhook_test.go
- api/v1beta1/verticadb_types.go
- config/manifests/bases/verticadb-operator.clusterserviceversion.yaml
- pkg/aterrors/aterrors_test.go
- pkg/vdbgen/vdb_test.go
This is a simple PR to update the contacts
> Modified the contacts

- scripts/push-vertica-server-image.sh
Publish multiarch k8 images to public repo. -only run for major/minor releases
> push multiarch k8 image to public repo

- api/v1/version.go
> fix IsPausedSessionsSupported

- README.md
This PR simply added security vulnerability policy.
> Added security vulnerability policy

- go.mod
- go.sum
- pkg/vadmin/replication_start_vc.go
- pkg/vadmin/suite_test.go
This PR applied recent vclusterOps to K8s operator.
> Refresh vclusterOps

- Makefile
- config/manifests/bases/verticadb-operator.clusterserviceversion.yaml
- go.mod
- go.sum
This PR enhances the stability of the Istio tests by upgrading the istioctl version and refining the create_db process in vclusterOps.
> Fixed istio tests

- .github/workflows/e2e.yml
- go.mod
- go.sum
- pkg/controllers/vdb/restart_reconciler.go
- pkg/controllers/vdb/upgrade.go
- pkg/controllers/vdb/verticadb_controller.go
Picked up Vivek's two unsandboxing PRs.
> update vcluster package version

- DEVELOPER.md
Update developer doc for prometheus deployment. Content based on confluence page: https://confluence.verticacorp.com/display/DEV/Prometheus+for+Vertica+K8S+Server+pods
> Update developer doc for prometheus

- .github/workflows/build-images.yml
- .github/workflows/e2e.yml
Use a working image to pass CICD temporarily.
> Temporary fix for CICD

- api/v1beta1/verticaautoscaler_types.go
- config/manifests/bases/verticadb-operator.clusterserviceversion.yaml
This adds UI hints that will allow setting the autoscaler fields from Openshift UI.
> Fix Openshift UI

- api/v1/verticaautoscaler_webhook.go
- api/v1/verticaautoscaler_webhook_test.go
follow up PR for fixing issue found in https://ot-internal.saas.microfocus.com/ui/?p=4001/37001#/entity-navigation?entityType=work_item&id=4391196
> fix value structure and add unit test

- api/v1/helpers.go
- api/v1/verticaautoscaler_webhook.go
- api/v1/verticaautoscaler_webhook_test.go
Fix some nil pointer edge cases on vas webhook validation.
> Vas webhook fix

- .github/workflows/build-images.yml
This is a simple change. Server side fixed the issue so we could use daily build in e2e test again.
> Use daily build to verify e2e test

- api/v1/verticaautoscaler_types.go
- api/v1/verticadb_types.go
- api/v1/verticadb_webhook.go
- api/v1beta1/verticaautoscaler_types.go
- changes/unreleased/Added-20250204-161432.yaml
- changes/unreleased/Removed-20250204-162421.yaml
- config/manifests/bases/verticadb-operator.clusterserviceversion.yaml
- config/samples/v1_verticaautoscaler.yaml
- config/samples/v1beta1_verticaautoscaler.yaml
- pkg/controllers/vdb/tlsservercertgen_reconciler.go
- pkg/controllers/vdb/verticadb_controller.go
Minor changes before release: we don't plan to release clientservertls so we don't want it to show up in the CR
> Remove clientservertls from code

- .github/actions/run-e2e-leg/action.yaml
- .github/workflows/e2e.yml
- scripts/setup-kustomize.sh
This allows us to run existing vcluster legs with and without cert.
> Add new jobs to run legs with cert

- .github/workflows/e2e.yml
- pkg/controllers/vdb/createdb_reconciler.go
This fixes a password issue and run leg 12 with cert.
> Fix leg 12

- .github/workflows/build-images.yml
This will hard code the image name that will be used for admintools tests.
I also replace replace the switch-case-actions.
> Hard code legacy image name

- pkg/controllers/vdb/createdb_reconciler.go
This is to fix unit test failure (lint complaints)
> remove useless markers

- .github/workflows/build-images.yml
- .github/workflows/e2e.yml
- docker-vertica-v2/packages/package-checksum-patcher.py
- docker-vertica/packages/package-checksum-patcher.py
Build process is not stable recently so I add retry process to it. By default, the build will automatically retry up to 3 times upon failure.
> Added retry times for build process

- .github/workflows/e2e.yml
- pkg/reviveplanner/analyze.go
- pkg/reviveplanner/analyze_test.go
- pkg/vadmin/create_db_vc.go
When the USER locations are all remote locations (e.g. s3 locations), revive_db will return an error "no local paths found". I removed that error since this is a valid case.
> Fixed s3 path issue

- config/rbac/leader_election_role.yaml
- scripts/template-helm-chart.sh
> Fix rbac rules leader election and manager roles

- .github/workflows/build-images.yml
- api/v1/helpers.go
- pkg/controllers/vdb/httpscertrotation_reconciler.go
- pkg/meta/annotations.go
- pkg/vadmin/set_tls_config_vc.go
This adds an annotation to control how long to keep the cache.
> Set cache duration

- .github/workflows/e2e.yml
- local-libs/vcluster/vclusterops/coordinator_database.go
- tests/e2e-leg-8-online/readonly-online-upgrade-through-vclusterops/20-pull-images.yaml
- tests/e2e-leg-8-online/readonly-online-upgrade-through-vclusterops/41-wait-for-upgrade.yaml
- tests/e2e-leg-8-online/readonly-online-upgrade-through-vclusterops/42-wait-for-steadystate copy.yaml
- tests/e2e-leg-8-online/readonly-online-upgrade-through-vclusterops/45-assert.yaml
- tests/e2e-leg-8-online/readonly-online-upgrade-through-vclusterops/45-upgrade-to-24-1.yaml
- tests/e2e-leg-8-online/readonly-online-upgrade-through-vclusterops/46-wait-for-upgrade.yaml
- tests/e2e-leg-8-online/readonly-online-upgrade-through-vclusterops/47-wait-for-steadystate.yaml
This PR will fix e2e-leg8-admintools-online.
> Fix admintool test

- api/v1/helpers.go
- api/v1/verticadb_webhook.go
- api/v1/verticadb_webhook_test.go
- pkg/controllers/sandbox/unsandboxsubcluster_reconciler.go
- pkg/controllers/vdb/clientservertlsupdate_reconciler.go
- pkg/controllers/vdb/httpstlsupdate_reconciler.go
- pkg/controllers/vdb/unsandboximageversion_reconciler.go
- pkg/controllers/vdb/verticadb_controller.go
- pkg/vadmin/unsandbox_sc_vc.go
- pkg/vk8s/meta_updater.go
- tests/e2e-leg-10-sandbox-basic/sandbox-basic/60-assert.yaml
- tests/e2e-leg-10-sandbox-basic/sandbox-basic/65-wait-for-steady-state.yaml
- tests/e2e-leg-10-sandbox-basic/sandbox-basic/70-assert.yaml
- tests/e2e-leg-10-sandbox-basic/sandbox-basic/71-wait-for-steady-state.yaml
- Fix missing field in tls secret check
- improve operator upgrade
- improve unsandboxing and make sandbox-basic more stable
> Fix some issues

- .github/actions/run-e2e-leg/action.yaml
- .github/workflows/e2e.yml
- .gitignore
- Makefile
- helm-charts/verticadb-operator/Chart.yaml
- helm-charts/verticadb-operator/values.yaml
- kuttl-test.yaml
- tests/e2e-leg-14/deploy-with-grafana-prometheus/05-assert.yaml
- tests/e2e-leg-14/deploy-with-grafana-prometheus/05-deploy-operator.yaml
- tests/e2e-leg-14/deploy-with-grafana-prometheus/99-delete-ns.yaml
Now by installing the operator we will also install a prometheus and grafana instance.
This sets common parameters for now. 
A new leg has been added. For now it just checks if grafana and prometheus have been installed with the operator
> Add grafana and prometheus to helm chart

- pkg/controllers/vdb/restart_reconciler.go
- pkg/podfacts/podfacts.go
- tests/e2e-leg-10-shutdown/sandbox-shutdown/73-assert.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/73-shutdown-sec3-in-sandbox1.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/75-assert.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/75-delete-pods-in-sec1.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/78-assert.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/78-wait-for-sec1-to-be-up.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/80-assert.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/80-shutdown-sec2-in-main.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/83-assert.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/83-delete-pods-in-pri1.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/85-assert.yaml
- tests/e2e-leg-10-shutdown/sandbox-shutdown/85-wait-for-pri1-to-be-up.yaml
This PR fixed the issue: when a subcluster is shut down, the other primary subclusters cannot be restarted in that cluster.
> Fixed restart issue
