docker-vertica/docker-entrypoint.sh, docker-vertica/packages/init.d.functions, pkg/controllers/actor.go, pkg/controllers/agent_reconcile_test.go, pkg/controllers/agent_reconciler.go, pkg/controllers/createdb_reconcile.go, pkg/controllers/dbaddnode_reconcile.go, pkg/controllers/dbaddsubcluster_reconcile.go, pkg/controllers/dbremovesubcluster_reconcile.go, pkg/controllers/install_reconcile.go, pkg/controllers/install_reconcile_test.go, pkg/controllers/obj_reconcile.go, pkg/controllers/podfacts.go, pkg/controllers/restart_reconcile.go, pkg/controllers/revivedb_reconcile.go, pkg/controllers/status_reconcile.go, pkg/controllers/suite_test.go, pkg/controllers/version_reconciler.go, pkg/controllers/verticadb_controller.go
Prior to this, the vertica agent was being started in the docker entrypoint.  This led to some race conditions -- starting the agent at the same time we are doing create_db or scale-out.  The race conditions often ended up causing the admintools.conf to be corrupted.  The file had all of the host information removed and it was owned by root.
The fix was to give the operator the control over when the agent starts.  This avoids the race conditions because there is only a single operator thread running.  A new `ReconcileActor` called `AgentReconciler` was added.  This is called right after the database is created or revived.
This also has some cleanup for `ReconcilerActor`.  All of the actors had to have common boilerplate functions (`GetClient`, `GetVDB`, `CollectPFacts`).  Only two of the …
=> Operator to control starting of vertica agent

tests/e2e-disabled/restart-node-multi-sc/00-minio.yaml, tests/e2e/auto-restart-vertica/00-minio.yaml, tests/e2e/client-access/05-minio-create.yaml, tests/e2e/crash-before-createdb/00-minio.yaml, tests/e2e/createdb-failures/30-setup-minio-tenant.yaml, tests/e2e/k-safety-0-scaling/00-minio.yaml, tests/e2e/k-safety-1-scaling/00-minio.yaml, tests/e2e/kill-controller/00-minio.yaml, tests/e2e/kill-during-add-node/05-minio.yaml, tests/e2e/multi-sc/02-minio.yaml, tests/e2e/private-pvc/10-minio-create.yaml, tests/e2e/restart/00-minio.yaml, tests/e2e/revivedb-1-node/05-minio-create.yaml, tests/e2e/revivedb-3-node/05-minio-create.yaml, tests/e2e/revivedb-failures/05-minio-create.yaml, tests/e2e/revivedb-multi-sc/05-minio-create.yaml, tests/e2e/update-strategy/00-minio.yaml, tests/e2e/upgrade-vertica/00-minio.yaml, tests/e2e/vdb-gen/00-minio.yaml, tests/e2e/webhook/05-minio-create.yaml
Adding a label 'stern=include' to minio so that it is included in the ancillary.log when running e2e tests (see logic in scripts/save-ancillary-logs.sh)
=> Include minio output in ancillary.log for e2e runs

docker-vertica/Dockerfile
Get the latest yum updates closes a bunch of vulnerabilities detected by snyk.  This adds about 100MB to the minimal image (786MB -> 892MB).
=> Fix vulnerabilities in vertica-k8s

.github/workflows/e2e.yml, .github/workflows/unittests.yml, Makefile, README.md, scripts/kind.sh, scripts/run-k8s-int-tests.sh
One of the e2e tests was failing consistently because we were hitting disk full.  I reduced the disk usage by changing the kind cluster we set from 2 nodes to 1 node.  This helps reduced the amount of disk needed because we only had to push the containers to 1 k8s node now instead of 2.
Also changed the name of the tests in GitHub actions from build to e2e/ut.
=> Reduce disk usage of e2e tests

DEVELOPER.md, changes/unreleased/Fixed-20210831-083212.yaml, cmd/operator/main.go, kuttl-soak-test-iteration-0.yaml, kuttl-test.yaml, pkg/controllers/createdb_reconcile.go, pkg/controllers/init_db.go, pkg/controllers/revivedb_reconcile.go, pkg/events/event.go, scripts/kuttl-test-loop.sh, tests/e2e/createdb-failures/18-assert.yaml, tests/e2e/createdb-failures/18-bad-creds-forcing-auth-parms-cp-failure.yaml
The operator had set AWS timeouts low so that during create_db we get quick feedback in case the s3 endpoint isn't setup correctly.  These low timeouts were interfering with the create_db in such a way as preventing a successful create on aws s3.  The timeouts were removed in this commit.  This also means we cannot reliable check for this error in the createdb-failures testcase.
A few other minor changed in included:
- adding event recording for when the s3 auth parms copy fails.  It is possible that if the secret was not setup correctly that the copy would contain undisplayable characters causing the entire copy to fail.  We log an event now so that end users have a better idea of what issue the operator is hitting.
- when running the operator with the 'make run' target, we need the …
=> Fix to allow create DB to work on AWS s3

Makefile, scripts/kind.sh
On some internal machines, we were having issues creating a kind cluster
when we moved to k8s 1.21.1.  Bumping the kind version helped.  This
also changes how we get kind -- it is now downloaded into the repo's bin
directory like other tools.
=> Bump kind version to 0.11.1

docker-vertica/docker-entrypoint.sh, pkg/controllers/builder.go
This adds logic to the docker entrypoint to ensure we have proper write permissions to the PV directories.  If we don't have write permissions, it will do a chown to correct it.  This is needed depending on the storage that backs the PV.
=> Support PVs that don't have dbadmin write access

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_webhook.go, changes/unreleased/Fixed-20210921-104327.yaml, pkg/controllers/createdb_reconcile.go, pkg/controllers/createdb_reconcile_test.go, pkg/controllers/init_db.go, pkg/events/event.go, pkg/vdbgen/vdb.go
This adds a new parameter to `.spec.communal` to allow the s3 region to be specified.  Prior to this, we would always use the Vertica default of us-east-1.  The webhook was updated to fill in the region if it wasn't set.  This way it will be clear what the default region rather than relying on the default set in the server.  The events were added to make it more visible when the region is misconfigured.
Closes #60.
=> Allow s3 region to be specified

.changie.yaml, changes/unreleased/Added-20210825-151346.yaml, changes/unreleased/Added-20210916-144455.yaml, changes/unreleased/Added-20210920-171923.yaml, changes/unreleased/Added-20210923-133214.yaml, changes/unreleased/Changed-20210823-142529.yaml, changes/unreleased/Changed-20210825-091644.yaml, changes/unreleased/Changed-20210827-140240.yaml, changes/unreleased/Changed-20210923-133510.yaml, changes/unreleased/Fixed-20210831-083212.yaml, changes/unreleased/Fixed-20210920-092151.yaml, changes/unreleased/Fixed-20210921-104327.yaml
There were some changie entries that were missed in the current release.  This also adds issue numbers to each changie entry so that we can include a link to the PR in the changelog.
=> Add missing changie entries for next release

pkg/controllers/install_reconcile.go
There was a small timing window that is closed with this change.  It was
caught in the crash-before-createdb testcase.  The order in install was
to add hosts to admintools.conf then accept the EULA.  If the pod is
rescheduled between these, we would attempt a re_ip before coming back
and completing the install.  But the re_ip kept failing because the EULA
wasn't accepted.   The solution was to accept the EULA *before* adding
the hosts to the admintools.conf.
=> Fix timing issue with install reconcile

pkg/controllers/imagechange_reconcile.go, pkg/controllers/podfacts.go, pkg/controllers/podfacts_test.go, pkg/controllers/restart_reconcile.go, pkg/controllers/restart_reconciler_test.go, tests/e2e/revivedb-failures/08-delete-clean-s3-pod.yaml, tests/e2e/vdb-gen/08-delete-clean-s3-pod.yaml
This addresses two scenarios related to the restart reconciler:
- Saw an issue during restart where it wouldn't do the restart as part of the image change reconcile.  The image change reconciler would skip the entire restart, and so it wouldn't happen until the restart reconciler.  Functionally, there is no issue here.  It just looks a bit weird in the events because it claimed the image change was successful then proceeds to restart Vertica after that.
- If some pods are not running, the restart reconciler should requeue.  Prior to this change it was possible for it to exit cleanly.  This could leave the operator in a state where it wouldn't restart a down pod.
=> Fix restart reconciler timing scenarios

.github/workflows/e2e.yml, Makefile, scripts/run-k8s-int-tests.sh, scripts/setup-krew.sh
Will download and install krew through a make target.  This will also harden the krew version rather than always getting latest.
=> Install krew through make target

Makefile, config/manager/kustomization.yaml, helm-charts/verticadb-operator/Chart.yaml, helm-charts/verticadb-operator/tests/image-name-and-tag_test.yaml, helm-charts/verticadb-operator/values.yaml, scripts/gen-csv.sh
To get ready for the October release, this bumps the version to 1.1.0.  There is also a fix in here to ensure we generate the proper operator image name -- both for helm and olm.
=> Bump version and fix generation of operator image name

Makefile, scripts/kind.sh, scripts/push-to-kind.sh, scripts/run-k8s-int-tests.sh
The -x option in kind.sh will now be used to skip killing of the registry.
Also changed the default deployment method for e2e tests to be helm.  When running the e2e tests in the CI it will randomly pick between helm and olm.
=> kind.sh term to delete registry by default

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_types_test.go, api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go, changes/unreleased/Added-20211029-083036.yaml, pkg/controllers/builder.go, pkg/controllers/createdb_reconcile.go, pkg/controllers/install_reconcile.go, pkg/controllers/install_reconcile_test.go, pkg/controllers/paths.go, pkg/controllers/podfacts.go, pkg/controllers/podfacts_test.go, pkg/controllers/revivedb_reconcile.go, pkg/controllers/uninstall_reconcile.go, pkg/paths/paths.go, tests/e2e/create-and-del-crd/02-custom-volume-mounts.yaml, tests/e2e/create-and-del-crd/setup-vdb/base/setup-vdb.yaml
This adds the ability to add custom volume mounts to the Vertica container.  A new `spec.volumeMounts` parameter was added to achieve this.  It works alongside the `spec.volumes` parameter.
Here is an example that mounts the path /tenants in the Vertica container using an existing PVC.  
```
metadata:
name: verticadb-sample
spec:
communal:
...
subclusters:
- name: sc1
volumeMounts:
- mountPath: /tenants
name: tenants
volumes:
- name: tenants
persistentVolumeClaim:
claimName: vertica-pvc
```
The volumeMounts parameter takes the standard set of options for volume mounts (e.g. same as pod.spec.containers.volumeMounts).
The mount path for the new volume mount cannot conflict with any existing.  The webhook was updated to detect any conflicts.
To …
=> Allow custom mount points to be added to vertica

api/v1beta1/verticadb_webhook.go, pkg/controllers/builder.go, pkg/controllers/init_db.go, pkg/controllers/init_db_test.go, pkg/controllers/obj_reconcile.go, pkg/controllers/obj_reconcile_test.go, pkg/events/event.go, pkg/names/names.go, pkg/paths/paths.go, pkg/vdbgen/vdb.go
The Vertica engine has very specific requirements for the Kerberos keytab: it must have read/write permissions for dbadmin and no one else.  It isn't possible to mount a file in k8s with specific requirements.  I originally added a hack that created an initContainer and copied the keytab so that the permissions could be set.  I'm removing that here as we now have a config knob in the engine to relax the check.  We just have to set `KerberosEnableKeytabPermissionCheck = 0`, and the engine won't care about keytab permissions.  This also means we don't need to restart the pod whenever the keytab changes as the change will get automatically picked up whenever the Secret changes.  Since this relies on an engine change, I put in a version check that Kerberos cannot be used except on 11.0.2.
=> Remove the Kerberos initContainer hack

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_webhook.go, changes/unreleased/Added-20211122-155946.yaml, pkg/controllers/builder.go, pkg/controllers/obj_reconcile.go, pkg/controllers/obj_reconcile_test.go, pkg/names/names.go, pkg/paths/paths.go, tests/e2e/k-safety-0-scaling/.gitignore, tests/e2e/k-safety-0-scaling/08-create-ssh-keys.yaml
This adds the ability to specify a custom ssh keys in the container.  The keys, stored in a Secret, will get mounted in /home/dbadmin/.ssh.  If this Secret is omitted, the ssh files from the image are used.  You can this option if you have a cluster that talks to Vertica notes outside of Kubernetes, as it has the public keys to be able to ssh to those nodes.  
The secret can be installed in the CR like this:
```
metadata:
name: v
spec:
communal:
...
subclusters:
- name: sc1
sshSecret: ssh-key  
```
It must have the following keys present: id_rsa, id_rsa.pub and authorized_keys.
=> Add ability to specify custom ssh keys

pkg/controllers/builder.go
Deploy a multi nodes cluster on Openshift fail because nodes cannot ssh each other.
This security context is added to enable that.
=> Add security context to enable ssh on Openshift

pkg/controllers/builder.go
With the security context added to enable ssh on pods on Openshift, it is necessary to have pods associated to privileged scc.
For that, instead of running them with default serviceaccount, we reference the operator serviceaccount which of course is to be associated to a privileged scc in the CSV. This will not break helm install as among the manifests generated in the chart there is already a service account with the same name.
=> Add serviceaccount to run pods with

tests/e2e-extra/revivedb-multi-sc/01-assert.yaml, tests/e2e-extra/vdb-gen/53-assert.yaml, tests/e2e-extra/vdb-gen/53-rbac.yaml, tests/e2e/client-access/20-assert.yaml, tests/e2e/client-access/20-rbac.yaml, tests/e2e/mount-certs/23-assert.yaml, tests/e2e/mount-certs/23-rbac.yaml, tests/e2e/multi-sc/17-assert.yaml, tests/e2e/multi-sc/17-rbac.yaml, tests/e2e/schedule-only/30-assert.yaml, tests/e2e/schedule-only/30-rbac.yaml, tests/e2e/update-strategy/01-assert.yaml, tests/e2e/update-strategy/01-rbac.yaml
This closes a timing scenario with e2e when creating common cluster scoped objects, like a ClusterRole.  If two tests create the objects at the same time (via kubectl apply), it is possible to get a failure.  
```
logger.go:42: 12:51:31 | vdb-gen/53-rbac | starting test step 53-rbac
logger.go:42: 12:51:31 | vdb-gen/53-rbac | running command: [sh -c kubectl apply --namespace $NAMESPACE -f ../../manifests/rbac/base/rbac.yaml]
=== CONT  kuttl/harness/revivedb-multi-sc
logger.go:42: 12:51:31 | revivedb-multi-sc/0-deploy-operator | test step completed 0-deploy-operator
logger.go:42: 12:51:31 | revivedb-multi-sc/1-rbac | starting test step 1-rbac
logger.go:42: 12:51:31 | revivedb-multi-sc/1-rbac | running command: [sh -c kubectl apply --namespace $NAMESPACE -f …
```
=> Handle concurrent updates to rbac during e2e tests

Makefile, changes/unreleased/Fixed-20211126-104134.yaml, pkg/controllers/podfacts.go
This closes a timing window during upgrade where we can indicate the image change has finished before completing the restart of the pods.  There is a check during the restart portion that calls `areAllPodsRunningAndZeroInstalled`.  This returns true if none of the pods exist yet, which is not correct.  State that the function uses was being set after checking if the pod exists.  If the pod doesn't exist, the state was left unset.  The timing hole is closed now that the state is being set correctly.
=> Image change can be marked complete before restart of the pods

tests/e2e/labels-annotations/04-delete-crd.yaml, tests/e2e/upgrade-vertica-ks-0/15-assert.yaml, tests/e2e/upgrade-vertica-ks-0/20-assert.yaml, tests/e2e/upgrade-vertica-ks-0/20-upgrade-vertica.yaml, tests/e2e/upgrade-vertica-ks-0/35-assert.yaml, tests/e2e/upgrade-vertica-ks-0/35-upgrade-and-scale-up.yaml, tests/e2e/upgrade-vertica-ks-0/40-assert.yaml, tests/e2e/upgrade-vertica-ks-0/40-upgrade-and-scale-down.yaml, tests/e2e/upgrade-vertica-ks-0/50-upgrade-vertica.yaml, tests/e2e/upgrade-vertica-ks-0/55-assert.yaml, tests/e2e/upgrade-vertica-ks-0/70-upgrade-vertica.yaml, tests/e2e/upgrade-vertica-ks-0/75-assert.yaml, tests/e2e/upgrade-vertica-ks-0/setup-vdb/base/setup-vdb.yaml, tests/e2e/upgrade-vertica-ks-1/25-assert.yaml, tests/e2e/upgrade-vertica-ks-1/35-assert.yaml, tests/e2e/upgrade-vertica-ks-1/35-upgrade-vertica.yaml, tests/e2e/upgrade-vertica-ks-1/setup-vdb/base/setup-vdb.yaml, tests/external-images.txt, tests/manifests/image-pull/upgrade-vertica-1/configmap.yaml
upgrade-vertica-ks-0/1 fail because of the use of the version 11.0.0 of the vertica image. We replaced it with version 11.0.1 and updated all related files.
=> Change vertica image version

kuttl-soak-test-iteration-0.yaml, scripts/run-k8s-int-tests.sh, scripts/setup-minio.sh, scripts/setup-olm.sh, tests/external-images-build.txt, tests/external-images-common-ci.txt, tests/external-images-gc-ci.txt
Some of the CI tests are failing because we run out of disk space on the machines that run CI.  This reduces the number of images we need to push into the kind cluster prior to the e2e run.  There were some images that weren't needed for e2e.  Just needed for setup of the kind cluster itself.  So this PR moves some of those images into a new file external-images-build.txt.
=> Reduce space requirements when running e2e in CI

docker-vlogger/README.md
Public README for vlogger image. Followed the format for other READMEs in this repo, linked to appropriate places in vertica.com docs.
The Creating a Custom Resource page will not be updated to reflect the vlogger image name:tag until 11.0SP2, but the current documentation is general enough to be clear while avoiding confusion.
https://www.vertica.com/docs/11.0.x/HTML/Content/Authoring/Containers/Kubernetes/Operator/CreatingCustomResource.htm
=> vlogger public README

scripts/setup-kustomize.sh, tests/kustomize-defaults.cfg
When running kuttl without setting VERTICA_IMG, it was using
vertica/vertica-k8s:latest as the image.  There was also some config
setting to set the default image to use if one isn't set.  We will now
use the image that `make echo-images` reports if the env. variable isn't
set.
=> Fixes for kuttl when VERTICA_IMG env not set

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_types_test.go, pkg/controllers/builder.go, pkg/controllers/imagechange.go, pkg/controllers/imagechange_test.go, pkg/controllers/labels_annotations.go, pkg/controllers/obj_reconcile.go, pkg/controllers/offlineimagechange_reconcile.go, pkg/controllers/offlineimagechange_reconcile_test.go, pkg/controllers/onlineimagechange_reconcile_test.go, pkg/controllers/onlineimagechange_reconciler.go, pkg/controllers/podfacts.go, pkg/controllers/restart_reconcile.go, pkg/controllers/restart_reconciler_test.go, pkg/controllers/subcluster_handle.go, pkg/controllers/suite_test.go, pkg/controllers/verticadb_controller.go, pkg/names/names.go, tests/e2e/upgrade-vertica-ks-0/75-assert.yaml
This is another PR for online-upgrade.  It will handle creation and removal of the standby subcluster during the online-image change process.
- new state was added to the vapi.Subcluster for this.  Originally, I was planning to keep most of this in the SubclusterHandle struct, but we already pass around vapi.Subcluster so it made it easier to have it their
- new status conditions for offline and online image change.  These are intended to be used by the operator to know what image change to continue with once an image change has started
- filled out more of the logic in onlineimagechange_reconciler.go.  It will scale-out a new standby subcluster for each primary, then scale them down when we are finishing the image change.
- moved more logic into imagechange.go that is common between …
=> Online image change: handling of the standby subcluster

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_types_test.go, pkg/controllers/builder.go, pkg/controllers/labels_annotations.go, pkg/controllers/obj_reconcile.go, pkg/controllers/obj_reconcile_test.go, pkg/controllers/onlineimagechange_reconciler.go, pkg/controllers/sc_finder.go, pkg/controllers/sc_finder_test.go, pkg/controllers/subcluster_handle.go, pkg/names/names.go, scripts/kind.sh, tests/e2e/labels-annotations/02-assert.yaml
This adds manipulating of the service objects during an online image change.  It will route client traffic to the standby when we are upgrading, then reroute the traffic back to the original subclusters when completing the upgrade.
As a side affect this also adds the ability for multiple subclusters to share the same service object.  This has benefits outside of the online image change process.
=> Online image change: manage client traffic over multiple subclusters

api/v1beta1/verticadb_types.go, pkg/controllers/builder.go, pkg/controllers/imagechange.go, pkg/controllers/imagechange_test.go, pkg/controllers/labels_annotations.go, pkg/controllers/obj_reconcile_test.go, pkg/controllers/offlineimagechange_reconcile.go, pkg/controllers/onlineimagechange_reconcile_test.go, pkg/controllers/onlineimagechange_reconciler.go, pkg/controllers/podfacts.go
This is the next set of changes for online image change.  It will route to a temporary subcluster, called a transient, so that client connections connect to an up node.  It will automatically route back to the original subcluster once the subcluster is back up.  It will also process secondary subclusters that they are brought back up.
This includes some rework in the onlineimagechange_reconciler to cut down on the amount of code duplication.
Added the ability to specify a template for the transient cluster.  This will get created when the image change starts and will get cleanup up when the image change is done.
=> Online image change: route to temporary subcluster to keep online

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_types_test.go, pkg/controllers/builder.go, pkg/controllers/imagechange_test.go, pkg/controllers/labels_annotations.go, pkg/controllers/obj_reconcile.go, pkg/controllers/obj_reconcile_test.go, pkg/controllers/onlineimagechange_reconcile_test.go, pkg/controllers/onlineimagechange_reconciler.go, pkg/controllers/suite_test.go
This is the next set of changes for online image change.  The CR parm TransientSubclusterTemplate was renamed to TemporarySubclusterRouting.  The parm can be used to provide a template of a subcluster to use for temporary routing while subclusters are down.  Or the parm can also be used to specify an existing subcluster.  This later option may be useful to those that want to just reuse existing subclusters.
This PR also cleans up how we route traffic to the subclusters.  We previously had relied on a 'transient' label.  But now we route to service name or subcluster name.
=> Online image change: allow reuse of existing sc for temporary routing

changes/unreleased/Added-20220112-124418.yaml
Following up issue [81](https://github.com/vertica/vertica-kubernetes/issues/81), OpenShift support has been spread over many many PR. This PR concludes that by adding a changie entry for OpenShift.
=> Add Changie entry for OpenShift

api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go, pkg/controllers/onlineimagechange_reconciler.go
This adds rules to the webhook for online image change:
- prevent changes to upgradePolicy when imageChange is in progress
- transient subcluster template: isPrimary == false, name cannot be an existing subcluster, size > 0 if name present
- transient subcluster cannot be added/removed during an online image change
- if multiple subclusters share a ServiceName, service specific things must be common between them (serviceType, NodePort, externalIPs, etc).
=> Online image change: new webhook rules

pkg/controllers/dbaddnode_reconcile.go, pkg/controllers/dbaddnode_reconcile_test.go, pkg/controllers/dbaddsubcluster_reconcile.go, pkg/controllers/dbremovenode_reconcile.go, pkg/controllers/dbremovesubcluster_reconcile.go, pkg/controllers/init_db.go, pkg/controllers/podfacts.go, pkg/controllers/podfacts_test.go, pkg/controllers/restart_reconcile.go, pkg/controllers/restart_reconciler_test.go, pkg/version/version.go
- when running AT start_db, we need to run from one of the primary nodes.  It won't work if we try from a read-only node that isn't being restarted.
- when calling re_ip, use the --force option.  This option is new in 11.1.0, so we needed conditional logic to know when we could use this.
- when calling start_db, we use the host list.  This option exists first in 11.0.1, so like reip, we needed conditional logic to know when we can use that option
One thing that isn't related to the title of this PR is some new logic needed in DBAddNodeReconicler.  That reconciler will now requeue if some pods aren't yet ready.  This was needed so that the upgrade properly waits for the transient subcluster to scale out.  Prior to this change, it was possible that the image change went ahead and restarted …
=> Online image change: changes for new admintools options in 11.1.0

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_types_test.go, api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go, pkg/controllers/builder.go, pkg/controllers/onlineimagechange_reconcile_test.go, pkg/controllers/onlineimagechange_reconciler.go, pkg/controllers/restart_reconciler_test.go, tests/e2e-11.1/online-upgrade-no-transient-1-sc/setup-vdb/base/setup-vdb.yaml
This changes the default behaviour for temporarySubclusterRouting.  It now defaults to picking existing subclusters rather than creating a transient subcluster.
=> Online image change: temporarySubclusterRouting to default to existing subclusters

Makefile, pkg/controllers/offlineupgrade_reconcile.go, pkg/controllers/onlineupgrade_reconcile_test.go, pkg/controllers/podfacts.go, pkg/controllers/podfacts_test.go, pkg/controllers/upgrade.go, pkg/controllers/upgrade_test.go, pkg/events/event.go, scripts/patch-image-in-vdb.sh, scripts/setup-kustomize.sh, tests/e2e-extra/vdb-gen/45-run-vdbgen.yaml, tests/kustomize-defaults.cfg
An online upgrade can only be used if upgrading from Vertica version 11.1+.  I'm reverting back to offline upgrade if we aren't on the correct version.
=> Fallback to offline upgrade if server incompatible

api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go
The webhook makes sure that two subclusters that share the same service
name have similar service specific settings (serviceType, nodePort,
etc.).  It didn't account for subclusters that don't fill in the
serviceName.  A blank service name will just use the subcluster name.
So two subclusters that have a blank service name will have different
service objects.  Using the GetServiceName() fixes this bug.
=> Webhook to account for empty serviceName in checks

changes/unreleased/Fixed-20220224-164528.yaml, pkg/controllers/init_db.go, pkg/controllers/init_db_test.go
Any endpoints ending with "/" will not affect DB creation. Not sure if we need a changie entry for this.
=> Fix bug to support Endpoints with trailing slashes

pkg/controllers/onlineupgrade_reconciler.go
We weren't skipping waitForReadyTransientPod if we are driving online
upgrade without a transient.  It isn't a major problem as we would error
out looking for the transient pod. But it does add some noise to the
operator log.
=> Skip step in online upgrade if not using transient

.gitignore, DEVELOPER.md, changes/unreleased/Changed-20220308-080716.yaml, pkg/controllers/dbaddnode_reconcile.go, pkg/controllers/dbaddnode_reconcile_test.go, pkg/controllers/podfacts.go, pkg/controllers/podfacts_test.go, pkg/controllers/rebalanceshards_reconcile.go, pkg/controllers/rebalanceshards_reconciler_test.go, pkg/controllers/verticadb_controller.go, pkg/events/event.go, tests/e2e/k-safety-0-scaling/35-assert.yaml, tests/e2e/k-safety-0-scaling/35-scale-up-to-3.yaml, tests/e2e/k-safety-0-scaling/40-assert.yaml, tests/e2e/k-safety-0-scaling/40-check-rebalance-shards.yaml, tests/external-images-build.txt
Prior to this PR we did 'admintools -t db_add_node' one at a time.  So if you were adding 3 nodes to a subcluster we would call admintools 3 times.  We now batch that into a single call.  This greatly speeds up the time to do scale up.  I have seen it take about 52 seconds to add 3 nodes, where previously we did 3 calls to admintools that took about 40 seconds each.
Shard rebalance is always done after add node.  I moved this to a separate reconciler now.  This allows for better error handling and better separation of concerns.
=> Batch 'admintools -t db_add_node' for faster scale up

Makefile, scripts/wait-for-webhook.sh
When we upgrade the operator-sdk to 1.17.0, we thought we were getting a
fix for the webhook ready probe.  So we removed the scripted wait and
instead relied on the --wait option through helm.  However, we still saw
cases where the helm command returns after the wait but the webhook
still wasn't 100% ready.  We are adding back the scripted wait to
stabilize things until we can investigate this more.
=> Add back the scripted wait for the webhook

Makefile
We use to run the helm unittest as part of CI but it was removed accidentally.  I'm adding it back to the `test` target again.
=> Run the helm unittest in the CI

api/v1beta1/verticadb_types.go, pkg/controllers/offlineupgrade_reconcile.go, pkg/controllers/offlineupgrade_reconcile_test.go, pkg/controllers/onlineupgrade_reconcile_test.go, pkg/controllers/onlineupgrade_reconciler.go, pkg/test/helpers.go
Instead of defining the UpgraderequeueTime for each test, use a helper function GetURTime()
=> Use a helper function to set UpgradeRequeueTime in the test

pkg/controllers/at_test.go, pkg/controllers/createdb_reconcile_test.go, pkg/controllers/dbaddnode_reconcile_test.go, pkg/controllers/dbaddsubcluster_reconcile_test.go, pkg/controllers/dbremovenode_reconcile_test.go, pkg/controllers/dbremovesubcluster_reconcile_test.go, pkg/controllers/init_db_test.go, pkg/controllers/install_reconcile_test.go, pkg/controllers/k8s_test.go, pkg/controllers/obj_reconcile_test.go, pkg/controllers/offlineupgrade_reconcile_test.go, pkg/controllers/onlineupgrade_reconcile_test.go, pkg/controllers/rebalanceshards_reconciler_test.go, pkg/controllers/restart_reconciler_test.go, pkg/controllers/revivedb_reconcile_test.go, pkg/controllers/status_reconcile_test.go, pkg/controllers/suite_test.go, pkg/controllers/uninstall_reconcile_test.go, pkg/controllers/upgrade_test.go, pkg/controllers/upgradeoperator120_reconciler_test.go, pkg/controllers/version_reconciler_test.go, pkg/test/helpers.go
This is a minor test refactor.  A few things I want to do based on some preliminary autoscaler work:
- in the test suite for the controller, rename `vrec` to `vdbRec`.  There is going to be another reconciler struct for the autoscaler, so calling it vrec isn't good enough to distinguish from the new one coming.
- moved test helpers createVdb and deleteVdb to the test package.  Now called CreateVDB and DeleteVDB.
=> Minor test refactor

changes/unreleased/Fixed-20220315-110324.yaml, pkg/version/version.go, pkg/version/version_test.go
The upgrade path detection that was added in v1.3.0 of the operator was too strict when it came to checking for service packs.  As per the Vertica docs, those can be skipped when doing upgrades.  This PR fixes that bug.
=> Skip service packs in upgrade path detection

changes/unreleased/Fixed-20220316-092618.yaml, pkg/controllers/onlineupgrade_reconciler.go, pkg/controllers/podfacts.go, pkg/controllers/podfacts_test.go, pkg/controllers/restart_reconcile.go, pkg/controllers/upgrade.go
This fixes a bug that caused a second cluster restart to occur after a successful offline upgrade.  The cached pod facts weren't getting invalidated.  So after the upgrade, it will proceed to the restart reconciler and using the stale facts think that a cluster restart is needed.  Adding an invalidate to the restart reconciler fixed this problem.
Also fixing a minor issue with online upgrade.  We could try to restart the primaries with 'AT -t restart_node'.  This will fail because the cluster is read-only.  Added a wait mechanism so that we only proceed with the primary restart once the server moves the secondaries into read-only mode.  This last issue was minor, so I didn't bother adding a changie entry for it.
=> Prevent cluster restart after offline upgrade

docker-vertica/docker-entrypoint.sh
I'm pretty sure they were coming from these copy commands.  It's OK that
these logs don't exist, so I piped stderr to /dev/null.
And, "mv" can be more efficient than "cp;rm".
And, mkdir -p could create /opt/vertica/config, so move it before the mv
And, chmod 755 is wrong for non-executables.  Instead add 644 to perms
=> docker log <container> was showing errors

docker-vertica/packages/cleanup.sh, docker-vertica/packages/package-checksum-patcher.py
This is the 1st of 2 PR to decrease the size of the vertica-k8s image.
It adds more files to clean up, removes the backup files and some libraries.
=> Clean up unnecessary files

changes/unreleased/Added-20220321-142806.yaml, config/default/manager_auth_proxy_patch.yaml, helm-charts/verticadb-operator/README.md, helm-charts/verticadb-operator/tests/image-name-and-tag_test.yaml, helm-charts/verticadb-operator/values.yaml, scripts/create-helm-charts.sh
Add config option for kube-rbac-proxy image instead of a hard
coded name, so that the controller-manager can be depoloyed
from a 3rd party registry (e.g. air gapped cluster, caching proxy).
Add image.repo config options to allow specifying a different
repository without changing name or version, for convenience.
Add imagePullSecrets so that images can be pulled from private repos.
=> controller-manager: Configurable image repos + imagePullSecrets

.github/workflows/e2e-azb.yml, .github/workflows/e2e-hdfs.yml, .github/workflows/e2e-online-upgrade.yml, .github/workflows/e2e-operator-upgrade.yml, .github/workflows/e2e-s3.yml, pkg/controllers/upgrade.go, pkg/controllers/upgrade_test.go
I have noticed that on occasion the upgradeStatus message gets *stuck*
at a stage in the online upgrade.  The upgrade has gone past a stage,
but it will end up reporting the wrong upgradeStatus message.  One
test (online-upgrade-with-transient) is sensitive to this as it checks
the status message in its assertions.  I suspect this occurs because we
are using a stale copy of the VerticaDB when we update the message.  I
am fixing this by making that update more robust.
=> Fix wrong upgradeStatus message

tests/e2e-online-upgrade/online-upgrade-drain/20-assert.yaml
The e2e testcase online-upgrade-drain can fail intermittently.  This
commit will fix that issue.  The issue it was hitting was that it would
try to connect to vertica through a service object for subcluster pri2.
Due to timing this subcluster might not be totally ready to accept
connections.  Adding a strict assertion that will only continue once
pods in that service object are ready.
=> Fix timing in online-upgrade-drain

changes/unreleased/Changed-20220325-102922.yaml, cmd/operator/main.go
When configuring the webhook, this will set the minimum TLS version to 1.3.  This is a bit of a hacky way to do this, but it will suffice until the controller-runtime allows this setting to be configure through the Manager.  See #155 for more of a discussion on what changes we are waiting for in controller-runtime.
Fixes #155
=> Set minimum TLS version of webhook to 1.3

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go, changes/unreleased/Added-20220328-085611.yaml, pkg/builder/builder.go, pkg/builder/labels_annotations.go, pkg/controllers/obj_reconcile.go, pkg/controllers/obj_reconcile_test.go
Additional subcluster options to better customize network load
balancers, i.e. when subcluster.serviceType is "LoadBalancer".
loadBalancerIP: Specifies front-end IP address of services. This is
useful in baremetal K8s (e.g. using MetalLB) to assign static IPs [1].
serviceAnnotations: Additional annotations for implementation-specific
customization of services. Managed K8s (e.g. Amazon EKS) heavily
use annotations to configure NLBs [2]. This is useful for choosing a
VPC/subnet, enabling logging, and other configurations.
[1] https://metallb.universe.tf/usage/#requesting-specific-ips
[2] https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/annotations/
Example configuration:
```
metadata:
name: example
namespace: …
```
=> subcluster: Add loadBalancerIP and serviceAnnotations

docker-operator/README.md
Links on the operator README still used the 11.x version number in the URL. I updated this to the latest.
=> updated docset version link to latest

pkg/controllers/vdb/podfacts.go
This fixes a regression that was introduced when changing pending pod handling in this release.  When running with k-safety 0, we need to restart all nodes together.  This closes a timing hole where it failed to wait for all of them.  This caused one of the e2e test to fail sporadically.
=> Fix pod restart with k-safety 0

api/v1beta1/verticaautoscaler_types.go, api/v1beta1/verticaautoscaler_webhook.go, api/v1beta1/verticaautoscaler_webhook_test.go, tests/e2e/vas-webhook/10-assert.yaml, tests/e2e/vas-webhook/10-create-vas-with-default-serviceName.yaml
This adds rules to VerticaAutoscaler to make serviceName and
verticaDBName as required.
Also, this relaxes some rules in the webhook wrt serviceName in the
template.  I removed the defaulter that had previously set the service
name in the template to match the one in the spec.  The webhook only
enforces that the service name match between spec and template if the
template is being used.
=> Enforce required fields in VerticaAutoscaler

Makefile, api/v1beta1/verticaautoscaler_types.go, config/manifests/bases/verticadb-operator.clusterserviceversion.yaml, config/samples/v1beta1_verticadb.yaml
- change maturity of the operator now that we support the autoscaler
- some changes to the samples.  The main change is to use the
'includeUIDInPath' parm so that we don't hit errors about trying to
create a database and a database already exists
- better description for the VerticaAutoscaler
=> Some updates to the CSV for 1.5.0

docker-vertica/Dockerfile
Scrutinize collects lang info, and when we used en_US.utf8 it would look
like the language was different across pods.  Using en_US.UTF-8 so that
the lang collected is the same.
=> Use en_US.UTF-8 as lang instead of en_US.utf8

changes/unreleased/Changed-20220603-111623.yaml, docker-vertica/Dockerfile
This is a new requirement for the upcoming 12.0 release of the vertica server.
=> Add zlib dev package to vertica-k8s image

changes/unreleased/Changed-20220603-125741.yaml, pkg/cmds/exec.go
When you exec into a pod, the ulimits you use are for the container runtime.  This can differ from the actual limits for the pod/container. This change ensures we use the pod/container limits when running any admintools commands.  This ensures the limits are the same for all pods.
=> Use pod limits when running admintools

.github/workflows/build-release-assets.yml, helm-charts/verticadb-operator/tests/image-name-and-tag_test.yaml, helm-charts/verticadb-operator/values.yaml
This corrects a problem when creating the new catalog entry in operatorhub.io.  It uses podman to pull the image to verify.  And podman doesn't assume you are pulling from dockerhub by default.   This change will make the repo explicit.  I had to update the CSV manually for the 1.5.0 release.  This changes the workflow to prefix with docker.io so the manual change isn't needed for the next release.
We only needed to update the bundle generation, but changing the default in the helm chart too to be consistent.
=> Prefix operator image with docker.io

DEVELOPER.md, Makefile, changes/unreleased/Changed-20220616-102645.yaml, pkg/controllers/vdb/metrics_reconcile.go, pkg/controllers/vdb/verticadb_controller.go, pkg/metrics/metrics.go, tests/e2e-extra/operator-metrics/30-verify-metrics-endpoint.yaml
This has various changes to the Prometheus metrics to make them more consumable and sync with future metric support in the server
- The prefix for all metrics was renamed from verticadb_* to vertica_*.   Verticadb is a k8s term, and we wanted to generalize it for when we expose the same metrics in non-k8s deployments.
- Rename *verticadb_subcluster_\*_count* gauges.  The subcluster name is a label, so we didn't need to repeat it in the metric name.  When you aggregate this metric to remove the subcluster label to get a cluster-wide view, having subcluster in the metric name didn't make much sense.
- Include namespace label in all of the metrics.  This allows you to distinguish metrics from other instances of the VerticaDB CR if you   have more than one.
=> Rename Prometheus metrics

api/v1beta1/verticadb_types.go, changes/unreleased/Added-20220624-112904.yaml, pkg/controllers/vdb/version_reconciler.go, pkg/version/version.go
There is an issue in the v12.0.0 server that prevents it from staring in k8s if running with cgroups v2.  This will log a warning event if we detect this environment.  We will still continue to try and start vertica, just in case we are running with a hotfix that addresses the issue.
I'm changing the default server image to 11.1.1 to make it less likely that we would hit this issue.
=> Log warning if v12.0.0 server and cgroups v2

README.md
Removed Installing the CRD command because it is redundant. Installing the Helm Chart or with OperatorHub.io installs the CRD.
=> rm Installing CRD section per dev and QA convo

Makefile, api/v1beta1/verticadb_types.go, changes/unreleased/Fixed-20220719-145459.yaml, changes/unreleased/Fixed-20220719-145535.yaml, changes/unreleased/Fixed-20220719-160434.yaml, helm-charts/verticadb-operator/Chart.yaml, helm-charts/verticadb-operator/values.yaml, pkg/builder/builder.go, pkg/builder/labels_annotations.go, pkg/controllers/vdb/annotateandlabelpod_reconcile.go, pkg/controllers/vdb/obj_reconcile.go, pkg/controllers/vdb/obj_reconcile_test.go, pkg/controllers/vdb/offlineupgrade_reconcile.go, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/podannotatelabel_reconcile.go, pkg/controllers/vdb/podannotatelabel_reconcile_test.go, pkg/controllers/vdb/verticadb_controller.go, tests/e2e-operator-upgrade-template/from-1.6.0/15-assert.yaml, tests/e2e-operator-upgrade-template/from-1.6.0/15-install-chart.yaml, tests/e2e-operator-upgrade-template/from-1.6.0/31-add-autoscaler.yaml, tests/e2e-operator-upgrade-template/from-1.6.0/31-assert.yaml, tests/e2e-operator-upgrade-template/from-1.6.0/41-errors.yaml, tests/e2e-operator-upgrade-template/from-1.6.0/41-wait-for-label-update.yaml, tests/e2e-operator-upgrade-template/from-1.6.0/46-assert.yaml, tests/e2e-operator-upgrade-template/from-1.6.0/46-change-autoscaler.yaml, tests/e2e-operator-upgrade-template/template/99-delete-ns.yaml
A bunch of changes and fixes related to upgrade of the operator:
- This increases the operator to 1.7.0.
- Added a new testcase to verify the upgrading of the operator from 1.6.0.
- Fixed an issue where the operator wouldn't update the operator version in k8s objects (app.kubernetes.io/version).  It stays on the version that originally created it. 
- Fixes an issue that every time we updated the operator version, it would force all of the pods to be rescheduled.  This happened because we changed a label for the pod in the sts template portion.  I now add a label for the version through a reconciler rather than through the statefulset template.  Unfortunately, we can't do anything for the next release (1.7.0) -- since we have to update the sts template to remove the label.  But the next …
=> Better support for upgrade of the operator

scripts/run-k8s-int-tests.sh, tests/e2e-extra/createdb-failures/90-delete-clean-communal-pod.yaml, tests/e2e-extra/createdb-failures/90-errors.yaml, tests/e2e-extra/revivedb-multi-sc/90-delete-clean-communal-pod.yaml, tests/e2e-extra/revivedb-multi-sc/90-errors.yaml, tests/e2e/multi-sc-sanity/90-delete-clean-communal-pod.yaml, tests/e2e/multi-sc-sanity/90-errors.yaml
Some testcases run a pod to cleanup communal at the start. When they go to cleanup the communal storage at the end nothing happens because the pod already exists. We need to delete the clean-communal pod before doing the cleanup the second time.
We are still seeing the occasional HDFS test fail due to diskfull in GitHub CI, so I'm hoping this helps.
=> Missed cleanup of communal on a couple of testcases

docker-vertica/Dockerfile
This is a small fix to allow the vertica-k8s container to be built on a machine running in the AWS environment.  We run the install to setup the directory structure for the container.  It is detecting we are running in AWS so is checking other things and failing.  The `--ignore-install-config` option should bypass the AWS check entirely.
=> install_vertica fix when running on VM in AWS

tests/e2e/update-strategy/50-assert.yaml
This fixes a small timing window in update-strategy where it was possible to advance too fast past a test step.  We delete a pod in one step (50), then suppose to wait for it to come back up in the next step (55).  But we didn't properly wait for the pod to be deleted in step 50.  So, it was possibly to quickly advance through step 55 before the pod really came back.
=> Fix timing in update-strategy e2e test

changes/unreleased/Changed-20220812-082810.yaml, docker-vertica/Dockerfile
Increase the Vertica server base image to the latest Ubuntu (focal-20220801) to resolve some security vulnerabilities.
=> Update vertica server image to ubuntu focal-20220801

api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go, changes/unreleased/Fixed-20220812-164753.yaml
There are certain paths that if chosen for data or depot will mess up the deployment.  These are paths that exist in the image and cannot be chosen as a PV mount point.  Adding a webhook rule to prevent their use.
=> Add webhook rule to prevent restricted paths

.github/workflows/build-images.yml, .github/workflows/e2e.yml, scripts/setup-hadoop.sh
Two things in this commit:
- We now include the image digest in the build summary.  This will make it easier to cross reference an image we use with one that is published in docker hub
- We always build the release artifacts for each PR and push to main. The release artifacts can be used by QA to test the exact change that was built in a particular commit.
=> Some e2e workflow improvements

changes/unreleased/Added-20220928-165145.yaml, config/manager/manager.yaml
Closes #253
An immutable root filesystem prevents applications from writing to their local disk. This is desirable in the event of an intrusion as the attacker will not be able to tamper with the filesystem or write foreign executables to disk.
=> Introduce readOnlyRootFilesystem in manager

changes/unreleased/Fixed-20220929-165740.yaml, pkg/cmds/exec.go, pkg/cmds/exec_test.go
This obfuscates the communal credentials when logging commands that the operator runs.
=> Hide communal credentials from the operator log

.github/workflows/build-images.yml, Makefile, changes/unreleased/Fixed-20220929-144054.yaml, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go, pkg/controllers/vdb/restart_reconcile.go, pkg/controllers/vdb/restart_reconciler_test.go, pkg/events/event.go, tests/external-images-common-ci.txt
When the operator needs to restart a node, it would kill any running Vertica process before it attemps to restart.  This was done initially in case a vertica process that was up, stops resonding.  However, this behaviour has been problematic if the Vertica startup is just too slow.
This commit will change the behaviour so that it won't uncondionally kill the Vertica process.  If the startup.log shows that Vertica is in the process of starting up, then the process is left as is and we requeue the iteration.
=> Don't interrupt a slow Vertica startup

pkg/cmds/exec.go, pkg/cmds/exec_test.go
This adds a few more secrets that we should not include as plain-text in the operator log.
This is a follow-up from a few things that were missed in #259.
=> Hide more communal secrets from operator log

changes/unreleased/Fixed-20221011-234913.yaml, pkg/vdbgen/vdb.go, pkg/vdbgen/vdb_test.go, tests/e2e-extra/vdb-gen/65-assert.yaml, tests/e2e-extra/vdb-gen/65-scale-sc1.yaml, tests/e2e-extra/vdb-gen/66-wait-for-steady-state.yaml, tests/e2e-extra/vdb-gen/70-assert.yaml, tests/e2e-extra/vdb-gen/70-run-vdbgen.yaml, tests/e2e-extra/vdb-gen/75-assert.yaml, tests/e2e-extra/vdb-gen/75-wait-for-revive.yaml, tests/e2e-extra/vdb-gen/run-vdb-gen.sh
This fixes some vdbgen issues by:
- fetching the ksafety from the server
- fetching the depot and data sizes from the server, and using them to calculate the local requestSize.
- fetching the server version and using it to build the image name.
=> Fix vdbgen

.github/actions/setup-e2e/action.yaml, .github/actions/setup-go-kctx/action.yaml, .github/workflows/build-images.yml, .github/workflows/build-release-assets.yml, .github/workflows/e2e-azb.yml, .github/workflows/e2e-hdfs.yml, .github/workflows/e2e-operator-upgrade.yml, .github/workflows/e2e-s3.yml, .github/workflows/e2e-server-upgrade.yml, .github/workflows/e2e-udx.yml, .github/workflows/scorecardtests.yml, .github/workflows/unittests.yml, .github/workflows/verify-public-artifacts.yml
Node.js 12 actions are deprecated in GitHub actions. If you use an action with this version, you get a warning. This upgrades any action that was rely on node 12 to one that supports node 16.
=> Upgrade github actions that used node 12

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go, changes/unreleased/Added-20221013-111702.yaml, pkg/controllers/vdb/init_db.go
This relaxes things in the operator so that the communal credential secret isn't required. Prior to this, the credential secret was required if connecting to a s3://, azb://, or gs:// endpoint.
This will allow us to authenticate with IAM when connecting on AWS. AWS provides two methods of authenticating with IAM:
- EC2 IAM authentication: an IAM role is attached to the EC2 instance. All pods running on the EC2 instance will be able to use the attached roles.
- IAM roles for service accounts (#200): this is for more fine-grained access control. You can use this to attach IAM roles to a ServiceAccount. All pods running with the ServiceAccount will be able to use the roles. This feature requires a Vertica service of at least 12.0.3 (not yet available at the time of this PR). You will need to …
=> Allow IAM authentication to communal storage

changes/unreleased/Fixed-20221024-202149.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/controllers/vdb/paths.go, tests/e2e-extra/revivedb-3-node/vdb-to-create/base/setup-vdb.yaml, tests/e2e-extra/revivedb-3-node/vdb-to-revive/base/setup-vdb.yaml
This is a bug fix for when the local paths (data, depot, catalog) all share the same mount location. Previous to this change, the pods in a statefulset will fail to start if the paths are all the same. It fails to start because they all shared the same mount. This fixes it by adding a mount only if the local paths differ.
=> Allow local paths to share the same mount point

pkg/cmds/exec.go
This is a fix to ensure that all environment variables set in the container get flowed to the subshell that will eventually run the vertica process. This ensures any vars set for AWS will be present in the environment that will run the vertica process -- needed for #200.
=> Flow all env vars to subshell running vertica

pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go
Some follow-up from the podfacts change. I noticed that we do some checks in podfacts that rely on the database up that can be skipped if the vertica pid isn't running. This will save a few 'kubectl exec' calls during a reconcile iteration when vertica isn't running.
=> Skip some checks if vertica pid not running

pkg/controllers/vdb/install_reconcile.go, pkg/controllers/vdb/install_reconcile_test.go
This fixes a bug that was introduced earlier in this release (#283) when we did the podfacts refactor. We were failing to create the http conf dir in the installer reconciler if the http server is enabled. The plan is enable the http e2e tests, which would have caught this, when we use the 12.0.2 server release in the CI.
=> Installer to create http conf dir if enabled

.github/workflows/verify-public-artifacts.yml, scripts/setup-minio.sh
The GitHub workflow "Verify Public Artifacts" was hitting a problem with the latest version of the minio operator (see https://github.com/minio/operator/issues/1331). I'm going to harden the minio version by using the same method we use to setup minio for the e2e tests.
=> Fix the Verify Public Artifacts GitHub workflow

changes/unreleased/Fixed-20221124-103144.yaml, pkg/vdbgen/generator.go, pkg/vdbgen/vdb.go, pkg/vdbgen/vdb_test.go
There are a couple of cases where a Vertica database can be created without storing authentication parms for communal:
- using HDFS as the communal store
- using AWS S3, but using IAM profiles for authentication
vdb-gen wasn't handling this case well. For AWS S3, it was expecting to see the authentication parms. It failed when it couldn't find it. And it handles the HDFS case, but still prints out an empty credential secret when it dumps the manifests.
This fixes both scenarios in vdb-gen.
=> vdb-gen to handle db that have no communal auth

changes/unreleased/Fixed-20221124-142513.yaml, pkg/atconf/file_writer.go
There is an internal 5-minute timeout while bootstrapping the database during revive. If this timeout is exceeded the revive will fail. I'm extending this time to 20-minutes to allow slow revives to succeed.
=> Extend admintools timeout for a slow revive

changes/unreleased/Fixed-20221209-092713.yaml, pkg/opcfg/config.go
When the metrics are disabled (through helm chart parmeter `prometheus.expose=Disable`), we weren't closing off the metrics endpoint. It was still being started on port :8080. There is an option to the operator called `--metrics-bind-address`. We were omitting this when metrics were disabled, but we ended up picking the default for this option and starting the metrics serving anyway. This fixes it by changing the default value for that parameter to "0", which prevents the metrics server from starting.
=> Don't start metric endpoint if metrics are disabled

api/v1beta1/verticadb_types.go, changes/unreleased/Added-20221208-151541.yaml, pkg/controllers/vdb/metrics_reconcile.go, pkg/controllers/vdb/metrics_reconcile_test.go, pkg/controllers/vdb/version_reconciler.go, pkg/controllers/vdb/verticadb_controller.go, pkg/metrics/metrics.go, pkg/version/metadata.go, pkg/version/metadata_test.go, tests/e2e-extra/operator-metrics/30-verify-metrics-endpoint.yaml
Adding a new label to all of the Prometheus metrics that the operator collects. We include the revive instance ID. Here is a sample metric:
```
vertica_up_nodes_count{namespace="vertica",revive_instance_id="566b8f9590b771272b918c86a17a7b",subcluster="defaultsubcluster",verticadb="vert"} 3
```
The label `revive_instance_id` will allow us to match labels generated at the server. This will help allow us to pull metrics into the same dashboard for operator and server.
=> Include metrics label to uniquely identify the database

api/v1beta1/verticadb_types.go, changes/unreleased/Changed-20221213-150739.yaml, pkg/controllers/vdb/clientroutinglabel_reconcile.go, pkg/controllers/vdb/dbaddnode_reconcile.go, pkg/controllers/vdb/dbremovesubcluster_reconcile.go, pkg/controllers/vdb/metrics_reconcile.go, pkg/controllers/vdb/metrics_reconcile_test.go, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go, pkg/controllers/vdb/rebalanceshards_reconcile.go, pkg/controllers/vdb/revivedb_reconcile_test.go, pkg/controllers/vdb/status_reconcile.go, pkg/controllers/vdb/suite_test.go, pkg/metrics/metrics.go, tests/e2e-extra/operator-metrics/30-verify-metrics-endpoint.yaml
This changes a few prometheus metrics to include the subcluster oid instead of the name. The subcluster name can change where as the oid stays constant. So, it's better to build a dashboard around. This is to sync with what the server is doing, so we will be able to combine metrics from the operator and the server in a single dashboard.
In order to include the subcluster oid, we needed to collect it. The podfacts were updated and a new status field was added to store the oid. The status field is necessary so that we know the oid if vertica is down and we can't query anything.
=> Include subcluster_oid in metrics

.github/workflows/build-images.yml, .github/workflows/e2e.yml
This takes advantage of a new feature in GitHub workflows that allows you to set the name of the run. We'll be able to use this to distinguish the dispatched runs from the Vertica internal CI: is it a release we are testing, is it the daily server, developer branch, etc.
=> Allow workflow dispach to set the name of the e2e run

docker-vertica/Dockerfile
This adds vi (not vim) and less for basic editing inside the vertica server container. It adds only 2MB to the overall container size.
=> Include small tools in vertica container

api/v1beta1/verticadb_types.go, changes/unreleased/Added-20230103-152056.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go, tests/e2e-leg-3/readiness-probe-override/05-create-creds.yaml, tests/e2e-leg-3/readiness-probe-override/10-assert.yaml, tests/e2e-leg-3/readiness-probe-override/10-deploy-operator.yaml, tests/e2e-leg-3/readiness-probe-override/15-assert.yaml, tests/e2e-leg-3/readiness-probe-override/15-create-db.yaml, tests/e2e-leg-3/readiness-probe-override/20-assert.yaml, tests/e2e-leg-3/readiness-probe-override/20-wait-for-create-db.yaml, tests/e2e-leg-3/readiness-probe-override/25-assert.yaml, tests/e2e-leg-3/readiness-probe-override/25-verify-readiness-probe-override.yaml, tests/e2e-leg-3/readiness-probe-override/30-assert.yaml, tests/e2e-leg-3/readiness-probe-override/30-change-overrides.yaml, tests/e2e-leg-3/readiness-probe-override/35-wait-for-steady-state.yaml, tests/e2e-leg-3/readiness-probe-override/90-delete-clean-communal-pod.yaml, tests/e2e-leg-3/readiness-probe-override/90-errors.yaml, tests/e2e-leg-3/readiness-probe-override/95-delete-cr.yaml, tests/e2e-leg-3/readiness-probe-override/95-errors.yaml, tests/e2e-leg-3/readiness-probe-override/96-assert.yaml, tests/e2e-leg-3/readiness-probe-override/96-cleanup-storage.yaml, tests/e2e-leg-3/readiness-probe-override/97-errors.yaml, tests/e2e-leg-3/readiness-probe-override/97-uninstall-operator.yaml, tests/e2e-leg-3/readiness-probe-override/99-delete-ns.yaml, tests/e2e-leg-3/readiness-probe-override/README.txt, tests/e2e-leg-3/readiness-probe-override/setup-vdb/base/kustomization.yaml, tests/e2e-leg-3/readiness-probe-override/setup-vdb/base/setup-vdb.yaml
The VerticaDB currently has a hard coded timeout for the readiness probe of 1 second. It does a 'select 1' query to vertica to check that its up and ready to accept connections. If this does not respond in 1 second, and this happens 3 times in a row, then we assume the endpoint isn't up. Routing rules from the service object will no longer reach that pod until the readiness probe is successful again.
A new knob is added to the VerticaDB to allow the readiness probe to be altered. See the `readinessProbeOverride` parameter in the example below. The new parameter is the `corev1.Probe` type, so it can accept any values that are typically included with probes.
```
metadata:
name: v
spec:
...
readinessProbeOverride:
timeoutSeconds: 5 …
```
=> Allow the readinessProbe to be configured

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go, config/manifests/bases/verticadb-operator.clusterserviceversion.yaml, pkg/builder/builder.go, pkg/controllers/vdb/obj_reconcile.go, pkg/controllers/vdb/obj_reconcile_test.go
Some new fields in the VerticaDB were added this release for the Vertica http server. There is going to be two http servers in the future, so changing the names of the fields to accomadate for this future change. This rename is fine because we haven't yet released a version of the operator that had the old names. They are new in this release.
=> Rename some fields added in current release

.github/workflows/e2e.yml, .github/workflows/unittests.yml, Makefile
Occasionally, we see failures when trying to install the unittest plugin for helm. Helm pulls it from github, but occasionally it can fail with errors such as this:
```
helm plugin install https://github.com/quintush/helm-unittest
Support linux-amd64
Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/tags/v0.2.11
No download_url found only searching for linux
Downloading  to location /tmp/_dist/
curl: Remote file name has no length!
curl: (23) Failed writing received data to disk/application
```
Ideally, we would like to retry because this seems to be an intermittent problem. But the curl command is embedded in helm. So, instead I'm switching to use a container as that seems a bit more robust. As a side benefit, this also allows us to fix the version of the plugin we …
=> Use container for helm ut

.github/workflows/e2e-udx.yml, tests/e2e-udx/udx-cpp/30-upload-files.yaml
Occasionally, the apt-get will fail due to network issues causing the e2e-udx run to fail. This adds in a simple retry mechanism.
=> Fix intermittent network issues in e2e-udx

config/samples/minio.yaml, scripts/setup-minio.sh, tests/external-images-s3-ci.txt, tests/manifests/minio/02-tenant.yaml
This upgrades the minio version we use in e2e and in the samples. The tenant we create in the old sample didn't work with the latest minio version, so updating that so the samples work.
=> Use newer version of minio in e2e/sample

scripts/push-to-kind.sh
This is help resolve temporary failures in the e2e runs.
=> Retry docker pull to avoid temp network issues

.github/workflows/build-images.yml
Last nights e2e run hit a timeout issue with the trivy scanning. Doubling the timeout to make this less likely in the future.
=> Increase the trivy scan timeout

scripts/logging-utils.sh, scripts/push-vertica-server-image.sh, scripts/show-e2e-run-result.sh
This is the first step in automating this work. For now, we need to run these manually to verify the e2e run was successful and to pull/tag/push the images.
=> Scripts to manage the release of vertica server

pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go
I'm including the node name in the query that we use to get node state. I'm adding this to help in debugging some e2e failures I have seen.
=> Include node name in query when getting node state

changes/unreleased/Fixed-20230131-160542.yaml, pkg/controllers/vdb/createdb_reconcile.go, pkg/controllers/vdb/localdatacheck_reconcile.go, pkg/controllers/vdb/localdatacheck_reconcile_test.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/restart_reconcile.go, pkg/controllers/vdb/restart_reconciler_test.go, pkg/controllers/vdb/revivedb_reconcile.go, pkg/controllers/vdb/verticadb_controller.go, pkg/events/event.go, pkg/mgmterrors/aterrors.go, pkg/mgmterrors/aterrors_test.go, pkg/mgmterrors/interface.go, pkg/mgmterrors/suite_test.go
This change makes disk full errors more prominent in the operator. The focus is on checking the disk space for the local PV. We handle this with a couple of strategies:
- parsing the output from admintools. Sometimes, disk full errors will be seen in the output.
- add a reconcile actor that will check the disk space available in the local PV and log a k8s event if its below a threshold (currently 10mb)
I did the second approach because there are some times when vertica may have trouble starting and the error doesn't surface in the admintools output.
=> Make disk full errors more prominent

tests/e2e-http-server/http-custom-certs/50-assert.yaml, tests/e2e-http-server/http-custom-certs/50-verify-metrics.yaml
The overnight e2e test failed because it was testing an endpoint that was renamed. It was using /info/version, changed that to use /metrics.
=> Change e2e http test to try different endpoint

pkg/reviveplanner/analyze.go, pkg/reviveplanner/analyze_test.go, tests/e2e-leg-4/revivedb-multi-sc/vdb-to-create/base/setup-vdb.yaml, tests/e2e-leg-4/revivedb-multi-sc/vdb-to-revive/base/setup-vdb.yaml
This fixes a regression in the new revive handler work. It wasn't handling database names that had capital letters in them. When we run the revive with --display-only option, we would erronously think the paths are bad because we weren't checking for the correct case.
Updates an e2e test to use capital letters in its db name that would have caught this sooner.
This regression exists only in the current release. So, no changie entry exists.
=> Revive to handle DB names that have capitals

api/v1beta1/verticadb_types.go, changes/unreleased/Added-20230219-214900.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go
A new parameter is added to the VerticaDB CRD that will allow pod-level securityContext options be overridden. Any value put in spec.podSecurityContext will get merged in with the default pod securityContext.
=> Add option to override pod-level securityContext

pkg/reviveplanner/analyze.go, pkg/reviveplanner/analyze_test.go, pkg/reviveplanner/parser.go, tests/e2e-leg-3/revive-with-different-local-paths/22-create-storage-path.yaml
The pre-pass we do with revive now handles more scenarios with the data path:
- vertica hosts can have DATA,TEMP paths that don't end with the vnode name. The generated DATA,TEMP paths all end with the vnode (e.g. /data/db/v_db_node0001_data). But additional paths can be added that don't follow that format.
- vertica hosts can have multiple DATA,TEMP paths. Previously, it only assumed there was one.
Closes #335
=> Revive planner to handle data path without vnode in it

Makefile
because the sed on OSX treats the -i flag differently
=> use perl instead of sed

changes/unreleased/Fixed-20230304-072028.yaml, pkg/controllers/vdb/restart_reconcile.go, pkg/controllers/vdb/restart_reconciler_test.go, tests/e2e-leg-4/restart-with-sidecars/05-create-communal-creds.yaml, tests/e2e-leg-4/restart-with-sidecars/10-assert.yaml, tests/e2e-leg-4/restart-with-sidecars/10-deploy-operator.yaml, tests/e2e-leg-4/restart-with-sidecars/15-assert.yaml, tests/e2e-leg-4/restart-with-sidecars/15-create-cr.yaml, tests/e2e-leg-4/restart-with-sidecars/20-assert.yaml, tests/e2e-leg-4/restart-with-sidecars/20-wait-for-create-db.yaml, tests/e2e-leg-4/restart-with-sidecars/25-wait-for-steady-state.yaml, tests/e2e-leg-4/restart-with-sidecars/30-delete-vertica-pid.yaml, tests/e2e-leg-4/restart-with-sidecars/35-assert.yaml, tests/e2e-leg-4/restart-with-sidecars/35-verify-restart-in-metrics.yaml, tests/e2e-leg-4/restart-with-sidecars/45-wait-for-steady-state.yaml, tests/e2e-leg-4/restart-with-sidecars/95-delete-cr.yaml, tests/e2e-leg-4/restart-with-sidecars/95-errors.yaml, tests/e2e-leg-4/restart-with-sidecars/96-assert.yaml, tests/e2e-leg-4/restart-with-sidecars/96-cleanup-storage.yaml, tests/e2e-leg-4/restart-with-sidecars/97-errors.yaml, tests/e2e-leg-4/restart-with-sidecars/97-uninstall-operator.yaml, tests/e2e-leg-4/restart-with-sidecars/99-delete-ns.yaml, tests/e2e-leg-4/restart-with-sidecars/setup-vdb/base/kustomization.yaml, tests/e2e-leg-4/restart-with-sidecars/setup-vdb/base/setup-vdb.yaml
This fixes a regression that was introduced in 1.10.0 of the operator. If you ran your VertiacDB with sidecars, it is possible that the operator fails to restart vertica. It will be stuck in a loop waiting for the startupProbe to expire.
The operator was checking the pod's status.containerStatuses list to see if the startupProbe is active. It assumed (wrongly) that it only ever needed to look at the first entry in that list. So, it kept looking at the wrong entry and can make the wrong inference about whether the startupProbe is still active.
A new e2e test was added to mimic the error and verify the fix.
=> Fix bug preventing restart when pods have sidecars

api/v1beta1/verticadb_types.go, pkg/controllers/vdb/httpservercertgen_reconcile.go, pkg/controllers/vdb/obj_reconcile.go
The http cert is needed if running httpServerMode. When this is set to Auto, we use to rely on the vertica version to know if it supports the http server. That was causing some issues in our e2e tests. A lot of reconcile iterations were needed for created db. Eventually some of the tests were going into a few minute lag between reconcile iterations due to the exponential backoff.
This change is to create the cert ahead of any version check. This may mean we generate the cert and put it in the sts more often. But this http server will be required at some point in the future, so this shouldn't be too much of a problem.
=> Always gen http cert if httpServerMode is auto

docker-vertica/packages/cleanup.sh
There was a missing 's' to a folder name: /opt/vertica/config/https_cert -> /opt/vertica/config/https_certs
=> Add missing 's'

api/v1beta1/verticadb_types.go, changes/unreleased/Added-20230310-154628.yaml, docker-vertica/Dockerfile, docker-vertica/packages/cleanup.sh, pkg/builder/builder.go, pkg/controllers/vdb/agent_reconciler.go, pkg/controllers/vdb/agent_reconciler_test.go, pkg/controllers/vdb/obj_reconcile.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/suite_test.go, pkg/controllers/vdb/verticadb_controller.go, pkg/events/event.go, tests/e2e-leg-2/shared-svc/21-wait-for-agent.yaml, tests/e2e-leg-2/shared-svc/setup-vdb/base/setup-vdb.yaml
This adds the agent for VA. 
- A new reconciler has been added.
- We start the agent only when this specific annotation is set in the CR: `vertica.com/run-agent: "yes"`
- We have added the agent key back to some of the images (not the nosshkeys version).
- The port 5444 will be added to the extsvc and  every vertica container
- An e2e test has been modified to check that agent is running when enabled.
=> Add backdoor to run the agent

tests/e2e-http-server/http-generated-certs/60-verify-sync-catalog.yaml
The catalog sync HTTP endpoint was renamed in Vertica 23.3. This updates the test to check the old and new endpoint name so that it can continue to work against different server versions.
=> Fix e2e test for catalog sync HTTP endpoint

changes/unreleased/Fixed-20230324-084145.yaml, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go, pkg/controllers/vdb/verticadb_controller.go
This fixes an issue with subcluster creation. We weren't running the rebalance_shards() to add subscriptions to the new subcluster. To hit this you had to have a few specific things:
- had to use a v11 server
- the database has to be migrated from enterprise to eon
There was a server issue during migration, to be fixed separately, that set some wrong state for certain tables. Some tables were identified as being "shared", which to the server means we need active shard subscriptions to query them. If no subscriptions, then the query would fail with "ERROR 9099:  Cannot find participating nodes to run the query".
This was affecting queries the operator does to catalog tables -- key for this fix was it affected any query to the nodes table. Because of this, the operator deemed the new scaled …
=> UP node check needs to be made more resilient

api/v1beta1/verticadb_types.go, api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go, changes/unreleased/Fixed-20230403-102815.yaml, pkg/names/names.go, pkg/names/names_test.go, pkg/vdbgen/vdb.go, pkg/vdbgen/vdb_test.go, tests/e2e-leg-1/create-and-del-crd/15-assert.yaml, tests/e2e-leg-1/create-and-del-crd/20-custom-volume-mounts.yaml, tests/e2e-leg-1/create-and-del-crd/25-assert.yaml, tests/e2e-leg-1/create-and-del-crd/25-scale-out.yaml, tests/e2e-leg-1/create-and-del-crd/setup-vdb/base/setup-vdb.yaml
Before this, a subcluster's name couldn't contain the underscore character because it is part of sts and pod names and according to FQDN rules, an underscore is not a valid character. 
This adds better support by simply mapping '_' to a '-' before building pod/service/sts name. This will allow us to support the default subcluster name in vertica – default_subcluster. 
The webhook now allows subcluster name with '_'. However, two subclusters could have have identical sts names: e.g. default_subcluster and default-subcluster. We reject that case now in the webhook.
=> Support subcluster names with underscore

tests/e2e-leg-4/restart-with-liveness-probe/55-assert.yaml
The test restart-with-liveness-probe fails sometimes while attempting to restart a pod that we deleted the Vertica PID in. The pod is suppose to have the .status.containerStatuses.lastState.terminated filled in. All of parts of the test look good. It is almost as if if that status isn't always reliably set. So, I am removing that part of the check. The e2e still retains its original purpose.
=> Fix for e2e test failure

tests/e2e-udx/udx-cpp/70-verify-cpp-source.yaml
The udx samples were changed in the latest server to call out to python2. This isn't present in the container that we use, nor do I want to add it. Rather, I'm simplying doing a sed in the samples to call python instead of python2.
=> Fix udx-cpp due to python change in latest server

docker-vertica/Dockerfile
Keeping vim out of the -nokeys server image to cut down on the number security vulnerabiliites -- vim has quite a few medium/low ones. We are treating the -nokeys server image as more of an image suitable for environments with stricter security guidelines.
=> Remove vim from nokeys server image

docker-vertica/Dockerfile
This is actually a fix to an earlier change that removed vim from the server container. We weren't passing down the required NO_KEYS argument so the logic we added wasn't working.
=> Remove vim from the -nokeys server image

.github/workflows/e2e-server-upgrade.yml, pkg/version/version.go, pkg/version/version_test.go, tests/e2e-server-upgrade/offline-upgrade-ks-0/15-assert.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/20-assert.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/20-start-vertica-upgrade.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/35-assert.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/35-upgrade-and-scale-up.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/40-assert.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/40-upgrade-and-scale-down.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/50-upgrade-vertica.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/55-assert.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/70-upgrade-vertica.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/75-assert.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/setup-vdb/base/setup-vdb.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-1/25-assert.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-1/35-assert.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-1/35-upgrade-vertica.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-1/setup-vdb/base/setup-vdb.yaml, tests/e2e-udx/udx-cpp/35-verify-cpp-aggregate.yaml, tests/e2e-udx/udx-cpp/expected-outputs/23.3.0/AggregateFunctionsOut.txt, tests/e2e-udx/udx-python/40-verify-python-transform.yaml, tests/external-images-server-upgrade-ci.txt, tests/manifests/image-pull/upgrade-vertica-1/configmap.yaml
This is a fix for the e2e tests related to the nightly vertica server test. The latest server builds updated it's version to 23.3.0. This broke a few things:
- all of the upgrade tests were from 11.1.1. As per the upgrade path, you cannot go from 11.1.1 to 23.3.0 as you are skipping the 12.0.x release. The fix here is to change all of the upgrade tests to start from 12.0.2.
- some of the udx tests have different expected results based on the server version. The server version check wasn't quite right, so we were picking the wrong expected result for 23.3.0.
=> Fixes for server version change

docker-vertica/packages/cleanup.sh
Temporarily remove the node_management_agent from the vertica-k8s image. This is to address a security vulnerability. We will add the nma back when the server addresses the vulnerability.
=> Remove node_management_agent from vertica-k8s image

Makefile, changes/unreleased/Added-20230509-105206.yaml, pkg/builder/builder.go, tests/e2e-leg-3/istio/05-setup-istio.yaml, tests/e2e-leg-3/istio/10-assert.yaml, tests/e2e-leg-3/istio/10-deploy-operator.yaml, tests/e2e-leg-3/istio/15-enable-strict-mTLS.yaml, tests/e2e-leg-3/istio/20-assert.yaml, tests/e2e-leg-3/istio/20-create-cr-tproxy.yaml, tests/e2e-leg-3/istio/25-assert.yaml, tests/e2e-leg-3/istio/25-wait-for-create-db.yaml, tests/e2e-leg-3/istio/30-kill-sts.yaml, tests/e2e-leg-3/istio/35-assert.yaml, tests/e2e-leg-3/istio/35-wait-for-restart.yaml, tests/e2e-leg-3/istio/90-cleanup-istio.yaml, tests/e2e-leg-3/istio/90-errors.yaml, tests/e2e-leg-3/istio/95-delete-cr.yaml, tests/e2e-leg-3/istio/95-errors.yaml, tests/e2e-leg-3/istio/96-assert.yaml, tests/e2e-leg-3/istio/96-cleanup-storage.yaml, tests/e2e-leg-3/istio/97-errors.yaml, tests/e2e-leg-3/istio/97-uninstall-operator.yaml, tests/e2e-leg-3/istio/99-delete-ns.yaml, tests/e2e-leg-3/istio/setup-vdb-tproxy/base/kustomization.yaml, tests/e2e-leg-3/istio/setup-vdb-tproxy/base/setup-vdb.yaml
This adds new ports to the headless service. This was done for compatibility with istio. When istio is enabled with TPROXY redirection and strict mTLS, the ports are needed to ensure vertica pods can continue to communicate with each other. See this for more info: https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/#headless-services
The headless service previously only had the ssh port. That was renamed from ssh to tcp-ssh to follow the istio port naming guidelines (see https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)
=> Additional ports added to headless service

docker-vertica/packages/cleanup.sh
This removes vcluster due to security vulnerabilities. It is related to node management agent, which we don't currently run in k8s.
=> Remove vcluster binary from vertica-k8s image

docker-vertica/Dockerfile, docker-vertica/Makefile, docker-vertica/packages/cleanup.sh, tests/e2e-udx/udx-cpp/30-upload-files.yaml, tests/e2e-udx/udx-cpp/50-verify-cpp-filter.yaml
An image change for vertica-k8s that addresses some security vulnerabilities that we found internally:
- change the OS of the final stage of the image to Ubuntu 23.04 (Lunar Lobster). This newer version gets security updates quicker than the previous version we were using. Moving to this version addressed a few vulnerabilities that we had
- remove pip from the image. We had an earlier attempt at doing this, but there was remnents still around.
- change the builder os version, an early stage in the container, from centos:centos7.9.2009 to quay.io/centos/centos:stream8. The old image we were using was deprecated. If you try building the vertica container on a new mac, it would complain. Switching to a new centos.
=> Move vertica-k8s to Ubuntu 23.04 (Lunar Lobster)

api/v1beta1/labels.go, api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go, changes/unreleased/Fixed-20230511-141746.yaml, cmd/operator/main.go, pkg/builder/builder.go, pkg/builder/labels_annotations.go, pkg/controllers/vas/suite_test.go, pkg/controllers/vdb/annotateandlabelpod_reconciler.go, pkg/controllers/vdb/clientroutinglabel_reconciler.go, pkg/controllers/vdb/clientroutinglabel_reconciler_test.go, pkg/controllers/vdb/dbremovesubcluster_reconciler.go, pkg/controllers/vdb/httpservercertgen_reconciler.go, pkg/controllers/vdb/obj_reconciler_test.go, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/onlineupgrade_reconciler_test.go, pkg/controllers/vdb/podannotatelabel_reconciler_test.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/suite_test.go, pkg/controllers/vdb/upgrade.go, pkg/controllers/vdb/upgradeoperator120_reconciler.go, pkg/controllers/vdb/upgradeoperator120_reconciler_test.go, pkg/iter/sc_finder.go, pkg/meta/annotations.go, pkg/meta/labels.go, pkg/vasstatus/status.go, scripts/change-operator-version.sh, tests/e2e-server-upgrade/offline-upgrade-happy-path/15-assert.yaml, tests/e2e-server-upgrade/offline-upgrade-happy-path/setup-vdb/base/setup-vdb.yaml
We can now set the following label in the CR:
```
spec:
labels:
app.kubernetes.io/name: "org-name"
```
All k8s created object will have it. If it is not set in the CR, it will assume the default value which is `vertica`.
A webhook has also been added to prevent other internally used labels to be overridden.
Closes #384
=> Allow app.kubernetes.io/name to be set in the VerticaDB CR

tests/e2e-http-server/http-custom-certs/55-verify-nodes.yaml, tests/e2e-http-server/http-generated-certs/55-verify-listtable.yaml, tests/e2e-http-server/http-generated-certs/60-verify-sync-catalog.yaml
The http endpoints changed in the latest server build. Updating the http testcases to allow for the new endpoint names.
=> Fix http testcases on nightly build

api/v1beta1/verticadb_webhook.go, api/v1beta1/verticadb_webhook_test.go, changes/unreleased/Fixed-20230511-151513.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go, tests/e2e-leg-2/restart-sanity/01-assert.yaml, tests/e2e-leg-2/restart-sanity/01-rbac.yaml, tests/e2e-leg-2/restart-sanity/12-assert.yaml, tests/e2e-leg-2/restart-sanity/13-verify-passwd-mounted.yaml, tests/e2e-leg-2/restart-sanity/33-change-probes.yaml, tests/e2e-leg-2/restart-sanity/43-verify-passwd-not-mounted.yaml, tests/e2e-leg-2/restart-sanity/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-3/multi-sc-sanity/10-assert.yaml, tests/e2e-leg-3/multi-sc-sanity/13-verify-passwd-not-mounted.yaml, tests/e2e-leg-3/multi-sc-sanity/setup-vdb/base/setup-vdb.yaml
Currently, the dbadmin password is mounted in the container at /etc/podinfo/superuser-passwd. This is needed so that readiness/startup probes can log into vertica and run the 'select 1' canary query. This change is to satisfy a request to avoid mounting the password if the probes are change to not refer to the password.
There are two ways you can change the probes:
1. Check if the client port is open.
Instead of checking the canary query. Just check if the client port is opened. Include overrides for the readiness and startup probes in the vdb like this:
```
metadata:
name: v
spec:
...
readinessProbeOverride:
tcpSocket:
port: 5433
startupProbeOverride:
tcpSocket:
port: 5433
```
2. Setup local trust for the dbadmin
Keep using the canary query …
=> Avoid mounting dbadmin password if not needed

changes/unreleased/Changed-20230512-141516.yaml, go.mod, go.sum
Upgrading go-restful package from 3.9.0 to 3.10.0 to address PRISMA-2022-0227
=> Uplift go-restful package to address vulnerability

changes/unreleased/Fixed-20230512-095131.yaml, pkg/atconf/file_writer.go, pkg/atconf/file_writer_test.go
This corrects node name reuse when the operator installs new hosts in the admintools.conf. The old reuse logic was a bit too simple and could end up skip reusing a name under certain circumstances. 
Note, there are two kinds of node names in vertica. The node name before a node is added to the cluster -- in the format of node####. And the vnode name, which is the name after its added to the cluster -- in the format of v_<dbname>_node####. This impacts only the first format.
=> Reuse node names when installing new k8s pods

api/v1beta1/eventtrigger_types.go, config/manifests/bases/verticadb-operator.clusterserviceversion.yaml, pkg/controllers/et/verticadbref_reconciler.go, tests/e2e-leg-1/auto-restart-vertica/17-assert.yaml, tests/e2e-leg-3/non-cluster-admin-deployment/40-assert.yaml
In future, we may want the EventTrigger to create more than 1 job. This is an update to the CRD so that we don't have to make the CRD change in a patch fix operator release.
=> Include number of jobs created in EventTrigger status

tests/e2e-http-server/http-generated-certs/55-assert.yaml, tests/e2e-http-server/http-generated-certs/55-verify-health.yaml
The nightly build removed one of the REST endpoints that we were testing in the http-generated-certs e2e test. This updates that test to reflect that change.
=> Fix http e2e test in nightly build

changes/unreleased/Added-20230523-142408.yaml, pkg/controllers/et/eventtrigger_controller.go, pkg/controllers/et/eventtrigger_controller_test.go, pkg/controllers/vas/verticaautoscaler_controller.go, pkg/controllers/vdb/createdb_reconciler.go, pkg/controllers/vdb/verticadb_controller.go, pkg/meta/annotations.go, pkg/meta/annotations_test.go, tests/e2e-leg-3/labels-annotations/35-suspend-reconcile.yaml, tests/e2e-leg-3/labels-annotations/40-wait-for-steadystate.yaml, tests/e2e-leg-3/labels-annotations/45-delete-pod.yaml, tests/e2e-leg-3/labels-annotations/50-assert.yaml, tests/e2e-leg-3/labels-annotations/50-wait-for-steadystate.yaml
This adds the ability to suspend all reconcile activity against a custom resource. This aids in debugging because the operator uses an infinity retry model (i.e. keep retrying the reconcile and use an exponential back-off for repeated failures). This works great unless you want to dig into a specific behaviour that you are seeing.
If any of the CRs (VerticaDB, VerticaAutoscaler, EventTrigger) have the `vertica.com/pause` annotation set to `true`, then no further reconcile will get scheduled for the CR.
This also swaps the create DB parameter --force-cleanup-on-failure with --force-removal-at-creation. It has the same affect, but if you have the operator paused you can see the left over log files from a failed create.
=> Annotation to suspend reconcile on a CR

tests/e2e-udx/udx-cpp/35-verify-cpp-aggregate.yaml
The udx-cpp e2e test has different expected output depending on the server version. For 12.0.4, we mistakenly picked the 23.3.x output.
=> Fix udx-cpp e2e test when run against a 12.0.4

api/v1beta1/eventtrigger_webhook.go, api/v1beta1/eventtrigger_webhook_test.go, changes/unreleased/Fixed-20230526-115323.yaml, config/webhook/manifests.yaml
We built out a webhook for the EventTrigger CRD, but we didn't include it within the webhook config file. This hooks it up so that create/update for EventTrigger CRs go through the webhook for validation.
This also adds a new webhook rule to ensure the job template has a name set.
=> Enable EventTrigger webhook

changes/unreleased/Fixed-20230529-084329.yaml, pkg/controllers/vdb/dbaddnode_reconciler.go, pkg/controllers/vdb/dbaddnode_reconciler_test.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go
There is a small timing window with the operator where we would attempt to do an add node before a pod has run install. This isn't a huge problem as the add node would fail and do things in the correct order in the subsequent reconcile iteration. But fixing this will cut down on the amount of noise in the operator log.
The fix is to check for the install state when we run add node. If we find a pod with a missing db and it doesn't have an install, we will requeue rather than attempting the add node.
=> Fix timing that causes db add node before install

docker-vertica/Dockerfile
Hitting this while installing packages for the first stage of the vertica-k8s container:
```
#0 77.36 + yum install -y cronie dialog glibc glibc-langpack-en iproute openssh-server openssh-clients openssl which zlib-devel
#0 77.84 Last metadata expiration check: 0:00:05 ago on Wed May 31 19:43:14 2023.
#0 78.97 Package glibc-2.28-228.el8.x86_64 is already installed.
#0 78.97 Package iproute-6.2.0-2.el8.x86_64 is already installed.
#0 79.07 Error:
#0 79.07  Problem: cannot install both glibc-common-2.28-226.el8.x86_64 from baseos and glibc-common-2.28-228.el8.x86_64 from @System
#0 79.07   - package glibc-langpack-en-2.28-226.el8.x86_64 from baseos requires glibc-common = 2.28-226.el8, but none of the providers can be installed
#0 79.07   - package glibc-2.28-228.el8.x86_64 from @System …
```
=> Fix for centos:stream8 package issue

changes/unreleased/Changed-20230608-170424.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/paths/paths.go
When using your own ssh keys through a ssh secret, we now mount the secret for the root user too. This comes in handy if you are running a hybrid k8s server and need to run update_vertica from within the pod. Prior to this change you couldn't do that because the ssh key for the root user was unrecognized.
=> SSH secret mounting improvements

changes/unreleased/Fixed-20230616-085300.yaml, docker-vertica-v2/Dockerfile, docker-vertica/Dockerfile
In some deployments, we have seen vbr fail because it cannot find rsync. This creates a symlink in /usr/bin to the rsync binary in /opt/vertica/bin. This ensures that rsync will be found.
=> Fix to ensure vbr can find rsync

pkg/controllers/vdb/restart_reconciler.go, pkg/controllers/vdb/restart_reconciler_test.go, pkg/vadmin/at.go, pkg/vadmin/create_db_at_test.go, pkg/vadmin/describe_db_at_test.go, pkg/vadmin/fetch_node_state_at_test.go, pkg/vadmin/interface.go, pkg/vadmin/opts/reip/opts.go, pkg/vadmin/re_ip_at.go, pkg/vadmin/re_ip_at_test.go, pkg/vadmin/re_ip_vc.go, pkg/vadmin/revive_db_at_test.go, pkg/vadmin/suite_test.go
More work to hide admintools commands behind an abstraction so that we can replace them with the vclusterOps library. This PR handles the admintools -t re_ip command. There is setup for a map file that re_ip needs. This was pushed into the abstraction too. When we create the re_ip API for vclusterOps we won't be specifying the mapping in a file.
=> Add dispatch abstraction for admintools -t re_ip

docker-vertica-v2/s6-rc.d/nma/up
In the v2 vertica-k8s image, the NMA wasn't automatically starting up. The issue was that it wasn't finding the certs because the environment variables it depended on were no loaded. This PR fixes that so it can now find the certs through the environment variables and start.
=> Automatically start the NMA in v2 vertica-k8s image

pkg/cmds/exec.go, pkg/cmds/fake.go, pkg/controllers/vdb/init_db.go, pkg/controllers/vdb/install_reconciler.go, pkg/controllers/vdb/paths.go, pkg/controllers/vdb/restart_reconciler.go, pkg/controllers/vdb/restart_reconciler_test.go, pkg/vadmin/add_node_at.go, pkg/vadmin/add_sc_at.go, pkg/vadmin/at.go, pkg/vadmin/create_db_at.go, pkg/vadmin/describe_db_at.go, pkg/vadmin/fetch_node_state_at.go, pkg/vadmin/re_ip_at.go, pkg/vadmin/remove_node_at.go, pkg/vadmin/remove_sc_at.go, pkg/vadmin/revive_db_at.go, pkg/vadmin/stop_db_at.go, scripts/dockerfile-lint
This is a refactor for the debugDumpAdmintoolsConfg() function. This is called to dump relevant portions of admintools.conf before and after an admintools call. Moving this to call to a common wrapper so we don't have to duplicate the calls so often. This also gets moves it into the admintools version of the Dispatcher interface.
=> Refactor dumping of admintools.conf

pkg/controllers/vdb/restart_reconciler.go, pkg/controllers/vdb/restart_reconciler_test.go, pkg/vadmin/add_sc_vc.go, pkg/vadmin/interface.go, pkg/vadmin/opts/restartnode/opts.go, pkg/vadmin/opts/startdb/opts.go, pkg/vadmin/remove_sc_vc.go, pkg/vadmin/restart_node_at.go, pkg/vadmin/restart_node_at_test.go, pkg/vadmin/restart_node_vc.go, pkg/vadmin/start_db_at.go, pkg/vadmin/start_db_at_test.go, pkg/vadmin/start_db_vc.go
This is a continuation of building out the dispatcher interface. The dispatcher interface will be used to switch between admintools and vcluster library. This adds the final two calls: RestartNode and StartDB.
=> Move restart_node and start_db behind dispatcher abstraction

DEVELOPER.md, Makefile, docker-vertica-v2/Makefile, docker-vertica/Makefile
As of Docker Engine 23.0, Buildx is the default build client. So we are now using it to build our images instead of `docker build`.
All `docker build` calls have been replaced by `docker buildx build`.
=> Build images with docker buildx build

tests/e2e-leg-4/restart-with-liveness-probe/35-assert.yaml, tests/e2e-leg-4/restart-with-liveness-probe/55-assert.yaml
I have seen the restart-with-liveness-probe test fail on occasion. One part of the test will wait for the livenessProbe to kick in an restart the pod. The test assertion check the lastState field in the Pod's container status. I have seen this not be filled in as expected. I am removing it from the assertion in an attempt to make the test run more reliably.
=> Fix flaky e2e test

.github/actions/setup-e2e/action.yaml, .github/workflows/build-images.yml, .github/workflows/e2e.yml
The e2e-vcluster test suite needs to run with the latest version of the server. For this reason, when we run that test suite we will use a private image from the dockerhub repo with the lag lastest-master. We also skip this test suite on forks because it requires secrets that are only accessible through the vertica-kubernetes repo.
We still build the v2 image to make sure nothing is broken. But since it uses an RPM from version 12.0.3 of the server, it doesn't have all of the functionality that the e2e-vcluster test suite needs. So, no e2e tests will run with it.
=> Always run e2e-vcluster with latest master changes

docker-vertica-v2/packages/cleanup.sh
We don't need ssh when running vclusterOps so this removes some of the ssh related files that were left.
=> Remove ssh related files from v2 image

tests/e2e-leg-3/prometheus-service-monitor/05-install-prometheus-crd.yaml
There was a change in a dependent github repo causing a failure in our test. Updating the path to the file in the dependent repo.
=> Fix prometheus-service-monitor e2e testcase

api/v1beta1/verticadb_types.go, changes/unreleased/Changed-20230713-154910.yaml, pkg/version/version.go
Minor bookkeeping necessary whenever we release a new version of the server.
=> Operator updates for new release server version

.github/actions/download-rpm/action.yaml, .github/workflows/e2e-server-upgrade.yml, scripts/guess-server-upgrade-base-image.sh
The base image that we upgrade from in the e2e server upgrade tests needs to be selected based on the target image. Vertica has a rule about upgrade paths that you can't skip major/minor versions. A new script was added that will guess what the base image to use for the upgrades.
Note, this was investigated because the nightly builds are failing. However, there is a bug with the nightly server that prevents the upgrade. So, even with this fix, things will still fail with the nightly test.
=> Pick a proper base image for e2e server upgrade tests

changes/unreleased/Fixed-20230719-140852.yaml, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go
This change fixes a bug in the operator's database existence check in version 1.10.1. The operator used to check for the existence of the catalog directory, but this could lead to errors if the create or revive DB commands failed, as the catalog directory would remain even though the database was not created or revived. This change fixes the bug by looking for a specific file in the catalog directory that is only present for fully initialized databases.
=> Fix the db existence check in the operator

go.mod, go.sum, pkg/aterrors/aterrors.go, pkg/controllers/vdb/verticadb_controller.go, pkg/events/event.go, pkg/vadmin/create_db_vc.go, pkg/vadmin/interface.go, pkg/vadmin/suite_test.go, pkg/vadmin/vc.go, pkg/vadmin/vc_errors.go, pkg/vadmin/vc_errors_test.go
This is a continuation of the vclusterOps integration. The vclusterops library can now flow errors that follow the [RFC 7807 spec](https://datatracker.ietf.org/doc/html/rfc7807). This allows the operator to know about specific error without having to resort to regex based searching. 
We only handle some of the more popular create db failures for now. But this work here will allow us to easily add support for additional types that flow from the vclusterops library.
For instance, if you create a VerticaDB with vclusterops enabled, and the communal storage path given is not empty, we will now see a message like this:
```
Events:
Type     Reason                  Age                   From                Message
----     ------                  ----                  ----                ------- …
```
=> Add event logging for errors from vclusterops library

api/v1beta1/verticadb_types.go, config/manifests/bases/verticadb-operator.clusterserviceversion.yaml, config/samples/v1beta1_verticadb.yaml, config/samples/verticadb_sample.yaml, scripts/setup-olm.sh
In OpenShift, you can create an instance of a VerticaDB using the web UI. It builds the input based on annotations supplied for the various fields in the CR. This updates those annotations to improve the UI for an upcoming demo. Changes to v1beta1_verticadb.yaml were done because the OpenShift web UI uses that to see default values.
=> CSV updates to improve VerticaDB web ui creation

pkg/controllers/vdb/dbaddnode_reconciler.go, pkg/controllers/vdb/install_reconciler.go
This fixes a small regression in this release. We were not logging an event message when add nodes was successful.
Also, moving the pod facts invalidation for vclusterOps. Where it was before meant that we would always invalidate the pod facts cache, even for the case where the install reconciler does nothing.
=> Log successful add nodes in the event log

pkg/controllers/vdb/status_reconciler.go, pkg/controllers/vdb/status_reconciler_test.go
This improves the status reconciler so that it doesn't lose state in the VerticaDB's status fields. I saw a case where we were losing the vnode information -- happened while working on the vclusterops integration and was due to another integration bug. But I thought it would be good to improve the resiliency of this reconciler to handle those edge cases.
=> Improve status retention in the status reconciler

changes/unreleased/Changed-20230728-090741.yaml, docker-vlogger/Dockerfile
This upgrades the base image of the vertica logger image to address security vulnerabilities. We are moving from alpine 3.15 to 3.18.
=> Update base image for vlogger

pkg/controllers/vdb/dbaddsubcluster_reconciler.go, pkg/controllers/vdb/dbremovenode_reconciler.go, pkg/controllers/vdb/dbremovesubcluster_reconciler.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go, pkg/controllers/vdb/restart_reconciler.go, pkg/controllers/vdb/revivedb_reconciler.go, pkg/controllers/vdb/stopdb_reconciler.go
The node list that we pass to reip and start will now be in vnode sorted order. Having a deterministic order for the pods will improve debugging. Also, its temporarily needed for vclusterops integration as that library has a strict requriement on the nodes being in vnode order. This will be dropped later, but I think this improvement can stand on its own just for the improvement to debugging.
This also includes some refactor to cleanup references to admintools in the main vdb package since now the backend could be admintools or vclusterops.
=> Run reip/startdb with consistent node order

tests/e2e-server-upgrade/online-upgrade-block-downgrade/20-initiate-upgrade.yaml
We have to pick a slightly newer image for the online-upgrade-block-downgrade test. Going back to an image that is too old will fail to start due to permission problems required in the docker entry point. This is only a problem with the nightly test that run with the latest server code.
=> Fix e2e server upgrade test

changes/unreleased/Added-20230731-202319.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/cloud/gcp.go, pkg/controllers/vdb/init_db.go, pkg/controllers/vdb/verticadb_controller.go
This is similar to #458 except we read from GSM for the superuser password secret. We use the same feature flag as before. Here is a sample CR to enable it.
```
metadata:
name: v
annotations:
vertica.com/use-gcp-secret-manager: "true" 
spec:
superuserPasswordSecret: <full name of the secret in GSM>
...
```
The name of the GSM secret is taken from the existing `spec.superuserPasswordSecret` field.
Note, we no longer use the canary query for health probes as that depends on the superuser password being a k8s secret. Instead, we check if vertica is running by seeing if anyone is listening on the vertica client port.
=> Allow use of GSM for superuser password secret

go.mod, go.sum
This PR uses the latest VclusterOps, which contains a patch to update the control address and control broadcast of the re-ip nodes.
=> Use the latest patched VClusterOps

pkg/cloud/gcp.go, pkg/controllers/vdb/init_db.go, pkg/controllers/vdb/verticadb_controller.go
If you are using GSM to store secrets, but have not put valid JSON in for the secret contents, you get a very cryptic error. This improves the error output. Here is a sample of what the output will look like now:
```
2023-08-02T17:55:04.019Z        ERROR   Reconciler error        {"controller": "verticadb", "controllerGroup": "vertica.com",
"controllerKind": "VerticaDB", "VerticaDB": {"name":"vertica-gs","namespace":"vertica"}, "namespace": "vertica", 
"name": "vertica-gs", "reconcileID": "5abd8c8e-49c3-4d1c-bb1c-9416747a69e1", 
"error": "failed to read superuser password from GSM: failed to unmarshal the contents of the GSM secret 'projects/1680942424/secrets/kguan-gsm-1/versions/13': invalid character '\\'' looking for beginning of value"}
```
=> Improve error message when GSM secret is malformed

Makefile, go.mod, go.sum, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go, pkg/controllers/vdb/restart_reconciler.go, pkg/vadmin/interface.go, pkg/vadmin/opts/restartnode/opts.go, pkg/vadmin/restart_node_at.go, pkg/vadmin/restart_node_vc.go, pkg/vadmin/restart_node_vc_test.go, tests/e2e-vcluster/vcluster-ks-1/30-assert.yaml, tests/e2e-vcluster/vcluster-ks-1/30-wait-for-restart.yaml
This integration incorporates the vclusterops restart nodes functionality into the operator.
To get restart to work, I had to change the re-ip process. There were cases where, when using admintools, we had to re-ip hosts that had been installed but not yet added to the database. This was necessary to keep the hosts' IP addresses up to date in admintools.conf. This step is not necessary for vclusterops because there is no state file that needs to be synchronized.
=> Implement VClusterOps.RestartNodes

docker-vertica-v2/Dockerfile, docker-vertica-v2/Makefile, docker-vertica/Makefile
The v2 image will always be treated as the NO_KEYS version. Removing the option for checking the environment variable in that image. Treating all spots as if NO_KEYS=YES.
Also, you can now add additional arguments to the docker build for the vertica-k8s image by setting the VERTICA_ADDITIONAL_DOCKER_BUILD_OPTIONS environment variable.
For example:
```
export VERTICA_ADDITIONAL_DOCKER_BUILD_OPTIONS="--platform linux/amd64"
make docker-build-vertica
```
=> Remove NO_KEYS from v2 image

.github/workflows/build-images.yml, .github/workflows/e2e.yml, scripts/push-vertica-server-image.sh
This reverts the change done in #481. It also sets the private repository for the vertica-k8s image to be vertica instead of verticadocker; the later was discontinued.
=> Revert "Fix vcluster in e2e (#481)"

scripts/setup-kustomize.sh, tests/kustomize-defaults.cfg
This adds a new environment variable that will control whether e2e tests are run with vclusterops enabled or not. This is controlled through kustomize. We can use this in the future to run a testcase in either deployment methods.
The default is to run with vclusterops disabled. To run with it enabled, run the following:
```
export VERTICA_DEPLOYMENT_METHOD=vclusterops
scripts/setup-kustomize.sh
<run your test>
```
Note, this works if an annotation is already present in the VerticaDB. I had to use some weird kustomize syntax to avoid clobbering other annotations.
fyi @roypaulin @cchen-vertica
=> Add env var to run e2e tests with vclusterops

go.mod, go.sum, pkg/vadmin/interface.go, pkg/vadmin/restart_node_vc.go, pkg/vadmin/restart_node_vc_test.go, pkg/vadmin/revive_db_vc.go, pkg/vadmin/revive_db_vc_test.go, pkg/vadmin/start_db_vc.go, pkg/vadmin/start_db_vc_test.go
This makes changes to the vcluster API calls to add the timeout option, taken from spec.restartTimeout, for start_db and restart_node. There are also some revive_db changes to be able to integrate with the latest vcluster repo.
=> Add timeout option for VCluster APIs

go.mod, go.sum, pkg/vadmin/vc_errors.go, pkg/vadmin/vc_errors_test.go
This applies to the vclusterops implementation of revive. We will now log an event message if we hit an cluster lease error. We use the new ClusterLeaseNotExpired concrete type to know if we hit this error. This gets us closer in sync with the admintools handling of specific errors (see aterrors.go)
=> Log event message for revive cluster lease error

tests/e2e-leg-3/istio/10-deploy-operator.yaml, tests/e2e-leg-3/istio/15-enable-permissive-mTLS.yaml
Using strict mTLS for istio doesn't work at the moment in our vclusterOps integration. I am changing the testcase to use a more permissive mode. We don't officially support istio in Vertica. But we do use it internally for one of our projects, and that use case doesn't use strict mode. So, it should be okay to change the test for now. Also, deploying the operator with the webhook enabled. I recall at one point the webhook didn't work with istio, but it did when I tried it again, so enabling that part.
=> Use permissive mTLS in istio e2e testcase

go.mod, go.sum, pkg/vadmin/add_node_vc.go, pkg/vadmin/add_sc_vc.go, pkg/vadmin/create_db_vc.go, pkg/vadmin/fetch_node_state_vc.go, pkg/vadmin/re_ip_vc.go, pkg/vadmin/remove_node_vc.go, pkg/vadmin/remove_sc_vc.go, pkg/vadmin/restart_node_vc.go, pkg/vadmin/revive_db_vc.go, pkg/vadmin/start_db_vc.go, pkg/vadmin/stop_db_vc.go, pkg/vadmin/suite_test.go
This PR just changes the Name option to DBName for all operations in the VCluster APIs
=> VCluster API refresh: option Name changed to DBName

go.mod, go.sum
This picks up a new vcluster version, which includes:
- Chinh's bug fix for when depot path has a trailing slash
- Cai's new ReviveDBNodeCountMismatchError struct
=> VCluster API refresh

go.mod, go.sum, pkg/vadmin/vc_errors.go, pkg/vadmin/vc_errors_test.go
This checked revive_db node count mismatch error from vclusterops. When we get this kind of error, we will log the event "ReviveDBNodeCountMismatch".
=> log event message for revive_db node count mismatch

Makefile
It is currently failing because it cannot find the base vertica image the tests start with. For nightly builds it is in a private repository. We need to push that image into kind as part of test setup. Adding a new make target for this. It will be called from within run-k8s-int-tests.sh -- as part of `make docker-push`.
=> Fix e2e-server-upgrade in nightly tests

changes/unreleased/Changed-20231003-094045.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go, tests/e2e-leg-1-failed/client-access/setup-vdb/base/setup-vdb.yaml
Before this change, when the operator set up the statefulset for the subcluster, it set the following capabilities:
```
// Needed to run sshd on OpenShift
"SYS_CHROOT",
// Needed to run sshd on OpenShift
"AUDIT_WRITE",
// Needed to be able to collect stacks via vstack
"SYS_PTRACE", 
``` 
SYS_CHROOT and AUDIT_WRITE are not needed in vclusterops mode so they are not added if vclusterops feature flag is set.
SYS_PTRACE is no longer set by default. If you need to collect stacks, you first have to set the SYS_PTRACE capability in the CR:
```
spec:
securityContext:
capabilities:
add: ["SYS_PTRACE"]
```
=> Update linux capabilities required by the operator

pkg/controllers/vdb/init_db.go, pkg/vadmin/vc.go
This fixes a timing issue that could cause the vclusters create db operation to fail. This can happen if the install is not run before the create db. The installer sets up a configuration file that starts the HTTP service. If this is skipped, the HTTP service will not start and create db will not succeed because it needs that endpoint to communicate with.
=> Ensure http service starts for vcluster create db

api/v1/helpers.go, api/v1/verticadb_types.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, api/v1beta1/verticadb_conversion.go, api/v1beta1/verticadb_conversion_test.go, pkg/controllers/vdb/verticadb_controller.go, pkg/meta/annotations.go, tests/e2e-leg-1/autoscale-by-pod/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-1/autoscale-by-subcluster/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-2/restart-sanity/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-4/createdb-failures/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-4/pvc-expansion/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-4/restart-with-liveness-probe/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-4/revivedb-3-node/vdb-to-create/base/setup-vdb.yaml, tests/e2e-leg-4/revivedb-3-node/vdb-to-revive/base/setup-vdb.yaml, tests/e2e-server-upgrade/offline-upgrade-happy-path/setup-vdb/base/setup-vdb.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-1/setup-vdb/base/setup-vdb.yaml, tests/e2e-server-upgrade/online-upgrade-with-pending-transient/setup-vdb/base/setup-vdb.yaml
Same rationale as in #531 . This moves the `spec.requeueTime` field to an annotation. The v1beta1 API is not impacted by this.
=> Rename v1 API fields: requeueTime

pkg/controllers/vdb/verticadb_controller.go, pkg/vadmin/add_node_vc.go, pkg/vadmin/add_sc_vc.go, pkg/vadmin/create_db_vc.go, pkg/vadmin/describe_db_vc.go, pkg/vadmin/fetch_node_state_vc.go, pkg/vadmin/interface.go, pkg/vadmin/re_ip_vc.go, pkg/vadmin/remove_node_vc.go, pkg/vadmin/remove_sc_vc.go, pkg/vadmin/restart_node_vc.go, pkg/vadmin/revive_db_vc.go, pkg/vadmin/start_db_vc.go, pkg/vadmin/stop_db_vc.go, pkg/vadmin/suite_test.go
This creates a custom logger for each vcluster API call. The purpose is so that we can construct a logr.Logger object using the WithName() function. This will give us a better idea of where the various log entries are coming from. For instance, with this change, you can see the 3 log messages below all originate from the CreateDB API call (3rd column in each log statement).
2023-10-14T21:14:35.123Z    INFO    controllers.VerticaDB.CreateDB Starting vcluster CreateDB  {"verticadb": "kuttl-test-able-insect/v-client-access"}
2023-10-14T21:14:35.123Z    INFO    controllers.VerticaDB.CreateDB Setup create db options {"verticadb": "kuttl-test-able-insect/v-client-access", "hosts": "10.244.0.28"}
2023-10-14T21:14:35.123Z    INFO    controllers.VerticaDB.CreateDB starting VCreateDatabase …
=> Set a custom logger for each vcluster API

api/v1/helpers.go, api/v1/verticadb_types.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, api/v1beta1/verticadb_conversion.go, api/v1beta1/verticadb_conversion_test.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/controllers/vdb/obj_reconciler.go, pkg/controllers/vdb/obj_reconciler_test.go, pkg/controllers/vdb/offlineupgrade_reconciler.go, pkg/controllers/vdb/offlineupgrade_reconciler_test.go, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/onlineupgrade_reconciler_test.go, pkg/meta/annotations.go, tests/e2e-leg-1/autoscale-by-pod/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-1/autoscale-by-subcluster/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-5/custom-cert-webhook-cabundle-in-secret/setup-vdb/base/setup-vdb.yaml
Another change to move CR parms to annotations in the v1 API. This moves both upgradeRequeueTime and SSHSecret over. See #531 to understand why we are making this change. No change is done to the v1beta1 API.
=> Rename v1 API fields: upgradeRequeueTime and SSHSecret

api/v1/helpers.go, api/v1/verticadb_types.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, api/v1beta1/verticadb_conversion.go, api/v1beta1/verticadb_conversion_test.go, pkg/controllers/vdb/config.go, pkg/controllers/vdb/init_db_test.go, pkg/meta/config.go, pkg/vdbgen/vdb.go, pkg/vdbgen/vdb_test.go
Another change to move CR parms to annotations in the v1 API. This removes both kerberosServiceName and kerberosRealm. Both of them can be specified through the `spec.communal.additionalConfig`, so it didn't make sense to have separate fields. See #531 to understand why we are changing the v1 API. No change is done to the v1beta1 API.
=> Rename v1 API fields: kerberosRealm and kerberosServiceName

pkg/builder/builder.go, pkg/paths/paths.go
For vclusterops deployments, we want to carve out a portion of the PV for use with scrutinize. The directory will be /tmp/scrutinize. We are doing this because we don't want to risk filling up the node's local directory with compressed diagnostics. These can be quite big. If the node's space is used then k8s will simply reschedule the pod, forcing the scrutinize to start over.
=> Include scrutinize storage in PV

changes/unreleased/Fixed-20231018-111648.yaml, pkg/controllers/vdb/dbremovenode_reconciler.go, pkg/controllers/vdb/dbremovenode_reconciler_test.go, pkg/controllers/vdb/dbremovesubcluster_reconciler.go, pkg/controllers/vdb/dbremovesubcluster_reconciler_test.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go
This fixes an issue with the drain we do for scale down. There was a small timing window where we would not do the drain. Instead, we proceed to the scale down. Any active connections on the removed nodes would be end without warning.
=> Fix timing hole that skips drain for scale down

.github/actions/setup-kubectl/action.yaml, go.mod, go.sum, pkg/vadmin/vc_errors_test.go
This picks up the latest vclusterops package. The key change is the logging for the library now uses the logr.Logger API everywhere. So, all of the logging for the operator and vclusterops should now follow the same format.
I also made a CI change. I noticed that we were having trouble downloading kubectl. This should be already included in the GitHub runners so removing the download step.
=> VCluster API Refresh: logging update

.github/actions/setup-e2e/action.yaml, .github/workflows/build-images.yml, .github/workflows/e2e.yml, Makefile, config/samples/v1beta1_verticadb.yaml, docker-vertica/Dockerfile, docker-vertica/Makefile
There is some image changes for this PR
- remove the nokeys image from the pipeline and NO_KEYS env var usage
- GH actions to stop using latest-master for vcluster tests. Instead use full or minimal, depending on the leg.
=> CI changes for new k8s images

api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go
Vertica cannot run if the user is root (uid == 0). This adds a webhook preventing that setting from even being set.
=> Add webhook to prevent setting of runAsUser as root

pkg/controllers/et/eventtrigger_controller.go, pkg/controllers/vas/verticaautoscaler_controller.go
Both the verticaautoscaler and eventtrigger controllers both watch the v1beta1 API. Functionaly this is fine, but it causes deprecation warnings to printed in the operator log like this: [W1024 15:58:00.630253 1 warnings.go:70] vertica.com/v1beta1 VerticaDB is deprecated, use vertica.com/v1 VerticaDB
Changing them to watch the v1 API will silence this message.
=> Vertica controllers to add watches for v1 API

pkg/controllers/vdb/restart_reconciler.go
Transient nodes are read-only secondary nodes so it cannot be started using vclusterops. As a result, I removed transient nodes from start node list. This change shouldn't affect existing features.
=> Removed transient nodes from node list when starting db

api/v1/verticadb_types.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, tests/e2e-server-upgrade/online-upgrade-with-pending-transient/35-modify-actual-transient.yaml
- Change default subcluster type to `primary` always
- Remove the auto case conversion for the type string (so now when a user provides a type string with upper-case letters, e.g. `Primary`, an error will be reported)
Note: these changes apply to the v1 API. The v1beta1 API was not changed.
=> Change default subcluster type in V1 VerticaDB API

changes/unreleased/Added-20231107-173951.yaml, docker-vertica-v2/Dockerfile
In the v2 vertica image, we can now redirect startup.log to stdout by setting `VERTICA_STARTUP_LOG_DUPLICATE` to `/proc/1/fd/1`.
An example of a Vertica pod log output via `kubectl logs v-sc0-0`:
```
2023/11/06 14:34:09 New NodeManagementAgent starting
2023/11/06 14:34:09 Checking for existence of directory  /opt/vertica/log
2023/11/06 14:34:09 Moving working directory to  /opt/vertica/log
2023/11/06 14:34:09 Successfully opened file node_management_agent.log. Setting log output to that file.
{
"goal" : 27,
"node" : "v_vertdb_node0001",
"progress" : 0,
"stage" : "Reading Catalog",
"text" : "Indexing Objects",
"timestamp" : "2023-11-06 14:34:18.414"
}
{
"goal" : 27,
"node" : "v_vertdb_node0001",
"progress" : 27,
"stage" : "Reading Catalog",
"text" : "Indexing Objects",
"timestamp" : …
```
=> Redirect startup.log to stdout

.github/workflows/e2e-leg-4.yml, api/v1/helpers.go, api/v1beta1/verticadb_types.go, changes/unreleased/Added-20231107-093813.yaml, pkg/cmds/cmds_test.go, pkg/cmds/exec.go, pkg/cmds/fake.go, pkg/controllers/vdb/verticadb_controller.go, pkg/meta/annotations.go, pkg/vadmin/add_node_vc.go, pkg/vadmin/add_sc_vc.go, pkg/vadmin/create_db_vc.go, pkg/vadmin/fetch_node_state_vc.go, pkg/vadmin/re_ip_vc.go, pkg/vadmin/remove_node_vc.go, pkg/vadmin/remove_sc_vc.go, pkg/vadmin/restart_node_vc.go, pkg/vadmin/start_db_vc.go, pkg/vadmin/stop_db_vc.go, scripts/setup-kustomize.sh, tests/e2e-leg-4/revivedb-1-node/27-create-et.yaml, tests/kustomize-defaults.cfg
Added a superuser-name annotation. This annotation can be used to customize Vertica superuser name. This should be used with vclusterops. When admintools is used, this annotation will be always set to "dbadmin".
=> Added a new annotation: vertica.com/superuser-name

go.mod, go.sum, pkg/vadmin/re_ip_vc.go, pkg/vadmin/start_db_vc.go, pkg/vadmin/start_db_vc_test.go
This PR synced the new changes from `vclusterops` and set the "trim node" options to be true in `re_ip` and `start_db` to avoid possible wrong input in case the operators provide more hosts/nodes than needed.
=> Trim nodes in re_ip and start_db to avoid failures from wrong input

pkg/controllers/vdb/go_id_helper.go, pkg/controllers/vdb/verticadb_controller.go
This code change is only for debugging intermittent errors in "update-strategy" test of e2e-leg-2. After the issue is fixed, we should revert the changes in this PR since retrieving goroutine ID is not recommended in golang.
=> Added goroutine ID to reconciler log for debugging purpose

go.mod, go.sum, pkg/vadmin/start_db_vc.go
This PR simply removed the pointer initialization on the operator side for `start_db` as the pointers have been initialized on the vclusterops side.
=> Remove vcluster pointer initialization on the operator side

pkg/version/version.go, pkg/version/version_test.go
With the new server versions, the minor is changing quite frequently. Each release is essentially a minor version change. And that is happening every quarter. So we added a rule so that the x.4.0 cannot be skipped but intermediate ones can. For instance. If someone is on 23.4.0, they can directly to 24.4.0 skipping 24.1.0, 24.2.0 and 24.3.0
=> Change upgrade path rules for new server versions

pkg/builder/builder_test.go, pkg/controllers/vdb/serviceaccount_reconciler.go, pkg/meta/annotations.go
- The operator respects the `vertica.com/mount-nma-certs` annotation when it is provided
- When it is not provided the operator assumes its value is `true` which means the NMA will read certs from a mounted secret volume (and proper env vars will be available in the db node containers)
- `serviceaccount_reconciler` skips role/rolebinding lookup and creation if `vertica.com/mount-nma-certs` is `true` or not provided (which will default to `true`), as that role is merely serving the purpose of granting the `get` and `list` permissions for secrets, which is only required when the NMA actually reads certs from k8s secrets directly.
=> Operator mounts NMA certs in a volume by default

.github/workflows/e2e-leg-1.yml, .github/workflows/e2e-leg-2.yml, .github/workflows/e2e.yml
This PR adds two previously images,` vertica/vertica-k8s:23.4.0-0-minimal` and `vertica/vertica-k8s:12.0.4-0-minimal`, in the available e2e-leg*.yml files. Additionally, a parameter `artifact_suffix` is introduced to avoid duplicating the artifact file for each run of the leg.
=> Run legs against previously released vertica image

api/v1/helpers.go, changes/unreleased/Added-20231121-133042.yaml, changes/unreleased/Removed-20231121-081101.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/controllers/vdb/config.go, pkg/controllers/vdb/init_db_test.go, pkg/controllers/vdb/suite_test.go, pkg/controllers/vdb/verticadb_controller.go, pkg/meta/annotations.go
Removed the annotation "vertica.com/use-gcp-secret-manager" in the operator. Instead, to read from GSM, the operator will check if the secrets of superuser password and communal access credentials have the prefix "gsm://".
=> Deduce the secret location is GSM with secret path reference

tests/e2e-leg-1/client-access/17-assert.yaml
I saw a case where we fail in step 30 of client-access with this error:
+ CLUSTER_IP=v-client-access-sc1
+ vsql -U dbadmin -h v-client-access-sc1 -c 'drop table if exists t1' vsql: could not connect to server: Connection refused
Is the server running on host "v-client-access-sc1" and accepting
TCP/IP connections on port 5433?
I think this error occurs due to timing -- we try to access the service object before it has the necessary labels for routing.
=> Improve stability of client-access e2e test

tests/e2e-leg-3/revive-with-different-local-paths/50-assert.yaml
This is another attempt at fixing the timing scenario in revive-with-different-local-paths. I suspect that the assertion for step 50 has a small timing window -- we need to provision the pods and still see the paths as invalid in the VerticaDB, but the operator can update the paths pretty quick. I am just going to check for the paths and not bother with verifying the pods any more.
=> Fix intermittent e2e test failure

changes/unreleased/Added-20231130-121009.yaml, scripts/config-transformer.sh, scripts/undeploy.sh, tests/e2e-leg-5/deploy-with-manifest/05-create-creds.yaml, tests/e2e-leg-5/deploy-with-manifest/10-assert.yaml, tests/e2e-leg-5/deploy-with-manifest/10-deploy-operator.yaml, tests/e2e-leg-5/deploy-with-manifest/15-assert.yaml, tests/e2e-leg-5/deploy-with-manifest/15-setup-vdb.yaml, tests/e2e-leg-5/deploy-with-manifest/90-delete-cr.yaml, tests/e2e-leg-5/deploy-with-manifest/90-errors.yaml, tests/e2e-leg-5/deploy-with-manifest/95-errors.yaml, tests/e2e-leg-5/deploy-with-manifest/95-uninstall-operator.yaml, tests/e2e-leg-5/deploy-with-manifest/98-assert.yaml, tests/e2e-leg-5/deploy-with-manifest/98-cleanup-storage.yaml, tests/e2e-leg-5/deploy-with-manifest/98-errors.yaml, tests/e2e-leg-5/deploy-with-manifest/99-delete-ns.yaml, tests/e2e-leg-5/deploy-with-manifest/setup-vdb/base/kustomization.yaml, tests/e2e-leg-5/deploy-with-manifest/setup-vdb/base/setup-vdb.yaml
Now that our operator is cluster scoped, we can deploy it using simple `kubectl apply -f ...` commands. This adds that manifest to our release artifacts. This will be published on GitHub in our 2.0.0 release. Once released the command will be:
```
kubectl apply --server-side=true --force-conflicts -f https://github.com/vertica/vertica-kubernetes/releases/latest/download/verticadbs.vertica.com-crd.yaml
kubectl apply --server-side=true --force-conflicts -f https://github.com/vertica/vertica-kubernetes/releases/latest/download/verticaautoscalers.vertica.com-crd.yaml
kubectl apply --server-side=true --force-conflicts -f https://github.com/vertica/vertica-kubernetes/releases/latest/download/eventtriggers.vertica.com-crd.yaml
kubectl apply -f …
```
=> Deploy operator with single YAML manifest

scripts/capture-scrutinize.sh
We have a helper script called capture-scrutinize.sh that will gather scrutinize during e2e runs. A few e2e tests use it and require that scrutinize be successful. One of those testcases, nma-cert-mounts, has failed because it couldn't talk to the NMA. It was running this right after a restart, but it was sending the request to an old IP. We pass in the host name to scrutinize. I suspect it resloved the host using a stale DNS cache and got the old IP. I am changing the script to use IPs instead of hosts.
=> capture-scrutinize.sh to use IP instead of host

CONTRIBUTING.md, DEVELOPER.md
- update email for Vertica open source team
- RPM name for vertica-k8s containers can be more flexible (due to #616)
=> Minor updates to markdown

changes/unreleased/Changed-20231207-104501.yaml, docker-vertica-v2/Dockerfile, docker-vertica-v2/Makefile, docker-vertica/Dockerfile, docker-vertica/Makefile, docker-vertica/s6-rc.d/cron/run, tests/e2e-leg-3/revive-with-different-local-paths/30-assert.yaml, tests/e2e-leg-6/verify-server-logrotate/08-upload-files.yaml, tests/e2e-leg-6/verify-server-logrotate/setup-env-runtime.sh, tests/e2e-udx/udx-cpp/setup-env-runtime.sh, tests/e2e-udx/udx-java/30-upload-files.yaml, tests/e2e-udx/udx-java/setup-env-runtime.sh, tests/e2e-udx/udx-python/30-upload-files.yaml, tests/e2e-udx/udx-python/setup-env-runtime.sh
This switches the v1 and v2 container from being built on ubuntu to rockylinux 9. This will make it easier built custom images since RHEL based distros are more commonly used for enterprise deployments. Some e2e test updates to account for the different set of packages that was installed.
=> Switched server container from ubuntu to rockylinux

api/v1/verticadb_types.go, pkg/controllers/vdb/verticadb_controller.go
Two minor things I am changing here to prepare for the upcoming operator releas:
- change default server version that the operator will use to 24.1.0
- log additional information about the VerticaDB at the start of a reconcile iteration to aid in debugging
=> Operator release prep

tests/e2e-leg-3/revive-with-different-local-paths/50-assert.yaml, tests/e2e-server-upgrade/online-upgrade-and-scale-up/21-wait-for-upgrade-to-start.yaml
This tries to fix a small timing window in revive-with-different-local-paths. There is a small window, 13 seconds in the failed case, when the k8s objects are in the correct state to match step 50 assert. If we transition too fast, then we don't catch the assertion. I am trying to fix this by reducing what we are checking in the assertion.
=> Fix e2e test failures

pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/restart_reconciler.go
This is to fix intermittent failures in the pending-pod e2e testcase when run in vclusterops mode. The restart reconciler needs to requeue if pods that it needs aren't running. We were too aggressive with vclusterops because we triggered on installed state, which may or may set correctly. This changes the check for vclusterops and only looks at dbExists state. It also correctly sets the installed state for vclusterops in all cases.
=> Fix restart reconciler requeue logic for vclusterops

go.mod, go.sum
This PR synced the new vclusterops changes, which will not output vcluster CLI console messages to the operator logs.
=> VCluster API Refresh: omit vcluster console messages

changes/unreleased/Fixed-20231213-101202.yaml, pkg/builder/builder.go, pkg/controllers/vdb/clientroutinglabel_reconciler.go, pkg/controllers/vdb/clientroutinglabel_reconciler_test.go, pkg/controllers/vdb/drainnode_reconciler.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go, pkg/meta/annotations.go, tests/e2e-server-upgrade/online-upgrade-no-transient-2-sc/setup-vdb/base/setup-vdb.yaml
The controller was not handling terminating pods correctly. This could lead to problems during online upgrades, such as not properly restarting primaries before taking down secondaries.
The issue occurs when the operator deletes pods with the old image. If the pod is still running immediately after the deletion, the operator may skip the restart and move on to the next phase of the upgrade. This is a small window because the termination grace period is 0 seconds, but we still see it occasionally in the e2e runs.
To test this issue, I added a new annotation (vertica.com/termination-grace-period-seconds) that makes it easier to hit this timing scenario. This annotation causes the pod to be in the termination step for a longer period of time.
The solution was to check for pod termination in …
=> Online upgrade to account for terminating pods

pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/upgrade.go
If upgrading from an admintools deployment to a vclusterops deployment, this change is needed if doing that via an online upgrade. We can't handle an online upgrade in this fashion because the NMA isn't running in pods still doing an admintools style of deployment. We have to take down any pods running admintools deployments. This will make the online upgrade offline, but at leaste then we can proceed.
=> Allow upgrade through a deployment change

changes/unreleased/Fixed-20231220-093626.yaml, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/onlineupgrade_reconciler_test.go, pkg/meta/annotations.go
In a previous change, we transition from an online to an offline upgrade if you attempt do to an upgrade across deployments. Across deployments means you are changing from admintools to vclusterops.  The original fix worked, but we mistakenly bypass it if we are also ignoring upgrade paths. This change ensures we handle things properly if also ignoring upgrade paths.
=> Fix upgrades across deployments when ignoring upgrade paths

Makefile, changes/unreleased/Security-20231220-172216.yaml, docker-operator/Dockerfile, go.mod, go.sum
This uplifts a package that the operator uses to resolve the [CVE-2023-48795](https://nvd.nist.gov/vuln/detail/CVE-2023-48795) vulnerability.
=> Fix CVE-2023-48795

api/v1/version.go, pkg/controllers/vdb/imageversion_reconciler.go, pkg/controllers/vdb/imageversion_reconciler_test.go
The NMA can read the TLS cert from an external secret store like Google Secret Manager or AWS Secrets Manager. This adds checks to ensure the NMA version is correct for the type of secret store used.
=> Check NMA version is compatible with external TLS secret store

pkg/secrets/client.go, pkg/secrets/fetcher_test.go, tests/e2e-leg-1/crash-before-createdb/10-assert.yaml, tests/e2e-leg-1/crash-before-createdb/15-assert.yaml
After monitoring the test results over the last week, I noticed two things that I am fixing:
- the e2e test crash-before-createdb, is suppose to kill pods in the middle of a create db. But sometimes the database is created before the kills if it is really quick. I am improving the testcase so that it can tolerate this.
- unit test for secrets package can sometimes fail because a namespace it depends on doesn't exist. I am changing the testcase so that it explicitly creates the namespace it needs.
=> Fixes for flaky tests

changes/unreleased/Fixed-20240102-145553.yaml, pkg/controllers/vdb/depobjcheck_reconciler.go, pkg/controllers/vdb/verticadb_controller.go
This issue closes a timing loophole in which the removal of a dependent object does not always trigger a reconcile. This was observed occasionally in the use-own-serviceaccount e2e test. We originally relied on watches that we set up with kube-apiserver. However, there appears to be a small window of time in which the removal of a watched object does not trigger a reconcile.
=> Check dependent objects at the end of a reconcile

changes/unreleased/Fixed-20240103-104435.yaml, go.mod, go.sum, pkg/meta/annotations.go, pkg/test/helpers.go, pkg/vadmin/create_db_vc.go, pkg/vadmin/create_db_vc_test.go, pkg/vadmin/restart_node_vc.go, pkg/vadmin/suite_test.go
This builds on a change made in vclusterops. It can now emit a specific error if it discovers that the database is already running. We add a feature flag to tolerate this (the default is true). This can allow us to proceed if we are in an environment with few resources available, which can cause instability during the creation process. If we have previously progressed far enough that Vertica is running, we will skip the create db step and proceed to the next reconciler. This will update the status condition to indicate that the database has been initialized.
=> VCluster API refresh: allow create db to proceed if db is already running

changes/unreleased/Changed-20240104-142619.yaml, pkg/meta/annotations.go, pkg/version/version.go, pkg/version/version_test.go
This operator update removes logic that prevented upgrades if the user skipped too many releases. This change is consistent with a recent update to the Vertica documentation, which no longer requires users to upgrade through all intermediate releases.
The old documentation stated that "Vertica upgrades must be performed in a linear fashion, with each release upgraded before the next." However, this requirement has been removed. Users can now upgrade to any supported release, regardless of whether they have skipped intermediate releases.
The only restriction that the operator still enforces is that users cannot downgrade.
=> Upgrade path detection will now only prevent downgrades

.github/workflows/build-release-assets.yml, scripts/config-transformer.sh
The build release assets workflow was not including all of the manifests that we wanted to include with the operator GitHub release. This has been corrected. Additionally, the operator.yaml that we generate for the release was not using the correct image name for our public operator image. This has also been fixed. These issues were discovered while releasing the 2.0.0 of the operator.
=> Include omitted release manifests

scripts/push-vertica-server-image.sh
The script still references an old image (-nokeys) that we no longer create. I updated the script to account for that. I also added a command to dump the version in images to verify we have the correct ones.
=> Update push-vertica-server-image.sh for new images

.github/workflows/verify-public-artifacts.yml, config/samples/verticadb_sample.yaml
We have this workflow that we use to validate after every operator release. This was broken in the last release. Included in here are fixes to get that working again.
=> Fixes for the verify-public-artifact workflow

scripts/guess-server-upgrade-base-image.sh, scripts/image-utils.sh, scripts/setup-kustomize.sh
When our server builds a new hotfix for 24.1.0 it will kick off a CI run and try to run some of the tests with the NMA sidecar. The NMA sidecar is only supported in 24.2.0 and above. This changes disables NMA sidecar when it detects you are running with 24.1.0.
This also cleans up some logic related to guessing the base image for a version. We had a complicated set of instructions for picking the right base image so that our upgrade tests can adhere to the upgrade path. The upgrade path logic has since been removed, which makes it easier to pick the base image. So, that has been cleaned up.
=> Don't use NMA sidecar in our CI when running 24.1.0

.github/workflows/e2e-udx.yml, tests/e2e-udx/udx-cpp/30-upload-files.yaml, tests/e2e-udx/udx-java/30-upload-files.yaml, tests/e2e-udx/udx-python/30-upload-files.yaml, tests/manifests/kind-hostpath/server-mount-patch.yaml
This is a test update for the UDX tests. We need to explicitly specify the container we want to use when setting up the development environment. I have enabled the NMA sidecar when running the UDX test suite in the end-to-end (e2e) tests.
=> Fix udx tests to run with NMA sidecar

tests/e2e-leg-6/verify-server-logrotate/expected-output/logrotateTimerServiceOut.txt
This PR is just a quick fix for e2e verify-server-logrotate in leg 6, as after 24.1.0 server, we also rotate the editor.log
=> fix verify-server-logrotate test

api/v1beta1/verticarestorepointsquery_types.go, pkg/controllers/vrpq/query_reconciler.go, pkg/controllers/vrpq/query_reconciler_test.go, pkg/vrpqstatus/status.go, pkg/vrpqstatus/status_test.go, tests/e2e-leg-6/verify-vrpq-conditions/10-assert.yaml, tests/e2e-leg-6/verify-vrpq-conditions/10-verify-conditions.yaml
This PR adds custom print columns for the new VerticaRestorePointsQuery CR, so that a kubectl get vrpq command tells you if the query has completed.
=> Add custom print columns for VerticaRestorePointsQuery

tests/e2e-server-upgrade/offline-upgrade-ks-0/30-wait-for-bad-image-upgrade-start.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/38-wait-for-bad-image-upgrade-start.yaml, tests/e2e-server-upgrade/offline-upgrade-ks-0/46-wait-for-bad-image-upgrade-start.yaml
Small fix to a recent change I made to this test for the NMA sidecar feature. I need to ensure we wait appropriately for the operator to acknowledge an upgrade before moving onto the next step. We use to verify this by checking the image, but that was removed because there is another container to check now.
=> Fix offline-upgrade-ks-0 e2e test

.github/workflows/e2e-leg-6.yml
This changes e2e-leg-6 so that it only runs on 24.2.0+ server. On older releases some of the testcases fail. This is due to the new NMA container.
=> Only run e2e-leg-6 in 24.2.0+ server

.github/actions/setup-e2e/action.yaml, .github/actions/setup-go/action.yaml, .github/workflows/build-images.yml, .github/workflows/build-release-assets.yml, .github/workflows/e2e-leg-1.yml, .github/workflows/e2e-leg-2.yml, .github/workflows/e2e-leg-3.yml, .github/workflows/e2e-leg-4.yml, .github/workflows/e2e-leg-5.yml, .github/workflows/e2e-leg-6.yml, .github/workflows/e2e-leg-7.yml, .github/workflows/e2e-operator-upgrade.yml, .github/workflows/e2e-server-upgrade.yml, .github/workflows/e2e-udx.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, .github/workflows/scorecardtests.yml, .github/workflows/unittests.yml, .github/workflows/verify-public-artifacts.yml, scripts/config-transformer.sh, scripts/gen-release-artifacts.sh, tests/e2e-server-upgrade/online-upgrade-drain/long-running-connection-secondary/base/long-running-connection.yaml
This updates actions used in the CI to new versions that aren't using Node 16. Node 16 was deprecated in GitHub actions, so we have warnings when we have actions using them. There are still a few remaining deprecations, which will be fixed at a later time.
One other notable change. The verify-public-release workflow has been updated so we have the option now to deploy the operator with kubectl.
=> CI Updates for Node 16 deprecation

PROJECT, api/v1beta1/groupversion_info.go, api/v1beta1/helpers.go, api/v1beta1/verticadb_types.go, api/v1beta1/verticascrutinize_types.go, cmd/operator/main.go, config/crd/kustomization.yaml, config/crd/patches/webhook_in_verticascrutinizers.yaml, config/crd/patches/webhook_in_verticascrutinizes.yaml, config/default/manager_auth_proxy_patch.yaml, config/manifests/bases/verticadb-operator.clusterserviceversion.yaml, config/rbac/verticascrutinize_editor_role.yaml, config/rbac/verticascrutinize_viewer_role.yaml, config/samples/kustomization.yaml, config/samples/v1beta1_verticascrutinize.yaml, helm-charts/verticadb-operator/README.md, helm-charts/verticadb-operator/tests/kind-concurrency_test.yaml, helm-charts/verticadb-operator/values.yaml, pkg/controllers/vscr/suite_test.go, pkg/controllers/vscr/vertica_scrutinize_controller_test.go, pkg/controllers/vscr/verticascrutinize_controller.go, pkg/opcfg/config.go, scripts/config-transformer.sh, scripts/template-helm-chart.sh, tests/e2e-leg-5/metrics-disabled/05-assert.yaml, tests/e2e-leg-5/metrics-no-auth/05-assert.yaml, tests/e2e-leg-5/prometheus-service-monitor/10-assert.yaml, tests/e2e-leg-5/prometheus-service-monitor/20-assert.yaml
This PR build out the stub for an empty controller to handle the VerticaScrutinize API. For now The operator can observe the new API, initiate a reconciliation iteration, and take no action, as we have set nil for the actors during this implementation phase
=>  Add empty controller and API for VerticaScrutinize

api/v1/helpers.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, changes/unreleased/Added-20240202-082047.yaml, go.mod, go.sum, pkg/meta/annotations.go, pkg/vadmin/create_db_vc.go, pkg/vadmin/create_db_vc_test.go, pkg/vadmin/suite_test.go
This adds an annotation to be able to control the timeout we wait during create db for the nodes to come up. The annotation value is: `vertica.com/createdb-timeout`.
=> Configure createdb timeout by annotation vertica.com/createdb-timeout

.github/workflows/build-images.yml, .github/workflows/e2e.yml
We are having issues accessing the private images from vertica/vertica-k8s-private in our CI. Using a different repository for the time being.
=> Temporarily use a different image repo for latest images

changes/unreleased/Fixed-20240213-111303.yaml, pkg/builder/builder_test.go, pkg/controllers/vdb/obj_reconciler.go, pkg/controllers/vdb/offlineupgrade_reconciler.go, pkg/controllers/vdb/offlineupgrade_reconciler_test.go, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/onlineupgrade_reconciler_test.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/restart_reconciler.go, pkg/controllers/vdb/upgrade.go, pkg/controllers/vdb/upgrade_test.go, pkg/names/names.go, pkg/vk8s/container.go, pkg/vk8s/container_test.go
Starting in istio 1.17, the istio proxy is now injected as the first container. This breaks some assumptions in the operator code. It assumes that any sidecar is injected at the end and the first two containers are the nma and server. This changes fixes that by referencing containers by their names rather than index. I removed all of the helpers based on index and instead get them by name.
=> Fixes Istio proxy sidecar initialization issue

.github/workflows/build-release-assets.yml, scripts/create-release.sh
The recent change to update the version of actions/upload-artifacts from v3 to v4 changed the structure of the artifacts. Updating the release operator procedure to account for that.
=> Fixes for github actions to release the operator

pkg/builder/builder.go, pkg/controllers/vdb/obj_reconciler.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/upgrade.go, pkg/vk8s/container.go
Found another case where we lookup the container by index rather than name. Index isn't reliable if sidecars are injected, like for istio.
=> Fix container index lookup

.github/workflows/build-images.yml, .github/workflows/release.yml, .gitignore, Makefile, changes/unreleased/Added-20240228-172721.yaml
The operator was initially designed exclusively for the amd64 platform. This modification aims to extend its compatibility to the arm64 platform. It's primarily intended for experimental purposes at this stage.
=> Add experimental support to run the operator on arm64

config/manifests/bases/verticadb-operator.clusterserviceversion.yaml
When adding the operator to the OpenShift catalog, there is a new requirement of a set of standard annotations that the CSV has. These are being added here. For a description of each of the annotations see this: https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs
=> Add required CSV annotations

tests/e2e-leg-4/revivedb-1-node/vdb-to-create/base/setup-vdb.yaml, tests/e2e-leg-4/revivedb-1-node/vdb-to-revive/base/setup-vdb.yaml, tests/e2e-leg-4/revivedb-multi-sc/vdb-to-create/base/setup-vdb.yaml, tests/e2e-leg-6/nma-certs-mount/setup-vdb/base/setup-vdb.yaml
Those changes are made to allow some test cases to bypass scrutinize-related bugs, until they are fixed.
=> Make some changes to scrutinize related test cases

pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/controllers/vscr/scrutinizepod_reconciler.go, pkg/controllers/vscr/scrutinizepod_reconciler_test.go
When the db doesn't have a password, we append `password=` to scrutinize cmd.
=> Allow empty password for vcluster scrutinize

pkg/vdbconfig/config.go, pkg/vdbconfig/config_test.go
If the region that the communal storage should use isn't set, then we normally pick a default. This only works if the webhook is enabled. This fixes a problem getting the default one when the webhook is disabled.
=> Set default region when webhook isn't set

changes/unreleased/Added-20240313-142514.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/controllers/vscr/podpolling_reconciler.go
Here are a few changes to make it easier to integrate custom init containers into the VerticaScrutinize CR:
- Include an environment variable, `SCRUTINIZE_TARBALL`, containing the full path of where the tarball resides.
- Mount the volume containing the tarball so that the containers have access to it.
=> Make it easier to integrate custom containers with VerticaScrutinize

tests/e2e-leg-4/revivedb-1-node/vdb-to-create/base/setup-vdb.yaml, tests/e2e-leg-4/revivedb-1-node/vdb-to-revive/base/setup-vdb.yaml, tests/e2e-leg-4/revivedb-multi-sc/vdb-to-create/base/setup-vdb.yaml, tests/e2e-leg-6/nma-certs-mount/setup-vdb/base/setup-vdb.yaml
Due to some issues to some issues in vcluster scrutinize, we had to update scrutinize-related e2e tests(https://github.com/vertica/vertica-kubernetes/pull/726). This is to undo those changes now that all the issues have been resolved.
=> Revert changes in some scrutinize related test cases

.golangci.yml, changes/unreleased/Fixed-20240320-101134.yaml, pkg/controllers/vdb/obj_reconciler.go, pkg/controllers/vdb/obj_reconciler_test.go, pkg/controllers/vdb/resizepv_reconciler.go, pkg/events/event.go, pkg/test/helpers.go, pkg/v1beta1_test/helpers.go, pkg/vadmin/install_packages_at.go, tests/e2e-leg-6/labels-annotations/55-add-service-annotations.yaml, tests/e2e-leg-6/labels-annotations/55-assert.yaml, tests/e2e-leg-6/labels-annotations/60-assert.yaml, tests/e2e-leg-6/labels-annotations/60-change-service-annotations.yaml, tests/e2e-leg-6/labels-annotations/65-wait-for-steadystate.yaml
In ROSA (RedHat OpenShift on AWS), we noticed that when setting up a network LoadBalancer an annotation would automatically be added to the Service object. This caused the operator to start a reconcile loop. It would remove the annotation, only to have OpenShift add it back. So, the operator was in a continuous reconcile loop.
To fix this we now allow manual annotations be added to service objects. The operator will only ensure the annotations that it generates are the correct value. It will ignore any additional annotation that was added outside of the VerticaDB.
I am also cleaning up the PVC expansion events. This can cause quite a lot of noise about skipping expansion if we continuously are doing reconciles. The skip events have been changed to log entries instead.
=> Resolved Service Annotation Loop Issue in ROSA Environment

changes/unreleased/Fixed-20240322-171146.yaml, config/rbac/verticadb-operator-cr-user-role.yaml, tests/e2e-leg-3/non-cluster-admin-deployment/45-assert.yaml, tests/e2e-leg-3/non-cluster-admin-deployment/45-create-vrpq-as-fred.yaml, tests/e2e-leg-3/non-cluster-admin-deployment/50-assert.yaml, tests/e2e-leg-3/non-cluster-admin-deployment/50-create-vscr-as-fred.yaml, tests/e2e-leg-3/non-cluster-admin-deployment/setup-vrpq.yaml, tests/e2e-leg-3/non-cluster-admin-deployment/setup-vscr.yaml
Add our two new CRDs to the `verticadb-operator-cr-user-role.yaml` manifest. This manifest, included in our release artifacts, allows cluster admins to grant write permissions for creating and modifying any of our CRDs. We overlooked this when initially adding the CRDs.
Additionally, update our end-to-end test for non-cluster admin deployments to ensure creation of the new CRDs as well.
=> Update role to grant write permissions for new CRDs

api/v1/helpers.go, api/v1/version.go, api/v1/verticadb_types.go, api/v1/verticadb_types_test.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, api/v1beta1/verticadb_types.go, pkg/controllers/vdb/replicatedupgrade_reconciler.go, pkg/controllers/vdb/upgrade.go, pkg/controllers/vdb/upgrade_test.go, pkg/controllers/vdb/verticadb_controller.go
This introduces a new upgrade policy called Replicated. It only adds infrastructure to support this new upgrade process, which aims to allow writes during the upgrade. An empty reconciler has been added, which will be expanded upon in subsequent changes. Only version 24.3.0 can be used with Replicated; a suitable fallback policy is selected if an older version is detected.
The Auto upgrade policy will not select Replicated until it is fully implemented.
As with other upgrade policies, new status conditions have been incorporated.
=> Add replicated upgradePolicy

pkg/controllers/vdb/podfacts.go
We have code to check if the Vertica process is running in the pod using the 'ps' command. In some tests, even after deleting the pod in admintools deployments, we noticed the Vertica process still running. This isn't correct because usually, we have to restart it manually. I suspect the Vertica PID might momentarily appear because it's terminated and waiting to be cleared. I'm not completely sure. Therefore, I'm updating the code to only find the PID for processes that are actively running. If a PID is stopped or terminated, it won't be found. This change will hopefully improve the pass rate for some upgrade tests.
=> Update process check to exclude inactive PIDs

api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, changes/unreleased/Changed-20240325-095511.yaml, pkg/vdbconfig/config.go
Previously, the operator required specifying an endpoint for S3 and GCS communal paths. This pull request modifies that behavior, allowing the endpoint to be left off. In such cases, the server will automatically select a suitable default. For S3 communal paths, the server defaults to https://s3.amazonaws.com, while for GCS endpoints, it defaults to https://storage.googleapis.com.
=> Operator now defaults endpoints for S3/GCS paths.

config/samples/v1beta1_verticarestorepointsquery.yaml
This PR eliminates filter options and labels from the VerticaRestorePointsQuery sample. The intention is to enhance the user experience on OpenShift when generating this CR from the webUI. OpenShift utilizes this sample to prepopulate fields in the webUI interface.
=> Clear filters in VerticaRestorePointsQuery sample

config/samples/v1beta1_verticareplicator.yaml
This PR eliminates labels from the `VerticaReplicator` sample config. The intention is to enhance the user experience on OpenShift when generating this CR from the webUI. OpenShift utilizes this sample to prepopulate fields in the webUI interface.
=> Remove labels in `vrep` sample config

config/samples/v1beta1_eventtrigger.yaml
This PR eliminates labels from the `EventTrigger` sample config. The intention is to enhance the user experience on OpenShift when generating this CR from the webUI. OpenShift utilizes this sample to prepopulate fields in the webUI interface.
=> Remove labels in `et` sample config

changes/unreleased/Fixed-20240403-091605.yaml, pkg/controllers/vdb/restart_reconciler.go, pkg/controllers/vdb/restart_reconciler_test.go
This change is aimed at resolving a specific issue encountered during the deployment of VerticaDB with the ScheduleOnly initialization policy. Previously, when a restart was triggered, the logic in the reconciler would prevent individual nodes from restarting if the cluster lacked quorum based on the pod state. The intention was to let the spread process bring down all remaining nodes before initiating a restart of the entire cluster. However, this approach didn't work with the ScheduleOnly policy because it didn't have a complete view of the cluster; it only had information about the pods running in k8s. There could be other nodes outside of VerticaDB contributing to the cluster's quorum. To address this, I'm refining the logic to perform the quorum check only when the initialization …
=> Fix restart logic for ScheduleOnly init policy

changes/unreleased/Security-20240403-171738.yaml, go.mod, go.sum
This uplifts a package that the operator uses to resolve the [CVE-2024-24786](https://avd.aquasec.com/nvd/cve-2024-24786) vulnerability.
=> Fix CVE-2024-24786

Makefile, changes/unreleased/Security-20240403-173910.yaml, docker-vlogger/Dockerfile, docker-vlogger/README.md
This resolves several security vulnerabilities with the vertica-logger image. It fixes them by pulling in a new version of the base image.
=> Pull in new base for vertica-logger image

pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go
This is a continuation of issue #750. In summary, we're encountering intermittent test failures. Upon deleting the pod in admintools deployments, we observed that the Vertica process shows up in the `ps` output. A new pod should not have Vertica already running because the operator should be triggering that. Although this doesn't impact the operator's functionality, it disrupts end-to-end tests for upgrades, as they rely on the operator's sequential actions. 
I encountered another instance of this issue while investigating with the debug code introduced in #750. It's evident from the `ps` output that the Vertica process belongs to a previous instance of the pod. One clear indication is that the host IP provided to the Vertica process doesn't match the pod's IP. Therefore, I've implemented …
=> Fix e2e test stability

.github/actions/run-e2e-leg/action.yaml, .github/workflows/e2e.yml, kuttl-test.yaml, scripts/image-utils.sh, scripts/setup-kustomize.sh, tests/e2e-leg-9/license/05-create-secrets.yaml, tests/e2e-leg-9/license/10-assert.yaml, tests/e2e-leg-9/license/10-verify-operator.yaml, tests/e2e-leg-9/license/15-assert.yaml, tests/e2e-leg-9/license/15-setup-vdb.yaml, tests/e2e-leg-9/license/20-assert.yaml, tests/e2e-leg-9/license/20-wait-for-createdb.yaml, tests/e2e-leg-9/license/25-wait-for-steady-state.yaml, tests/e2e-leg-9/license/95-delete-cr.yaml, tests/e2e-leg-9/license/95-errors.yaml, tests/e2e-leg-9/license/96-assert.yaml, tests/e2e-leg-9/license/96-cleanup-storage.yaml, tests/e2e-leg-9/license/96-errors.yaml, tests/e2e-leg-9/license/99-delete-ns.yaml, tests/e2e-leg-9/license/setup-vdb/base/kustomization.yaml, tests/e2e-leg-9/license/setup-vdb/base/setup-vdb.yaml, tests/manifests/vertica-license/base/kustomization.yaml
This adds a new leg, e2e-leg-9, to the CI. This is going to be used to test changes done in 24.3.0. One new change with this is that it will use a vertica license so that we can test scaling past 3 nodes. This will be required in order to test out the new replicated upgrade work.
=> Add new leg for 24.3.0 tests

api/v1/version.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go
This PR adds below webhooks rules for sandboxes in CRD:
- cannot scale (up or down) any subcluster that is in a sandbox
- cannot remove a subcluster that is sandboxed. It must be unsandboxed first.
- cannot have multiple sandboxes with the same name
- cannot have the image of a sandbox be different than the main cluster before the sandbox has been setup
- cannot be used on versions older than 24.3.0
- cannot be used before the database has been initialized
- cannot have duplicate subclusters defined in a sandbox
- cannot have a subcluster defined in multiple sandboxes
- cannot have a non-existing subcluster defined in a sandbox
We could add more rules later for sandboxes when we have needs.
=> Add webhook rules for sandboxes

api/v1/helpers.go, pkg/builder/builder.go, pkg/controllers/vdb/httpservercertgen_reconciler.go, pkg/controllers/vdb/replicatedupgrade_reconciler.go, pkg/controllers/vdb/replicatedupgrade_reconciler_test.go, pkg/controllers/vdb/serviceaccount_reconciler.go, pkg/controllers/vdb/suite_test.go, pkg/controllers/vdb/upgrade.go, pkg/meta/annotations.go
This change adds stubs to the replicated upgrade reconciler. It attempts to have the functions present that are needed to do the upgrade. Due to dependencies, such as sandboxing and replication, comprehensive testing is currently limited to unit tests. While this logic might evolve during integration, it gives a framework for how the upgrade should function.
Additionally, I identified new requirements for state management. Two new annotations have been introduced to the VerticaDB: 
- vertica.com/replicated-upgrade-sandbox: to record the name of the sandbox created for the upgrade
- vertica.com/replicated-upgrade-replicator-name: to track the name of the VerticaReplicator CR utilized for replicating data to the sandbox.
=> Add stubs for replicated upgrade

api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go
This PR adds a new webhook rule for sandboxes in CRD: cannot have a primary subcluster defined in a sandbox.
=> Add a new webhook rule for sandboxes

pkg/controllers/vdb/clientroutinglabel_reconciler.go, pkg/controllers/vdb/obj_reconciler.go, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/onlineupgrade_reconciler_test.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/replicatedupgrade_reconciler.go, pkg/controllers/vdb/replicatedupgrade_reconciler_test.go, pkg/controllers/vdb/suite_test.go, pkg/controllers/vdb/upgrade.go
In the replicated upgrade process, we must pause and redirect client connections from subclusters in replica group A to those in replica group B. This is the initial stage of the change. Currently, pause/redirect semantics are not supported, as they require new server modifications that have not yet been implemented. Therefore, we will perform an old-style drain to pause the process and maintain service labels correctly to point to subclusters in replica group B for redirection.
=> Redirect clients to replica group B during replicated upgrade

pkg/controllers/vdb/offlineupgrade_reconciler.go, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/upgrade.go, pkg/events/event.go
If we had selected an upgrade method but ended up failing back to a different method because something was incompatible, we are going to log an event. For instance, if we requested something other than offline upgrade, but we end up in the offline upgrade code path we will have an event message like this:
```
Normal   IncompatibleUpgradeRequested  7m20s                  verticadb-operator  Requested upgrade is incompatible with the Vertica deployment. Falling back to offline upgrade.
```
=> Add event when different upgrade policy is picked

pkg/controllers/vdb/offlineupgrade_reconciler.go, pkg/controllers/vdb/replicatedupgrade_reconciler.go, pkg/controllers/vdb/replicatedupgrade_reconciler_test.go
This will add a status message to the `.status.upgradeStatus` field in the VerticaDB as the operator goes through the various stages of replicated upgrade. It reuses the same design for the other upgrade methods in that we only advance the status message forward. This means that we need to reconcile an iteration, we won't report the first status message again.
=> Add status messages for replicated upgrade

api/v1beta1/helpers.go, changes/unreleased/Changed-20240430-115516.yaml, pkg/controllers/vrpq/query_reconciler.go, pkg/controllers/vrpq/query_reconciler_test.go, pkg/controllers/vrpq/vdbverify_reconciler.go
The VerticaRestorePointsQuery reconciler will keep retrying the query when a previous query has failed. We should check if QueryComplete is present instead of checking if QueryComplete is true to ensure the verification of exactly-once semantics.
The VRep reconciler change will be opened in another PR in vnext branch
=> Give the vdb verification exactly once semantics for vrpq

api/v1/helpers.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, pkg/controllers/vdb/replicatedupgrade_reconciler.go, pkg/controllers/vdb/replicatedupgrade_reconciler_test.go, pkg/iter/sc_finder.go, pkg/iter/sc_finder_test.go, pkg/meta/annotations.go, pkg/names/names.go, tests/e2e-leg-7/restart-kill-sts/15-assert.yaml, tests/e2e-leg-7/restart-kill-sts/20-assert.yaml, tests/e2e-leg-7/restart-kill-sts/30-delete-sts.yaml, tests/e2e-leg-7/restart-kill-sts/35-assert.yaml, tests/e2e-leg-7/restart-kill-sts/40-delete-sts.yaml, tests/e2e-leg-7/restart-kill-sts/45-assert.yaml, tests/e2e-leg-7/restart-kill-sts/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-9/replicated-upgrade-sanity/35-assert.yaml
This adds a new subcluster annotation to control the statefulset name. The new annotation is: `vertica.com/statefulset-name-override`. This is needed for replicated upgrade when the sandbox gets promoted to the main cluster. We will want to rename the sandbox subcluster to match the original names. However, the statefulset name always included the subcluster name. This new annotation will allow us to rename the subcluster while keeping the statefulset name constant. This ensurse we can do a rename without needing to rebuild the statefulset.
=> Decouple subcluster name from its statefulset name

pkg/controllers/vrep/vdbverify_reconciler.go
To follow up on #781, we will verify the presence of QueryReady instead of checking if QueryReady is true. This ensures the verification of exactly-once semantics for vrep.
=> Give the vdb verification exactly once semantics for vrep

pkg/builder/builder.go, pkg/builder/labels_annotations.go, pkg/controllers/vdb/imageversion_reconciler.go, pkg/controllers/vdb/imageversion_reconciler_test.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/sandbox_configmap.go, pkg/controllers/vdb/sandboxsubcluster_reconciler.go, pkg/controllers/vdb/sandboxsubcluster_reconciler_test.go, pkg/controllers/vdb/sandboxupgrade_reconciler_test.go, pkg/controllers/vdb/verticadb_controller.go, pkg/names/names.go, pkg/test/helpers.go, tests/e2e-leg-9/sandbox/35-assert.yaml, tests/e2e-leg-9/sandbox/45-assert.yaml
This will create/update a sandbox config map whenever we create a new sandbox in sandbox reconciler. The config map is watched by sandbox controller for restarting/upgrading the nodes in a sandbox. The config map will be deleted if vdb is deleted or the sandbox is unsandboxed.
=> Create sandbox config maps in sandbox reconciler

api/v1/helpers.go, pkg/controllers/vdb/upgrade_test.go, pkg/controllers/vdb/verticadb_controller.go, pkg/iter/sc_finder_test.go
A nondeterministic failure occurs when a label is updated based on the sandbox spec. We need to ensure that the label is updated only after the status is set by the sandbox subcluster
=> Update sandbox label

pkg/builder/builder.go, pkg/controllers/vdb/sandboxsubcluster_reconciler_test.go, tests/e2e-leg-9/sandbox/35-assert.yaml, tests/e2e-leg-9/sandbox/45-assert.yaml
The ConfigMap should have the name of the VerticaDB, not the database name. The sandbox controller uses this to figure out the correct VerticaDB to fetch.
=> Set VerticaDB name in ConfigMap

api/v1/helpers.go, api/v1/verticadb_types.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, api/v1beta1/verticadb_conversion.go, api/v1beta1/verticadb_conversion_test.go, api/v1beta1/verticadb_types.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/replicatedupgrade_reconciler.go, pkg/controllers/vdb/sandboxsubcluster_reconciler.go, pkg/controllers/vdb/sandboxsubcluster_reconciler_test.go, pkg/controllers/vdb/upgrade.go, pkg/mockvops/mockvops.go, pkg/vadmin/opts/sandboxsc/opts.go, pkg/vadmin/sandbox_sc_vc.go, pkg/vadmin/sandbox_sc_vc_test.go, pkg/vk8s/k8s.go, pkg/vk8s/k8s_test.go, pkg/vk8s/suite_test.go, tests/e2e-leg-9/sandbox/30-assert.yaml, tests/e2e-leg-9/sandbox/50-assert.yaml, tests/e2e-leg-9/sandbox/50-sandbox-another-sc-to-sec1.yaml, tests/e2e-leg-9/sandbox/55-wait-for-steady-state.yaml, tests/e2e-leg-9/sandbox/setup-vdb/base/setup-vdb.yaml
This adds support for multiple subclusters in a single sandbox. In order to denote which subclusters are primary in the sandbox, a new subcluster type is added called 'sandboxprimary'. New webhook rules have been added to account for the new subcluster type.
The new type will get added to the first subcluster in a sandbox. We now add subclusters to a sandbox in the order they are defined in the vdb spec. This ensures that we pick a deterministic subcluster as the first one in a sandbox.
When adding a subcluster to an existing sandbox, we need to pass in a host from the main cluster and the sandbox too. This reason this is needed is that we need to replicate the new sandbox state in both the main cluster and in the sandbox. So, the vclusterOps API will update both clusters.
=> Add support for multiple subclusters in a sandbox

pkg/vadmin/revive_db_vc.go
This was mistakenly removed in the last VCluster API refresh (#741). Without this, if there is an error during revive, then it will complain that local catalog/data/depot dirs are not empty.
=> Use ForceRemoval option with revive

pkg/controllers/vdb/sandboxsubcluster_reconciler.go, tests/e2e-leg-9/sandbox-on-create/05-create-secrets.yaml, tests/e2e-leg-9/sandbox-on-create/10-assert.yaml, tests/e2e-leg-9/sandbox-on-create/10-verify-operator.yaml, tests/e2e-leg-9/sandbox-on-create/15-assert.yaml, tests/e2e-leg-9/sandbox-on-create/15-setup-vdb.yaml, tests/e2e-leg-9/sandbox-on-create/20-assert.yaml, tests/e2e-leg-9/sandbox-on-create/20-wait-for-createdb.yaml, tests/e2e-leg-9/sandbox-on-create/25-wait-for-steady-state.yaml, tests/e2e-leg-9/sandbox-on-create/95-delete-cr.yaml, tests/e2e-leg-9/sandbox-on-create/95-errors.yaml, tests/e2e-leg-9/sandbox-on-create/96-assert.yaml, tests/e2e-leg-9/sandbox-on-create/96-cleanup-storage.yaml, tests/e2e-leg-9/sandbox-on-create/96-errors.yaml, tests/e2e-leg-9/sandbox-on-create/99-delete-ns.yaml, tests/e2e-leg-9/sandbox-on-create/setup-vdb/base/kustomization.yaml, tests/e2e-leg-9/sandbox-on-create/setup-vdb/base/setup-vdb.yaml, tests/e2e-leg-9/verify-vrep/09-create-data-users-tlsconfig.yaml, tests/e2e-leg-9/verify-vrep/20-verify-target-data.yaml, tests/e2e-leg-9/verify-vrep/35-verify-target-sandbox-data.yaml, tests/e2e-leg-9/verify-vrep/50-verify-target-sandbox-data-custom-username.yaml, tests/e2e-leg-9/verify-vrep/65-verify-target-sandbox-data-tls-config.yaml, tests/e2e-leg-9/verify-vrep/70-create-target-sandbox-data.yaml, tests/e2e-leg-9/verify-vrep/85-verify-target-sandbox-data.yaml
This update addresses an issue that occurs when multiple subclusters are added to a new sandbox during the same reconciliation iteration. The problem arose after sandboxing the first subcluster; the second subcluster failed to sandbox.
The failure was due to the need to provide both a host from the main cluster and a host from the sandbox to the vcluster API. To obtain the sandbox host, the system relies on the `vdb.status.sandbox` being updated. Since this update wasn't happening, the process of finding the sandbox host by checking pod facts didn't locate any sandboxed pods.
The solution is to update `vdb.status.sandboxes` as each subcluster is sandboxed. This update allows subsequent sandboxes to find the correct pod facts, ensuring the process completes successfully for all …
=> Fix for many subclusters sandboxed at the same time

pkg/vadmin/restart_node_vc.go, pkg/vadmin/start_db_vc.go, tests/e2e-leg-9/sandbox/60-assert.yaml
In k8s, the node state polling timeout is controlled by the annotation "vertica.com/restart-timeout". If it's not set, the polling timeout is set to 0 which will fail vclusterOps start_db and start_node. Then we will have many cluster/node restart failure events. This PR simply used vclusterOps default polling timeout if the annotation "vertica.com/restart-timeout" is not set.
=> Fixed polling timeout issue of start_db and start_node

tests/e2e-leg-9/replicated-upgrade-sanity/02-assert.yaml, tests/e2e-leg-9/replicated-upgrade-sanity/02-rbac.yaml, tests/e2e-leg-9/replicated-upgrade-sanity/35-assert.yaml, tests/e2e-leg-9/replicated-upgrade-sanity/37-assert.yaml, tests/e2e-leg-9/replicated-upgrade-sanity/37-create-data-in-main-cluster.yaml, tests/e2e-leg-9/replicated-upgrade-sanity/38-assert.yaml, tests/e2e-leg-9/replicated-upgrade-sanity/38-wait-for-replication-finish.yaml, tests/e2e-leg-9/replicated-upgrade-sanity/39-assert.yaml, tests/e2e-leg-9/replicated-upgrade-sanity/39-verify-data-in-sandbox.yaml
In the replicated upgrade, the operator should trigger the replication reconciler after the sandbox is upgraded. The replication reconciler will create a replication CR and copy the data from the main cluster to the sandbox. This PR added an e2e test to verify that replication process.
=> Added e2e test for verifying replication in upgrade

go.mod, go.sum, pkg/controllers/vdb/dbremovesubcluster_reconciler.go, pkg/vadmin/opts/removesc/opts.go, pkg/vadmin/remove_sc_vc.go, pkg/vadmin/remove_sc_vc_test.go
This PR applied new vclusterOps library to fix intermittent failure in online-upgrade-kill-transient test. That intermittent failure is caused by IP inconsistency between the transient node and the catalog. In the new vclusterOps library, we won't check the version of the transient node in start_node, and we will do re-ip before removing the transient node.
=> Fixed intermittent failure in online-upgrade-kill-transient test

.github/workflows/build-images.yml, .github/workflows/e2e.yml
This PR updates the Vertica image to `20240606` to avoid replication errors from the server side. This is a temporary fix, and we will revert this change after fixing the issue on the server side
=> Downgrade Vertica Image for Temporary Fix of e2e-leg-9-vcluster

pkg/controllers/vdb/replicatedupgrade_reconciler.go, pkg/controllers/vdb/upgrade.go
This PR used vsql to close all active user sessions before database replication starts in the replicated upgrade. This can speed up the upgrade process. This is a temporary change. We will improve this by pausing all user sessions soon.
=> Closed user sessions before db replication starts in db upgrade

.github/workflows/e2e.yml
With the change on the server side, we have already fixed the issue in https://github.com/vertica/vertica-kubernetes/pull/832. We can revert to the latest Vertica image to fix the replication issue
=> Revert Latest Vertica Image for E2E Leg9 vCluster

go.mod, go.sum, pkg/vadmin/promote_sandbox_to_main_vc.go, pkg/vadmin/promote_sandbox_to_main_vc_test.go
The latest vclusterOps improves the promote_sandbox API to clean communal storage after sandbox promotion. This PR simply updates vclusterOps library to clean communal storage in the online upgrade.
=> Applied the latest vclusterOps library

pkg/controllers/vdb/replicatedupgrade_reconciler.go, pkg/controllers/vdb/replicatedupgrade_reconciler_test.go, pkg/controllers/vdb/sandbox_configmap.go, tests/e2e-leg-9/replicated-upgrade-sanity/35-assert.yaml, tests/e2e-leg-9/replicated-upgrade-sanity/40-errors.yaml
After promoting sandbox to main, we need to delete sandbox config map to avoid any kind of conflicts as the sandbox does not exist anymore.
=> Remove sandbox configmap after promotion

pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/onlineupgrade_reconciler_test.go
When you do back to back online upgrade, the 2nd time, the new sts names contain the subcluster to mimic names. If any of the names contains an underscore, the sts name will be invalid. This PR converts underscore to hyphen to prevent that.
=> Remove underscore from new statefulset name during second online upgrade

api/v1/helpers.go, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/podfacts.go, pkg/controllers/vdb/podfacts_test.go, pkg/controllers/vdb/restart_reconciler.go
This PR fixed re-ip error when restart the cluster by checking all pods are up and NMA is running in all pods. Without the check, vclusterOps re-ip could fail when NMA is not running or half of the primary nodes are not up.
=> Fixed re-ip error when restart the cluster

tests/e2e-leg-4/revivedb-multi-sc/vdb-to-create/base/setup-vdb.yaml, tests/e2e-leg-4/revivedb-multi-sc/vdb-to-revive/base/setup-vdb.yaml, tests/e2e-leg-9/new-online-upgrade-sanity/55-assert.yaml, tests/e2e-leg-9/new-online-upgrade-sanity/55-kill-one-pod.yaml, tests/e2e-leg-9/new-online-upgrade-sanity/56-assert.yaml, tests/e2e-leg-9/new-online-upgrade-sanity/56-wait-for-restart.yaml
The server side has fixed the bug that the catalog in secondary nodes cannot be refreshed. This PR adds a test to verify that fix.
=> Added a test to verify we can restart secondary nodes after online upgrade

api/v1/helpers.go, api/v1/version.go, api/v1/verticadb_types_test.go, pkg/controllers/vdb/imageversion_reconciler.go, pkg/controllers/vdb/imageversion_reconciler_test.go
This disallow online upgrade for version 24.3.0-0 because an hotfix has been released recently with updeates needed for online upgrade. This is simple on purpose as it is for the target release "2.2.0".
=> Deny online upgrade on version 24.3.0-0

api/v1/helpers.go, api/v1/version.go, pkg/controllers/vdb/imageversion_reconciler.go, pkg/controllers/vdb/podfacts.go, pkg/meta/annotations.go
When we run an online upgrade from Version 24.2.x to 24.3.x, the operator will fail due to pod facts collection error. The reason is that secondary subclusters still use the old Vertica Version 24.2.x when primary subclusters finished the upgrade. As a result, the operator will call vclusterOps API to collect node details on secondary subclusters, but secondary subclusters doesn't have that API due to a low Vertica version.
This PR saved the old Vertica version prior to the upgrade, and used that version to decide if the operator should call vclusterOps API to collect node details during the upgrade.
=> Fixed Online Upgrade Error

api/v1/helpers.go, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/podfacts.go
This PR fixed online upgrade halting issue after sandbox restart. We use vclusterOps to collect node details in online upgrade rather than vsql. This change will remove active connections on the subclusters so subclusters doesn't need to wait for user connections to be paused. As a result, it will fix the halting issue.
=> Fixed online upgrade halting issue

docker-vertica-v2/Dockerfile, docker-vertica/Dockerfile, docker-vertica/Makefile
Legacy and minimal images aren't using ot-harden images as the base images so I removed the option added in #902
=> Removed FOR_GITHUB_CI from legacy and minimal images

api/v1/version.go, pkg/version/version.go, pkg/version/version_test.go
This is an improvement of Vertica version process. Sometimes we support a feature from a specific hotfix of a version. For the low hotfix number, we don't support the feature. This PR allows us to process and compare hotfix numbers in the version.
=> Processed hotfix number in vertica version

pkg/controllers/sandbox/unsandboxsubcluster_reconciler.go, pkg/controllers/vdb/podfacts.go
There is an ND error during the online upgrade. After a successful sandboxing, the config map is deleted by the sandbox controller which is not desired. There is a delay for sandbox controller to get the latest sandbox status. I made the expired sandbox check more strict in this PR. You can download the error logs from Jira VER-96105.
=> Tighten the check for expired sandbox config map

api/v1beta1/helpers.go, api/v1beta1/verticadb_conversion.go, changes/unreleased/Fixed-20240902-223100.yaml, pkg/controllers/vas/k8s.go, pkg/controllers/vas/refreshcurrentsize_reconciler.go, pkg/controllers/vas/subclusterresize_reconciler.go, pkg/controllers/vas/subclusterresize_reconciler_test.go, pkg/controllers/vas/subclusterscale_reconciler.go, pkg/controllers/vas/subclusterscale_reconciler_test.go, pkg/controllers/vas/suite_test.go, pkg/controllers/vas/targetsizeinitializer_reconciler.go, pkg/controllers/vas/targetsizeinitializer_reconciler_test.go, pkg/controllers/vas/vdbverify_reconciler.go
When running a VerticaAutoscaler on a VerticaDB where `vcluster-ops` was not explicitly set to `true` we hit a `CreateContainerError` error. This happens because the autoscaler was still internally  using a v1beta1 VerticaDB which led to the conversion webhook wrongfully setting that annotation to `false`.
This fixes the issue by using a v1 VerticaDB instead.
Closes #908
=> Fix autoscaler bug

scripts/kind.sh
A larger operator log size and longer events duration would be useful for users who want to debug issues on a local Kind cluster. This PR will increase the maximum log size from 10Mi to 100Mi and the duration of events from 1 hour to 24 hours.
On a newly deployed Kubernetes cluster, the pod's log is located under the host /var/log/pods/<pods-name> directory with a maximum log file size of 10Mi (openshift cluster is 50Mi). 
As our verticadb-operator pod's log grows fast as time passes by, especially with online upgrade operations, it's recommended to configure the kubelet argument containerLogMaxSize to increase the maximum log file size to 100Mi.
By default, the k8s cluster clears the events after 1 hour and is not persistent on any disk. The direct way is to add extra args --event-ttl …
=> config kind cluster to increase maximum log file size and event-ttl

docker-vertica-v2/Dockerfile, docker-vertica/Dockerfile
This PR simply installed "strip" command in the build image for stripping /opt/vertica. It should restore the size of Vertica minimal images.
=> Installed strip in build image

.github/workflows/build-images.yml
Since now the minimal image's size is normal and we don't create the restore point in the sandbox, we should be good to use daily vertica images.
=> Used daily minimal image

api/v1beta1/verticascrutinize_webhook.go
Print the log age time default values if they are not set. 
1. log-age-oldest-time default as 24 hours ago if not set
2. log-age-newest-time default as the current time if not set
The example error message would look like:
1. set log-age-oldest-time after the current time, and leave log-age-newest-time not set
* metadata.annotations[vertica.com/scrutinize-log-age-oldest-time]: Invalid value: "2024-09-24 08 +08": log-age-oldest-time cannot be set after current time
* metadata.annotations[vertica.com/scrutinize-log-age-newest-time]: Invalid value: "": log-age-oldest-time cannot be set after log-age-newest-time. log-age-oldest-time is: "2024-09-24 00 UTC", log-age-newest-time default as current time: "2024-09-23 20 UTC".
2. set log-age-newest-time before 24 hours ago, and leave …
=> update log age time default message if not set

Makefile, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/upgrade.go, scripts/guess-server-upgrade-base-image.sh, tests/e2e-leg-9/multi-online-upgrade/30-initiate-upgrade.yaml, tests/e2e-leg-9/new-online-upgrade-pods-down/36-kill-pods-in-main.yaml
the server can now reshard even with DisableNonReplicatableQueries set
sandboxing now properly clears DisableNonReplicatableQueries during sandbox setup, plus cat editor ignores it
=> Remove workarounds for online upgrade

api/v1/verticadb_types.go, api/v1/verticadb_webhook.go, tests/e2e-leg-6/save-restore-point/05-create-restore-point.yaml
To trigger save_restore_point, you have to set the `SaveRestorePointNeeded` status condition. A status condition has many required fields. With this PR, the user will only have to set the type and condition, there is a webhook that will set the other requirered fields.
As an example, before the user would need this: `{"type": "SaveRestorePointNeeded", "status": "True", "message": "test", "reason": "test", "lastTransitionTime": "2024-09-16T21:38:27Z"}`
Now they only have to set 2 fields: `{"type": "SaveRestorePointNeeded", "status": "True"}`
NB: If the webhook is disabled, you will need to explicitly set all the required fields.
=> Update webhook for status condition

changes/unreleased/Added-20240930-144400.yaml, pkg/builder/builder.go, pkg/meta/annotations.go, pkg/reviveplanner/analyze.go, pkg/reviveplanner/analyze_test.go, pkg/reviveplanner/atparser/at_parser.go, pkg/reviveplanner/interface.go, pkg/reviveplanner/util/const.go, pkg/reviveplanner/vcparser/vc_parser.go, tests/e2e-leg-3/revive-with-different-local-paths/35-assert.yaml, tests/e2e-leg-3/revive-with-different-local-paths/37-assert.yaml, tests/e2e-leg-3/revive-with-different-local-paths/37-verify-storage-location-exists.yaml, tests/e2e-leg-3/revive-with-different-local-paths/38-assert.yaml, tests/e2e-leg-3/revive-with-different-local-paths/38-wait-for-restart.yaml, tests/e2e-leg-3/revive-with-different-local-paths/39-verify-storage-locations-is-persistent.yaml, tests/e2e-leg-3/revive-with-different-local-paths/55-assert.yaml, tests/e2e-leg-3/revive-with-different-local-paths/57-verify-storage-location-exists.yaml
This PR supports reviving a database with multiple data paths, temp paths, user paths, and depot paths.
=> Support multiple local pathes in revive_db

DEVELOPER.md, api/v1/version.go, api/v1/verticadb_types_test.go, pkg/controllers/vdb/onlineupgrade_reconciler_test.go, pkg/controllers/vdb/upgrade.go, pkg/controllers/vdb/upgrade_test.go, pkg/version/version.go
kill all sessions during online upgrade when hitting pause timeout when the vertica version is too old to tell us which sessions are paused
=> fix online upgrade pause timeout logic

api/v1/version.go, pkg/catalog/fetch_node_details_vsql.go, pkg/controllers/vdb/podfacts.go
During podfact collection, we add the sandbox state to the query to get node details only for version >= v12.0.4. The issue is that we get the version from the `version` annotation and in the middle of read-only online upgrade it will contain the new version. Therefore, The `select ... from nodes;` will fail for subclusters that still run the old image, if that image is < v12.0.4, because it contains the sandbox state which is not supported. That is why the daily run fails(base_image<v12.0.4 and target_image>v12.0.4).
To fix it, the operator will get the version from the `previous-version` annotation if read-only online upgrade is in progress.
=> Fix admintools read-only upgrade bug from a version < v12.0.4 to a version > v12.0.4

api/v1/version.go, pkg/controllers/vdb/upgrade.go
i was too optimistic about the server change going in in time for the various hotfixes. this makes the pause timeout both less aggressive than without is_paused, but a little more aggressive than is strictly necessary once the server change goes in.
=> pause timeout

api/v1/verticadb_webhook.go, scripts/is-image.sh, tests/e2e-leg-6/save-restore-point/05-create-restore-point.yaml
The reason why normal ci tests were oddly more stable than daily build tests was because we were skipping a lot of them.
We rely on the vertica-version label in the image to skip some tests in case the vertica version is lower than the min required version by the test. The issue is that label is empty for `latest-test-master` which leads to all the tests using that image to be skipped. We need to set that label properly for that image too but in the meantime, we are adding this work-around to not skip some tests.
=> Prevent skipping some tests

.github/workflows/build-images.yml
We have seen trivy scan failure multiple times due to network issues. To make it more robust, maybe add retry to those steps, so we don't have to re-trigger it manually every time. 
First option, using https://github.com/Wandalen/wretry.action. This one doesn't apply good enough in docker run, get docker os issue when trying
Second solution, add a retry step after the build: https://stackoverflow.com/questions/71574593/how-to-automatically-retry-github-action-jobs-on-failure. 
Third option, wrap the trivy script and then call with run script, that way we can use other github actions like: https://github.com/marketplace/actions/retry-step This requires more efforts and need to download the trivy binary to the repo and run as script.
Fourth option, use backup URL to download if failed, as …
=> trivy scan setup backup url for downloading db artifacts

.github/actions/run-e2e-leg/action.yaml, api/v1/helpers.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, pkg/controllers/vdb/obj_reconciler.go, pkg/iter/sc_finder.go, pkg/iter/sc_finder_test.go, tests/e2e-leg-10/sandbox-basic/71-wait-for-steady-state.yaml, tests/e2e-leg-10/sandbox-basic/75-assert.yaml, tests/e2e-leg-10/sandbox-basic/75-terminate-sandbox2.yaml, tests/e2e-leg-10/sandbox-on-create/30-assert.yaml, tests/e2e-leg-10/sandbox-on-create/30-removed-sec2.yaml, tests/e2e-leg-4/vdb-gen/50-assert.yaml, tests/e2e-leg-4/vdb-gen/75-assert.yaml
This fixes the issue that happens when you remove a sandbox and all its subclusters at the same time from the vdb, the pods will be down but will never get deleted.
Now, as soon as unsandbox is done the operator will find the statefulset make it rejoin the main cluster where it will be removed.
=> Remove sandbox and subclusters from vdb at the same time

.golangci.yml, api/v1beta1/verticadb_conversion.go
The new linter version breaks unit test because of the hugeParam size
=> increase hugeparam default size

.github/workflows/e2e.yml
The order of the contains method expect contains(search, items)
We saw unexpected pushes to the Opentext private repo because the order of variables got mixed up.
The expected case should be:
contains(github.event.workflow_run.display_title, 'server daily version')
For example: contains('e2e: server daily version 20241023', 'server daily version')
But seems like the github.event.workflow_run.display_title is an empty string, which causes the condition to be true contains('server daily version, '')
So instead, lets use the inputs.reason as the condition.
=> bug fix on image push action

api/v1/helpers.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go
Here are the rules that are implemented by this change.
- When creating a vdb, all subclusters and sandboxes(if any) must not have `shutdown` set to true.
- If a sandbox has `shutdown`(spec) true and any of its subclusters has the annotation "vertica.com/shutdown-driven-by-sandbox" set to true in the old vdb, we should prevent the user from updating that subcluster's shutdown field.
- You cannot unsandbox a subcluster with `shutdown` true(spec and/or status) or part of a sandbox with `shutdown` true
- You cannot change spec.sandboxes[].image if the sandbox has `shutdown` true or has any subcluster with `shutdown` true(spec and/or status)
- You cannot terminate a sandbox if it has has `shutdown` true. terminate means removing the sandbox in spec.sandboxes[] and its subclusters in …
=> webhook rules for sandbox shutdown

api/v1/helpers.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go
Here are the rules implemented in this PR:
- you cannot sandbox a subcluster with shutdown true(spec or status).
- you cannot add a subcluster to a sandbox that has the shutdown field set to true
- you cannot add a subcluster to a sandbox that already has at least one subcluster with shutdown true
- you cannot scale (up/down) a subcluster with shutdown true(spec or status)
- You cannot remove a subcluster with shutdown true(spec or status)
=> Ver 97254 shutdown webhook

tests/e2e-leg-6/verify-server-logrotate/expected-output/logrotateTimerServiceOut.txt, tests/e2e-leg-6/verify-server-logrotate/sql-input/logrotate.sql
This PR add a new method in server log rotate SQL file, select clear_data_collector('TraceProfiles');
and new expected output to match the server test cases.
=> add trace profile data collector clean up

api/v1beta1/verticareplicator_webhook.go, api/v1beta1/verticareplicator_webhook_test.go, cmd/operator/main.go, config/webhook/manifests.yaml
Add webhook for VerticaReplicator. It enforces the following rules:
- Only one of the following should be specified: table, schema, pattern, or pattern with exclusion
- Make sure the new field "mode" only has one of the following fields: async, sync or empty string(for backward compatibility)
- Object name, include/exclude pattern, and target namespace cannot be used in sync mode
=> Add VerticaReplicator webhook

pkg/builder/builder.go, pkg/meta/annotations.go
The proxy config map should use the annotation value of vertica.com/client-proxy-log-level. This pr is for updating the logic by replacing the hardcoded value.
=> use annotations proxy log level

pkg/builder/labels_annotations.go, pkg/controllers/vdb/obj_reconciler.go, tests/e2e-leg-11/client-proxy/40-add-subcluster.yaml, tests/e2e-leg-11/client-proxy/40-assert.yaml
When creating a deployment, a replicaset is created for each replica. When the update strategy is `RollingUpdate`, each time there is a change in the deployment spec, an extra pod will be created with the update and the old one will be deleted once the new one is ready. So there is a timing where you may see twice the number of pods with respect to what you expect. 
During testing, QA found that each time we create a proxy deployment, at first we had twice the number of required pods before getting the correct number after a few seconds. That is because we updated the deployment by adding the server version annotation when it is available in the vdb. That annotation does't serve any purpose so I just removed to avoid updating the deployment.
=> Prevent proxy deployment update

.github/actions/run-e2e-leg/action.yaml, pkg/controllers/vdb/verticadb_controller.go, tests/e2e-leg-10/sandbox-upgrade-happy-path/55-assert.yaml
A bug was found in sandbox-upgrade-happy-path test case. The sandbox is upgraded and then removed (unsandboxed). After unsandboxing, we restart all the pods of the former sandbox. The issue is that the subcluster that joins the main cluster is not running the same image, so we get stuck for a while in startnode(HTTPSPollNodeStateIndirectOp) until the timeout(1200s). After timeout expires, it will requeue and run `UnsandboxImageVersionReconciler` which will recreate the pods with the correct image and next the next startnode attempt will succeed.  The solution consists in calling `UnsandboxImageVersionReconciler` just before the restart reconciler.
=> Fix sandbox-upgrade-happy-path

changes/unreleased/Security-20241219-123023.yaml, go.mod, go.sum, pkg/meta/annotations.go
This PR updated GO net library to 0.33 for fixing CVE-2024-45338.
=> Fixed CVE-2024-45338

api/v1beta1/verticaautoscaler_types.go
I would like to get some feedback before generating code for new those fields.
=> initial draft for review before generating code

DEVELOPER.md, config/samples/v1beta1_verticaautoscaler_custom_metrics.yaml
Update Developer doc with customize interval explanation. Add example of VerticaAutoscaler under sample.
=> Prometheus adapter custom time range

config/samples/v1beta1_verticaautoscaler_custom_metrics.yaml, prometheus/adapter.yaml, tests/e2e-leg-12/prometheus-sanity/31-wait-for-metrics.yaml, tests/e2e-leg-12/prometheus-sanity/35-verify-custom-metrics.yaml
1 add vertica_sessions_active_count object metric
2 fix e2e test prometheus-sanity
=> add new object metric and fix e2e test

config/samples/v1beta1_verticaautoscaler_custom_metrics.yaml, prometheus/adapter.yaml, tests/e2e-leg-12/prometheus-sanity/35-verify-custom-metrics.yaml
This is the first step to enable the metric vertica_queued_requests_total. Some future work would include adding new test cases to test together with hpa.
=> Add metric vertica_queued_requests_total

.github/actions/run-e2e-leg/action.yaml, .github/workflows/e2e.yml, scripts/setup-minio.sh
This PR uses a Github extension to auto retry e2e test upon failure. Given the instability of K8s e2e test, a retry mechanism reduces the need for manual reruns and enhances the success rate of the CI/CD pipeline.
=> Implement a retry mechanism in e2e test

pkg/builder/builder.go, pkg/builder/labels_annotations.go, pkg/controllers/sandbox/sandbox_controller.go, pkg/controllers/sandbox/unsandboxsubcluster_reconciler_test.go, pkg/controllers/vdb/clientroutinglabel_reconciler.go, pkg/controllers/vdb/clientroutinglabel_reconciler_test.go, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/controllers/vdb/sandbox_configmap.go, pkg/controllers/vdb/sandboxsubcluster_reconciler.go, pkg/controllers/vdb/unsandboxsubcluster_reconciler_test.go, pkg/meta/annotations.go, tests/e2e-leg-10/sandbox-restart/57-check-connection.yaml
When a sandbox pod is deleted, the operator does not put back the routing label. This adds the ClientRoutingLabelReconciler in the sandbox controller. It also adds an annotation in the configMap to sometimes disable routing, like in the case of online upgrade where routing to the sandbox must not be allowed until replication is done.
=> Add routing label to sandbox pods

api/v1/helpers.go, pkg/builder/builder.go, pkg/meta/annotations.go
Introduce annotation `vertica.com/disable-depot-volume-management: "true"|"false"`
Its purpose is to disable volume management for the depot volume, thus allowing specific scenarios such as providing the Depot as an ephemeral PVC for scratch storage, distinct from a regular PVC (with independent lifecycle) and from an EmptyDir (residing directly on the host OS filesystem).
We use it because our ephemeral storage is a local PV bound by an ephemeral PVC and it needs to have the same lifecycle as our pod (destroyed when the pod is destroyed, created when the pod is created) and is co-located on the same node, so it can't be carried across node changes.
- EmptyDir does not work because EmptyDir specifically uses the k8s host filesystem
- a regular PVC does not have its lifecycle managed …
=> feat(annotation): allow to disable depot volume management

api/v1/helpers.go, pkg/builder/builder.go, pkg/meta/annotations.go
Introduce annotation `vertica.com/disable-depot-volume-management: "true"|"false"`
Its purpose is to disable volume management for the depot volume, thus allowing specific scenarios such as providing the Depot as an ephemeral PVC for scratch storage, distinct from a regular PVC (with independent lifecycle) and from an EmptyDir (residing directly on the host OS filesystem).
We use it because our ephemeral storage is a local PV bound by an ephemeral PVC and it needs to have the same lifecycle as our pod (destroyed when the pod is destroyed, created when the pod is created) and is co-located on the same node, so it can't be carried across node changes.
- EmptyDir does not work because EmptyDir specifically uses the k8s host filesystem
- a regular PVC does not have its lifecycle managed …
=> feat(annotation): allow to disable depot volume management (#1085)

api/v1/helpers.go, api/v1/verticaautoscaler_types.go, api/v1/verticaautoscaler_webhook.go, api/v1/verticaautoscaler_webhook_test.go
Add webhook rules for custom autoscaler as continued work of #1071:
- maxReplicas cannot be less than minReplicas
- maxReplicas must be set
- cannot set customAutoscaler after CR creation
- 2 metrics cannot have the same name
- if spec.customAutoscaler.scaledObject.metrics[].type is "prometheus", spec.customAutoscaler.scaledObject.metrics[].prometheus must not be nil, if it is "cpu" or "memory", spec.customAutoscaler.scaledObject.metrics[].resource must not be nil
- scaledownThreshold must be of the same type as the threshold used for scaleup.
- customAutoscaler.hpa must be non-nil if customAutoscaler.type == "HPA" / - customAutoscaler.scaledObject must be non-nil if customAutoscaler.type == "ScaledObject" or empty
=> Add addtional webhook custom autoscaler

pkg/controllers/vdb/restart_reconciler.go, pkg/vadmin/opts/reip/opts.go, pkg/vadmin/re_ip_vc.go, pkg/vadmin/re_ip_vc_test.go
This PR will fix two sandbox restart issues:
1. cannot find vertica nodes to re-ip.
2. some vertica nodes have HTTPs service up but haven't joined the main cluster.
The first issue is fixed by adding the option "sandboxName" in vclusterOps re-ip call.
The second issue is fixed by killing all vertica nodes before start_db.
=> Fixed sandbox restart issue

api/v1/verticaautoscaler_webhook.go, api/v1/verticaautoscaler_webhook_test.go
Made a mistake when I read the rule: - When spec.customAutoscaler.hpa.scaledownThreshold is set, scaledown stabilisation window must be 0, where the scaledownThreshold should be scaleInThreshold, not behavior.ScaleDown. So the condition shouldn't check the behavior field. 
Also need to instantiate the attribute to make sure there is no nil pointer. Added some unit more unit test to cover the case
=> fix default value condition

.github/CODEOWNERS, api/v1/helpers.go, api/v1/verticaautoscaler_webhook.go, api/v1/verticaautoscaler_webhook_test.go
- make sure the 2 annotations are not same at same time
- make sure their value after conversion is valid
- make sure `paused-autoscaling-replicas` is lower than replicas and positive
=> Add webhook for autoscaler pausing annotations

api/v1/helpers.go, pkg/controllers/vdb/nmacertconfigmapgen_reconciler.go, pkg/controllers/vdb/nmacertconfigmapgen_reconciler_test.go, pkg/controllers/vdb/tlsservercertgen_reconciler_test.go
In `pkg/controllers/vdb/nmacertconfigmapgen_reconciler.go` we were checking for k8s secrets only. This checks for any supported secret store. I also addded unit tests.
=> Handle checking secret from any secret stores before generating nma cert configmap

pkg/controllers/vdb/createdb_reconciler.go
Use "FALLTHROUGH" to create authentication. That allows users to use password to connect to https service when TLS is enabled. 
The authentication is also renamed from "auth_tls" to "k8s_tls_builtin_auth" to avoid being deleted by users.
This change will fix "k-safety-0-scaling" and "k-safety-1-scaling" in leg 1.
All test cases in leg 1 can be run both with and without TLS.
=> use FALLTHROUGH, rename auth_tls to k8s_tls_builtin_auth

pkg/controllers/vdb/restart_reconciler.go
In some cases, killing the spread process does not terminate the Vertica process, leading to a slow restart (health prob will kill vertica process eventually). In this PR, I killed both the spread and Vertica processes before initiating a cluster restart. This change should enhance the stability of e2e tests.
=> Improved K8s Cluster Restart

api/v1/helpers.go, api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go
Added webhook to error if restore point archive name contains an invalid character. Supported characters for archive name are the same as DB name, except archive name also supports dash character.
=> Add webhook to validate restore point archive name has no invalid chars

api/v1beta1/verticascrutinize_types.go, pkg/controllers/vscr/scrutinizepod_reconciler.go, pkg/controllers/vscr/scrutinizepod_reconciler_test.go, pkg/controllers/vscr/vdbverify_reconciler.go, pkg/controllers/vscr/verticascrutinize_controller.go, pkg/events/event.go, tests/e2e-leg-10/sandbox-on-create/40-create-vscr.yaml, tests/e2e-leg-10/sandbox-on-create/41-assert.yaml, tests/e2e-leg-10/sandbox-on-create/41-verify-pod-created.yaml, tests/e2e-leg-10/sandbox-on-create/42-assert.yaml, tests/e2e-leg-10/sandbox-on-create/42-wait-for-scrutinize.yaml, tests/e2e-leg-10/sandbox-on-create/43-check-tarball.yaml, tests/e2e-leg-6/collect-scrutinize/08-assert.yaml, tests/e2e-leg-6/collect-scrutinize/08-create-vscr.yaml
Added "sandbox" to VerticaScrutinize. When set, we will collect Scrutinize using the hosts of the specified sandbox; if omitted, we will collect from main cluster, as before. Also added error handling when invalid sandbox name is specified.
=> Add sandbox option to VerticaScrutinize, to run using sandbox hosts instead of main cluster

cmd/operator/main.go
In the current state, we run into the following when trying to run this outside of cluster.
```bash
2025-04-15T07:58:23.096Z        INFO    setup   Operator Config {"controllersScope": "cluster", "version": "", "watchNamespace": "", "webhooksEnabled": true, "controllersEnabled": true, "broadcasterBurstSize": 25}
2025-04-15T07:58:23.097Z        ERROR   setup   unable to start manager {"error": "unable to find leader election namespace: not running in-cluster, please specify LeaderElectionNamespace"}
```
with this commit the manager binary can run of cluster as well.
```bash
make build
export CONCURRENCY_VERTICADB=5
export CONCURRENCY_VERTICAAUTOSCALER=1
export CONCURRENCY_EVENTTRIGGER=1
export CONCURRENCY_VERTICARESTOREPOINTSQUERY=1
export CONCURRENCY_VERTICASCRUTINIZE=1
export …
```
=> allow manager binary to run outside of cluster

cmd/operator/main.go
In the current state, we run into the following when trying to run this outside of cluster.
```bash
2025-04-15T07:58:23.096Z        INFO    setup   Operator Config {"controllersScope": "cluster", "version": "", "watchNamespace": "", "webhooksEnabled": true, "controllersEnabled": true, "broadcasterBurstSize": 25}
2025-04-15T07:58:23.097Z        ERROR   setup   unable to start manager {"error": "unable to find leader election namespace: not running in-cluster, please specify LeaderElectionNamespace"}
```
with this commit the manager binary can run of cluster as well.
```bash
make build
export CONCURRENCY_VERTICADB=5
export CONCURRENCY_VERTICAAUTOSCALER=1
export CONCURRENCY_EVENTTRIGGER=1
export CONCURRENCY_VERTICARESTOREPOINTSQUERY=1
export CONCURRENCY_VERTICASCRUTINIZE=1
export …
```
=> allow manager binary to run outside of cluster (#1195)

api/v1/verticadb_webhook.go, api/v1/verticadb_webhook_test.go, changes/unreleased/Fixed-20250417-183709.yaml
When initPolicy is set to Revive and database is initialized, we have a webhook to prevent users to create restore points. I fixed that webhook.
=> Fixed the issue where users cannot create restore point

changes/unreleased/Fixed-20250414-174731.yaml, scripts/template-helm-chart.sh
The issue was found in #1188. We will always try to create the metrics rbac avan when createRbacProxy is "Disable". This will conditionally create the rbac like before.
=> Add back the feature gate flag to disable the RBAC creation for metrics

api/v1/helpers.go, pkg/meta/annotations.go, pkg/vadmin/fetch_node_details_vc.go, pkg/vadmin/interface.go
This will make debugging easier by disabling the fetch_node_details info log.
=> Disable fetch_node_details info log

.github/CODEOWNERS, .github/workflows/e2e.yml, pkg/controllers/vdb/restart_reconciler.go, pkg/controllers/vdb/sandboxsubcluster_reconciler.go, pkg/meta/annotations.go, pkg/podfacts/podfacts.go, pkg/vadmin/restart_node_vc.go
In K8s realdb, when a sandbox subcluster is shut down and then restarted, it may remain down and never come back up. This happens because, during the restart reconciliation, the pods in the sandbox subcluster are not in a Running state—so the reconciler skips the restart and does not requeue the task. As a result, the sandbox restart reconciler is never triggered again.
This PR addresses that issue.
=> Fixed Issue with Restarting Pods in Sandbox Subcluster

changes/unreleased/Fixed-20250428-160725.yaml, pkg/podfacts/podfacts.go
On the IPv6-enabled k8s cluster, the operator would restart the Vertica pods after the database creation. The root cause is that it could not detect the node's up status with the IPv6 URL. A bracket was added to the IPv6 address to resolve the issue.
=> Add brackets to IPv6 address to check if node up

api/v1/helpers.go, pkg/controllers/vdb/sandboxshutdown_reconciler.go, pkg/controllers/vdb/shutdownspec_reconciler.go, pkg/controllers/vdb/shutdownspec_reconciler_test.go, pkg/controllers/vdb/verticadb_controller.go
In a previous PR, I decided to call sandboxshutdown _reconciler early in the reconcile loop, to prevent some failures to affect some sandbox ops. The issue is that it might be possible that (ex: realdb) someone is adding a new sandbox +subclusters and that will fail sandboxshutdown _reconciler. The 2nd sandboxshutdown _reconciler does not have this issue because it happens towards the end when all critical reconcilers have been run.
To fix this, I added a field `IgnoreError` that is true for the 1st sandboxshutdown _reconciler. When true, if a subcluster is not yet in the status, we just skip that sc knowing a later reconciler will add it to the db.
=> Fix sandboxshutdown _reconciler

api/v1/helpers.go, pkg/controllers/vdb/sandboxshutdown_reconciler.go, pkg/controllers/vdb/shutdownspec_reconciler.go, pkg/controllers/vdb/shutdownspec_reconciler_test.go, pkg/controllers/vdb/verticadb_controller.go
In a previous PR, I decided to call sandboxshutdown _reconciler early in the reconcile loop, to prevent some failures to affect some sandbox ops. The issue is that it might be possible that (ex: realdb) someone is adding a new sandbox +subclusters and that will fail sandboxshutdown _reconciler. The 2nd sandboxshutdown _reconciler does not have this issue because it happens towards the end when all critical reconcilers have been run.
To fix this, I added a field IgnoreError that is true for the 1st sandboxshutdown _reconciler. When true, if a subcluster is not yet in the status, we just skip that sc knowing a later reconciler will add it to the db.
=> Fix sandbox_shutdown

.github/workflows/e2e.yml, Makefile, pkg/controllers/vdb/onlineupgrade_reconciler.go, pkg/vadmin/get_config_parameter_vc.go, pkg/vadmin/get_config_parameter_vc_test.go, pkg/vadmin/manage_connection_draining_vc.go, pkg/vadmin/set_config_parameter_vc.go, pkg/vadmin/vc.go, scripts/guess-server-upgrade-base-image.sh, tests/e2e-leg-9/multi-online-upgrade/30-initiate-upgrade.yaml
The base version for upgrade is 24.4.0 so if you upgrade to 25.3.0, as there is no tls config, http calls after upgrade will all fail.
This picks a 25.3.0 image if certs are enabled .
=> Fix upgrade with certs

pkg/controllers/vdb/obj_reconciler.go, pkg/secrets/fetcher.go
The issue is "reconcileTLSSecrets()" in obj_reconciler.go. That function must be used for k8s secrets only. When the secret is in awssm, we would try to get it using k8s api, which of course will fail. Now we first check if the tls secret is in k8s and skip it if that's not the case
=> Fix bug in obj_reconciler

local-libs/vcluster/vclusterops/set_tls_config.go
Cache duration does not work and fails all the "cert" tests. This is a temporary change to allow tests to pass until it is fixed.
=> Disable cache duration

pkg/builder/builder.go, pkg/cmds/exec.go, pkg/cmds/fake.go, pkg/controllers/sandbox/sandbox_controller.go, pkg/controllers/vdb/verticadb_controller.go, pkg/controllers/vrep/replication_reconciler.go, pkg/controllers/vrep/replication_status_reconciler.go
This PR appended "-m allow" to vsql command when annotation "enable-tls-auth" is set to "true". This is for the user that needs to set tls version to 1.3 in Vertica. For tls 1.3, a connection with tls will fail immediately.
=> Allowed vsql connection without certs

tests/e2e-leg-12/scale-out-with-threshold-keda/45-assert.yaml, tests/e2e-leg-12/scale-out-with-threshold-keda/45-create-vas.yaml
scale-out-with-threshold-keda sometimes fails at step 50 because the cluster is scale out to 5 instead of 4. This set max replicas to 4 so it can not scale out above 4.
=> Make scale out test stable

pkg/controllers/vdb/obj_reconciler.go, pkg/controllers/vdb/subclustershutdown_reconciler.go, pkg/controllers/vdb/subclustershutdown_reconciler_test.go
We found that restarting a subcluster after shutdown did not work because obj_reconciler will overwrite the expected size with the current size which in this case is zero. This fixes that issue.
=> Fix shutdown subcluster issue

local-libs/vcluster/vclusterops/tls_rotate_certs.go, pkg/controllers/vdb/clientservertlsupdate_reconciler.go, pkg/controllers/vdb/httpstlsupdate_reconciler.go, pkg/controllers/vdb/tls_config.go, pkg/podfacts/podfacts.go, pkg/vadmin/opts/rotatetlscerts/opts.go, pkg/vadmin/rotate_tls_certs_vc.go
This PR enables passing host information directly to the TLS rotate API, eliminating the need for the API to fetch it from the HTTPS service. This allows rolling back HTTPS TLS certificates using only the old certificate.
=> Pass host info to tls rotate api

.gitignore, tests/e2e-leg-2-at-only/schedule-only/setup-managed-vdb/base/setup-vdb.yaml
Before removing v1beta1, encryptSpreadComm's default value (when left empty) was "disabled". But the default value on v1 is "vertica". That will stop the db before step 40(add-node) which causes the failure.
The fix is to explicitely set encryptSpreadComm to disabled.
=> Fix schedule-only test
